// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "actions:updated": string;
            "activity:appended": number;
            "auth:updated": string;
            "flows:updated": string;
            "jobs:updated": string;
            "log:appended": number;
        }
    }
}
