// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FeedService provides mock desktop feed data until GitHub-backed sources exist.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ActionsFor returns the actions available for a PR or issue.
 */
export function ActionsFor(kind: string): $CancellablePromise<$models.Action[] | null> {
    return $Call.ByID(504720659, kind);
}

/**
 * Items returns the mock feed items. Profile and feed IDs are reserved for the
 * future GitHub-backed implementation.
 */
export function Items(profileID: string, feedID: string): $CancellablePromise<$models.FeedItem[] | null> {
    return $Call.ByID(1168225591, profileID, feedID);
}

/**
 * Profiles returns the profiles shown in the desktop rail.
 */
export function Profiles(): $CancellablePromise<$models.Profile[] | null> {
    return $Call.ByID(1352748783);
}
