// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FeedService is the Wails service exposing feed data to the frontend. All
 * data comes from the injected feed.Provider; this type is wire glue only.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as feed$0 from "../internal/desktop/feed/models.js";

/**
 * ActionsFor returns the actions available for a PR or issue.
 */
export function ActionsFor(kind: string): $CancellablePromise<feed$0.Action[] | null> {
    return $Call.ByID(504720659, kind);
}

/**
 * Items returns the items of one feed, or of every feed in the profile when
 * feedID is empty.
 */
export function Items(profileID: string, feedID: string): $CancellablePromise<feed$0.Item[] | null> {
    return $Call.ByID(1168225591, profileID, feedID);
}

/**
 * MarkRead records an item as read app-locally.
 */
export function MarkRead(profileID: string, itemID: string): $CancellablePromise<void> {
    return $Call.ByID(128492524, profileID, itemID);
}

/**
 * Profiles returns the profiles shown in the desktop rail.
 */
export function Profiles(): $CancellablePromise<feed$0.Profile[] | null> {
    return $Call.ByID(1352748783);
}
