// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FeedService is the Wails service exposing feed data to the frontend. All
 * data comes from the injected feed.Provider; this type is wire glue only.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as feed$0 from "../internal/desktop/feed/models.js";

/**
 * ActionsFor returns the actions available for a PR or issue.
 */
export function ActionsFor(kind: string): $CancellablePromise<feed$0.Action[] | null> {
    return $Call.ByID(504720659, kind);
}

/**
 * Config describes the profiles config file: path, content, validity.
 */
export function Config(): $CancellablePromise<feed$0.ConfigInfo> {
    return $Call.ByID(3084968143);
}

/**
 * ConfigPrompt returns a paste-ready prompt for a coding agent to edit the
 * profiles config on the user's behalf.
 */
export function ConfigPrompt(): $CancellablePromise<string> {
    return $Call.ByID(3108030981);
}

/**
 * CreateFeed persists a new feed in the profile (ID derived from the name)
 * and returns the feed's materialized summary.
 */
export function CreateFeed(profileID: string, def: feed$0.FeedDef): $CancellablePromise<feed$0.Source> {
    return $Call.ByID(2859570357, profileID, def);
}

/**
 * CreateProfile creates a workspace seeded with the default feeds.
 */
export function CreateProfile(name: string): $CancellablePromise<feed$0.Profile> {
    return $Call.ByID(2100022366, name);
}

/**
 * CreateSource persists a new top-level source and returns it with its
 * assigned ID.
 */
export function CreateSource(def: feed$0.SourceDef): $CancellablePromise<feed$0.SourceDef> {
    return $Call.ByID(3542744264, def);
}

/**
 * FeedDefFor returns one feed's definition, for edit prefill.
 */
export function FeedDefFor(profileID: string, feedID: string): $CancellablePromise<feed$0.FeedDef> {
    return $Call.ByID(3622655147, profileID, feedID);
}

/**
 * Items returns the items of one feed, or of every feed in the profile when
 * feedID is empty.
 */
export function Items(profileID: string, feedID: string): $CancellablePromise<feed$0.Item[] | null> {
    return $Call.ByID(1168225591, profileID, feedID);
}

/**
 * MarkRead records an item as read app-locally.
 */
export function MarkRead(profileID: string, itemID: string): $CancellablePromise<void> {
    return $Call.ByID(128492524, profileID, itemID);
}

/**
 * Profiles returns the profiles shown in the desktop rail.
 */
export function Profiles(): $CancellablePromise<feed$0.Profile[] | null> {
    return $Call.ByID(1352748783);
}

/**
 * Refresh refetches the sources the profile's feeds reference, bypassing the
 * search cache TTL, and reports whether anything changed. Backs the manual
 * "Refresh now" action.
 */
export function Refresh(profileID: string): $CancellablePromise<boolean> {
    return $Call.ByID(2193367500, profileID);
}

/**
 * Sources returns the top-level source definitions, for the feed editor's
 * source picker.
 */
export function Sources(): $CancellablePromise<feed$0.SourceDef[] | null> {
    return $Call.ByID(1179368585);
}

/**
 * UpdateFeed replaces the feed's definition; the feed keeps its ID.
 */
export function UpdateFeed(profileID: string, feedID: string, def: feed$0.FeedDef): $CancellablePromise<void> {
    return $Call.ByID(3440431000, profileID, feedID, def);
}
