// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Action is an action offered for a feed item's kind.
 */
export interface Action {
    "id": string;
    "icon": string;
    "color": string;
    "title": string;
    "sub": string;
    "primary": boolean;
}

/**
 * FeedItem is an item from a profile feed.
 */
export interface FeedItem {
    "id": string;

    /**
     * "PR" | "Issue"
     */
    "kind": string;
    "repo": string;
    "num": number;
    "title": string;
    "author": string;
    "age": string;
    "unread": boolean;
    "labels": string[] | null;
    "branch": string;
    "body": string;
    "prompt": string;
}

/**
 * FeedSource is a selectable source within a profile.
 */
export interface FeedSource {
    "id": string;
    "name": string;
    "count": number;
    "newCount": number;
}

/**
 * Profile is a desktop feed profile and its available sources.
 */
export interface Profile {
    "id": string;
    "letter": string;
    "name": string;
    "sourceSummary": string;
    "totalCount": number;
    "unreadCount": number;
    "feeds": FeedSource[] | null;
}
