// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FlowSummary is one flow file's listing row for the flows picker: identity
 * plus load/validity status, so a broken flow file shows up (with its
 * error) instead of silently vanishing from the list.
 */
export interface FlowSummary {
    "id": string;
    "name": string;
    "enabled": boolean;
    "valid": boolean;
    "error"?: string;
    "warnings"?: string[] | null;
}

/**
 * GithubSettings is the GitHub integration's editable configuration.
 */
export interface GithubSettings {
    "pollIntervalSeconds": number;
    "minPollIntervalSeconds": number;
}

/**
 * PathInfo describes a single on-disk location surfaced in settings.
 */
export interface PathInfo {
    "path": string;

    /**
     * Exists reports whether the path is present on disk right now (a log file
     * or database may not exist until first written).
     */
    "exists": boolean;

    /**
     * Overridden reports whether a stored override backs this location. Only
     * meaningful for the data and config directories; always false otherwise.
     */
    "overridden": boolean;
}

/**
 * SystemInfo is the full set of locations shown on the System settings screen.
 */
export interface SystemInfo {
    "dataDir": PathInfo;
    "configDir": PathInfo;
    "logFile": PathInfo;
    "database": PathInfo;
}
