// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FlowSummary is one flow file's listing row for the flows picker: identity
 * plus load/validity status, so a broken flow file shows up (with its
 * error) instead of silently vanishing from the list.
 */
export interface FlowSummary {
    "id": string;
    "name": string;
    "enabled": boolean;
    "valid": boolean;
    "error"?: string;
    "warnings"?: string[] | null;
}
