// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PipelineService is the Wails service exposing the desktop pipeline's
 * event log and commit protocol to the frontend. All data comes from the
 * injected *pipelinedb.DB; this type is wire glue only, matching
 * FeedService's thin-glue style.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as feed$0 from "../internal/desktop/feed/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pipeline$0 from "../internal/desktop/pipeline/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pipelinedb$0 from "../internal/desktop/pipeline/pipelinedb/models.js";

/**
 * ActionsFor returns the configured actions for an item kind ("PR"/"Issue"),
 * for the detail-pane action picker. The catalog is static today (see
 * feed.ActionsFor); this is the seam where actions.yml-driven actions plug in.
 */
export function ActionsFor(kind: string): $CancellablePromise<feed$0.Action[] | null> {
    return $Call.ByID(1014871757, kind);
}

/**
 * Commit applies the frontend graph runtime's batch atomically: it upserts
 * feed outputs, enqueues action outputs, records node-run metrics, and
 * advances the consumer's offset to batch.UpToOffset. Idempotent by offset:
 * replaying a batch already applied (UpToOffset <= the consumer's current
 * offset) is a no-op.
 */
export function Commit(batch: pipeline$0.CommitBatch): $CancellablePromise<void> {
    return $Call.ByID(2833242122, batch);
}

/**
 * FeedItemCounts returns per-feed total/unread counts for every feed in a
 * flow, for the sidebar's rail badges.
 */
export function FeedItemCounts(flowID: string): $CancellablePromise<pipeline$0.FeedCount[] | null> {
    return $Call.ByID(460495308, flowID);
}

/**
 * FeedItems returns the persisted items for a feed, newest first.
 */
export function FeedItems(feedID: string): $CancellablePromise<pipeline$0.FeedItem[] | null> {
    return $Call.ByID(2832766353, feedID);
}

/**
 * MarkFeedItemRead clears the unread flag on one feed item.
 */
export function MarkFeedItemRead(feedID: string, itemID: string): $CancellablePromise<void> {
    return $Call.ByID(3950941725, feedID, itemID);
}

/**
 * NodeRuns returns up to limit of a flow's most recent node_run rows,
 * newest first, for the flows canvas's live per-node status and RECENT
 * activity list.
 */
export function NodeRuns(flowID: string, limit: number): $CancellablePromise<pipeline$0.NodeRunRecord[] | null> {
    return $Call.ByID(2130853077, flowID, limit);
}

/**
 * ReadFrom returns up to limit event_log rows appended after offset, in
 * ascending order.
 */
export function ReadFrom(offset: number, limit: number): $CancellablePromise<pipelinedb$0.Msg[] | null> {
    return $Call.ByID(2706344123, offset, limit);
}
