// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PipelineService is the Wails service exposing the desktop pipeline's
 * event log, configured actions, and commit protocol to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as feed$0 from "../internal/desktop/feed/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pipeline$0 from "../internal/desktop/pipeline/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as actions$0 from "../internal/desktop/pipeline/actions/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pipelinedb$0 from "../internal/desktop/pipeline/pipelinedb/models.js";

/**
 * ActionViews returns the configured actions available for an item kind
 * ("PR"/"Issue"). The actions store is the single source for both these
 * detail-pane views and flow output actions.
 */
export function ActionViews(kind: string): $CancellablePromise<actions$0.View[] | null> {
    return $Call.ByID(2696790941, kind);
}

/**
 * Commit applies the frontend graph runtime's batch atomically: it upserts
 * feed outputs, enqueues action outputs, records node-run metrics, and
 * advances the consumer's offset to batch.UpToOffset. Idempotent by offset:
 * replaying a batch already applied (UpToOffset <= the consumer's current
 * offset) is a no-op.
 */
export function Commit(batch: pipeline$0.CommitBatch): $CancellablePromise<void> {
    return $Call.ByID(2833242122, batch);
}

/**
 * FeedItemCounts returns per-feed total/unread counts for every feed in a
 * flow, for the sidebar's rail badges.
 */
export function FeedItemCounts(flowID: string): $CancellablePromise<pipeline$0.FeedCount[] | null> {
    return $Call.ByID(460495308, flowID);
}

/**
 * FeedItems returns the persisted items for a feed, newest first.
 */
export function FeedItems(feedID: string): $CancellablePromise<pipeline$0.FeedItem[] | null> {
    return $Call.ByID(2832766353, feedID);
}

/**
 * InvokeAction records the user's explicit confirmation for actionID against
 * item and executes it. It accepts only actions that apply to the item's kind;
 * executable configuration is always re-resolved from ActionStore.
 */
export function InvokeAction(actionID: string, item: feed$0.Item): $CancellablePromise<void> {
    return $Call.ByID(204589393, actionID, item);
}

/**
 * MarkFeedItemRead clears the unread flag on one feed item.
 */
export function MarkFeedItemRead(feedID: string, itemID: string): $CancellablePromise<void> {
    return $Call.ByID(3950941725, feedID, itemID);
}

/**
 * NodeRuns returns up to limit of a flow's most recent node_run rows,
 * newest first, for the flows canvas's live per-node status and RECENT
 * activity list.
 */
export function NodeRuns(flowID: string, limit: number): $CancellablePromise<pipeline$0.NodeRunRecord[] | null> {
    return $Call.ByID(2130853077, flowID, limit);
}

/**
 * ReadFrom returns up to limit event_log rows after consumer's persisted
 * offset, in ascending order. The frontend never supplies an offset: the
 * SQLite checkpoint is the source of truth across runtime restarts.
 */
export function ReadFrom(consumer: string, limit: number): $CancellablePromise<pipelinedb$0.Msg[] | null> {
    return $Call.ByID(2706344123, consumer, limit);
}
