// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package session

import (
	"fmt"
	"strings"
)

const (
	// StateActive is a State of type active.
	StateActive State = "active"
	// StateRecycled is a State of type recycled.
	StateRecycled State = "recycled"
	// StateCorrupted is a State of type corrupted.
	StateCorrupted State = "corrupted"
)

var ErrInvalidState = fmt.Errorf("not a valid State, try [%s]", strings.Join(_StateNames, ", "))

var _StateNames = []string{
	string(StateActive),
	string(StateRecycled),
	string(StateCorrupted),
}

// StateNames returns a list of possible string values of State.
func StateNames() []string {
	tmp := make([]string, len(_StateNames))
	copy(tmp, _StateNames)
	return tmp
}

// String implements the Stringer interface.
func (x State) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x State) IsValid() bool {
	_, err := ParseState(string(x))
	return err == nil
}

var _StateValue = map[string]State{
	"active":    StateActive,
	"recycled":  StateRecycled,
	"corrupted": StateCorrupted,
}

// ParseState attempts to convert a string to a State.
func ParseState(name string) (State, error) {
	if x, ok := _StateValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _StateValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return State(""), fmt.Errorf("%s is %w", name, ErrInvalidState)
}

// MarshalText implements the text marshaller method.
func (x State) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *State) UnmarshalText(text []byte) error {
	tmp, err := ParseState(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *State) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
