// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package tmuxexec

import (
	"fmt"
	"strings"
)

const (
	// LaunchPhaseAllocating is a LaunchPhase of type allocating.
	LaunchPhaseAllocating LaunchPhase = "allocating"
	// LaunchPhaseLaunching is a LaunchPhase of type launching.
	LaunchPhaseLaunching LaunchPhase = "launching"
	// LaunchPhaseObserving is a LaunchPhase of type observing.
	LaunchPhaseObserving LaunchPhase = "observing"
	// LaunchPhaseFinalizing is a LaunchPhase of type finalizing.
	LaunchPhaseFinalizing LaunchPhase = "finalizing"
	// LaunchPhaseCommitted is a LaunchPhase of type committed.
	LaunchPhaseCommitted LaunchPhase = "committed"
	// LaunchPhaseRollingBack is a LaunchPhase of type rolling_back.
	LaunchPhaseRollingBack LaunchPhase = "rolling_back"
	// LaunchPhaseFailed is a LaunchPhase of type failed.
	LaunchPhaseFailed LaunchPhase = "failed"
	// LaunchPhaseCleanupIncomplete is a LaunchPhase of type cleanup_incomplete.
	LaunchPhaseCleanupIncomplete LaunchPhase = "cleanup_incomplete"
)

var ErrInvalidLaunchPhase = fmt.Errorf("not a valid LaunchPhase, try [%s]", strings.Join(_LaunchPhaseNames, ", "))

var _LaunchPhaseNames = []string{
	string(LaunchPhaseAllocating),
	string(LaunchPhaseLaunching),
	string(LaunchPhaseObserving),
	string(LaunchPhaseFinalizing),
	string(LaunchPhaseCommitted),
	string(LaunchPhaseRollingBack),
	string(LaunchPhaseFailed),
	string(LaunchPhaseCleanupIncomplete),
}

// LaunchPhaseNames returns a list of possible string values of LaunchPhase.
func LaunchPhaseNames() []string {
	tmp := make([]string, len(_LaunchPhaseNames))
	copy(tmp, _LaunchPhaseNames)
	return tmp
}

// String implements the Stringer interface.
func (x LaunchPhase) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x LaunchPhase) IsValid() bool {
	_, err := ParseLaunchPhase(string(x))
	return err == nil
}

var _LaunchPhaseValue = map[string]LaunchPhase{
	"allocating":         LaunchPhaseAllocating,
	"launching":          LaunchPhaseLaunching,
	"observing":          LaunchPhaseObserving,
	"finalizing":         LaunchPhaseFinalizing,
	"committed":          LaunchPhaseCommitted,
	"rolling_back":       LaunchPhaseRollingBack,
	"failed":             LaunchPhaseFailed,
	"cleanup_incomplete": LaunchPhaseCleanupIncomplete,
}

// ParseLaunchPhase attempts to convert a string to a LaunchPhase.
func ParseLaunchPhase(name string) (LaunchPhase, error) {
	if x, ok := _LaunchPhaseValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _LaunchPhaseValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return LaunchPhase(""), fmt.Errorf("%s is %w", name, ErrInvalidLaunchPhase)
}

// MarshalText implements the text marshaller method.
func (x LaunchPhase) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *LaunchPhase) UnmarshalText(text []byte) error {
	tmp, err := ParseLaunchPhase(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *LaunchPhase) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}

const (
	// PaneLaunchStateAllocated is a PaneLaunchState of type allocated.
	PaneLaunchStateAllocated PaneLaunchState = "allocated"
	// PaneLaunchStateSpawned is a PaneLaunchState of type spawned.
	PaneLaunchStateSpawned PaneLaunchState = "spawned"
	// PaneLaunchStateRunning is a PaneLaunchState of type running.
	PaneLaunchStateRunning PaneLaunchState = "running"
	// PaneLaunchStateCompleted is a PaneLaunchState of type completed.
	PaneLaunchStateCompleted PaneLaunchState = "completed"
	// PaneLaunchStateExitPending is a PaneLaunchState of type exit_pending.
	PaneLaunchStateExitPending PaneLaunchState = "exit_pending"
	// PaneLaunchStateFailed is a PaneLaunchState of type failed.
	PaneLaunchStateFailed PaneLaunchState = "failed"
	// PaneLaunchStateLost is a PaneLaunchState of type lost.
	PaneLaunchStateLost PaneLaunchState = "lost"
)

var ErrInvalidPaneLaunchState = fmt.Errorf("not a valid PaneLaunchState, try [%s]", strings.Join(_PaneLaunchStateNames, ", "))

var _PaneLaunchStateNames = []string{
	string(PaneLaunchStateAllocated),
	string(PaneLaunchStateSpawned),
	string(PaneLaunchStateRunning),
	string(PaneLaunchStateCompleted),
	string(PaneLaunchStateExitPending),
	string(PaneLaunchStateFailed),
	string(PaneLaunchStateLost),
}

// PaneLaunchStateNames returns a list of possible string values of PaneLaunchState.
func PaneLaunchStateNames() []string {
	tmp := make([]string, len(_PaneLaunchStateNames))
	copy(tmp, _PaneLaunchStateNames)
	return tmp
}

// String implements the Stringer interface.
func (x PaneLaunchState) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x PaneLaunchState) IsValid() bool {
	_, err := ParsePaneLaunchState(string(x))
	return err == nil
}

var _PaneLaunchStateValue = map[string]PaneLaunchState{
	"allocated":    PaneLaunchStateAllocated,
	"spawned":      PaneLaunchStateSpawned,
	"running":      PaneLaunchStateRunning,
	"completed":    PaneLaunchStateCompleted,
	"exit_pending": PaneLaunchStateExitPending,
	"failed":       PaneLaunchStateFailed,
	"lost":         PaneLaunchStateLost,
}

// ParsePaneLaunchState attempts to convert a string to a PaneLaunchState.
func ParsePaneLaunchState(name string) (PaneLaunchState, error) {
	if x, ok := _PaneLaunchStateValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _PaneLaunchStateValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return PaneLaunchState(""), fmt.Errorf("%s is %w", name, ErrInvalidPaneLaunchState)
}

// MarshalText implements the text marshaller method.
func (x PaneLaunchState) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *PaneLaunchState) UnmarshalText(text []byte) error {
	tmp, err := ParsePaneLaunchState(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *PaneLaunchState) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
