// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Flow is one parsed and validated flows/*.yaml document. Besides being the
 * decode target for LoadFlow, it is the wire shape GetFlow/SaveFlow expose
 * to the desktop frontend's graph editor over Wails — hence the json tags
 * alongside the (unused-by-Flow-itself, since flowFile is the YAML decode
 * target) documentation of the on-disk names.
 */
export interface Flow {
    /**
     * ID is the filename stem (no extension), never a value read from the
     * file itself.
     */
    "id": string;
    "name": string;
    "enabled": boolean;
    "nodes": Node[] | null;
    "wires": Wire[] | null;
}

/**
 * Layout is the machine-written, non-authoritative sibling of a flow — and
 * the on-disk shape of a <id>.ui.yaml file: node canvas positions only,
 * keyed by node id. It is never consulted by LoadFlow/validation and never
 * blocks a flow from loading — a missing or broken .ui.yaml just means the
 * editor lays out nodes fresh (see LoadUI).
 */
export interface Layout {
    "nodes": { [_ in string]?: NodePosition } | null;
}

/**
 * Node is one node in a flow's graph: the common envelope fields (id, type,
 * name, disabled) plus a per-type Config decoded via the registry. The json
 * tags document the wire shape produced by MarshalJSON/UnmarshalJSON (see
 * node_json.go) — Node's own (Un)MarshalJSON/(Un)MarshalYAML methods bypass
 * normal struct-tag reflection, so these tags are documentation, not decode
 * wiring.
 */
export type Node = any;

/**
 * NodePosition is one node's canvas coordinates in a flow's sibling
 * <id>.ui.yaml layout file.
 */
export interface NodePosition {
    "x": number;
    "y": number;
}

/**
 * Wire is a directed edge from one node's output port to another node's
 * (sole) input. Out defaults to 0 when omitted in YAML.
 */
export interface Wire {
    "from": string;
    "out"?: number;
    "to": string;
}
