// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: action_run_log.sql

package queries

import (
	"context"
	"database/sql"
)

const actionRunLogIDFromEnd = `-- name: ActionRunLogIDFromEnd :one
SELECT id FROM action_run_log
WHERE command_id = ?
ORDER BY id DESC
LIMIT 1 OFFSET ?
`

type ActionRunLogIDFromEndParams struct {
	CommandID int64 `json:"command_id"`
	Offset    int64 `json:"offset"`
}

// The id of the line `offset` lines before the newest, for a tail read.
func (q *Queries) ActionRunLogIDFromEnd(ctx context.Context, arg ActionRunLogIDFromEndParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, actionRunLogIDFromEnd, arg.CommandID, arg.Offset)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getActionRun = `-- name: GetActionRun :one
SELECT
    oc.id, oc.action_id, oc.key, oc.status, oc.attempts, oc.dispatch_lane, oc.is_rerun,
    oc.created_at, oc.claimed_at, oc.finished_at, oc.last_error,
    oc.profile_id, oc.source_kind, oc.source_scope, oc.external_id,
    CAST(COALESCE((SELECT j.label FROM job j WHERE j.command_id = oc.id ORDER BY j.id DESC LIMIT 1), '') AS TEXT) AS label,
    CAST(COALESCE(i.id, 0) AS INTEGER) AS item_id,
    CAST(COALESCE(i.title, '') AS TEXT) AS item_title
FROM output_command oc
LEFT JOIN inbox_item i
    ON oc.external_id <> ''
   AND i.profile_id = oc.profile_id AND i.source_kind = oc.source_kind
   AND i.source_scope = oc.source_scope AND i.external_id = oc.external_id
WHERE oc.id = ?
`

type GetActionRunRow struct {
	ID           int64          `json:"id"`
	ActionID     string         `json:"action_id"`
	Key          string         `json:"key"`
	Status       string         `json:"status"`
	Attempts     int64          `json:"attempts"`
	DispatchLane string         `json:"dispatch_lane"`
	IsRerun      int64          `json:"is_rerun"`
	CreatedAt    int64          `json:"created_at"`
	ClaimedAt    int64          `json:"claimed_at"`
	FinishedAt   int64          `json:"finished_at"`
	LastError    sql.NullString `json:"last_error"`
	ProfileID    string         `json:"profile_id"`
	SourceKind   string         `json:"source_kind"`
	SourceScope  string         `json:"source_scope"`
	ExternalID   string         `json:"external_id"`
	Label        string         `json:"label"`
	ItemID       int64          `json:"item_id"`
	ItemTitle    string         `json:"item_title"`
}

func (q *Queries) GetActionRun(ctx context.Context, id int64) (GetActionRunRow, error) {
	row := q.db.QueryRowContext(ctx, getActionRun, id)
	var i GetActionRunRow
	err := row.Scan(
		&i.ID,
		&i.ActionID,
		&i.Key,
		&i.Status,
		&i.Attempts,
		&i.DispatchLane,
		&i.IsRerun,
		&i.CreatedAt,
		&i.ClaimedAt,
		&i.FinishedAt,
		&i.LastError,
		&i.ProfileID,
		&i.SourceKind,
		&i.SourceScope,
		&i.ExternalID,
		&i.Label,
		&i.ItemID,
		&i.ItemTitle,
	)
	return i, err
}

const insertActionRunLogLine = `-- name: InsertActionRunLogLine :exec
INSERT INTO action_run_log (command_id, attempt, stream, text, created_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertActionRunLogLineParams struct {
	CommandID int64  `json:"command_id"`
	Attempt   int64  `json:"attempt"`
	Stream    string `json:"stream"`
	Text      string `json:"text"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) InsertActionRunLogLine(ctx context.Context, arg InsertActionRunLogLineParams) error {
	_, err := q.db.ExecContext(ctx, insertActionRunLogLine,
		arg.CommandID,
		arg.Attempt,
		arg.Stream,
		arg.Text,
		arg.CreatedAt,
	)
	return err
}

const listActionRunLogAfter = `-- name: ListActionRunLogAfter :many
SELECT id, command_id, attempt, stream, text, created_at FROM action_run_log
WHERE command_id = ? AND id > ?
ORDER BY id ASC
LIMIT ?
`

type ListActionRunLogAfterParams struct {
	CommandID int64 `json:"command_id"`
	ID        int64 `json:"id"`
	Limit     int64 `json:"limit"`
}

func (q *Queries) ListActionRunLogAfter(ctx context.Context, arg ListActionRunLogAfterParams) ([]ActionRunLog, error) {
	rows, err := q.db.QueryContext(ctx, listActionRunLogAfter, arg.CommandID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActionRunLog{}
	for rows.Next() {
		var i ActionRunLog
		if err := rows.Scan(
			&i.ID,
			&i.CommandID,
			&i.Attempt,
			&i.Stream,
			&i.Text,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActionRuns = `-- name: ListActionRuns :many
SELECT
    oc.id, oc.action_id, oc.key, oc.status, oc.attempts, oc.dispatch_lane, oc.is_rerun,
    oc.created_at, oc.claimed_at, oc.finished_at, oc.last_error,
    oc.profile_id, oc.source_kind, oc.source_scope, oc.external_id,
    CAST(COALESCE((SELECT j.label FROM job j WHERE j.command_id = oc.id ORDER BY j.id DESC LIMIT 1), '') AS TEXT) AS label,
    CAST(COALESCE(i.id, 0) AS INTEGER) AS item_id,
    CAST(COALESCE(i.title, '') AS TEXT) AS item_title
FROM output_command oc
LEFT JOIN inbox_item i
    ON oc.external_id <> ''
   AND i.profile_id = oc.profile_id AND i.source_kind = oc.source_kind
   AND i.source_scope = oc.source_scope AND i.external_id = oc.external_id
WHERE oc.id < ?1 AND instr(oc.action_id, ':') = 0
ORDER BY oc.id DESC
LIMIT ?2
`

type ListActionRunsParams struct {
	BeforeID int64 `json:"before_id"`
	RowLimit int64 `json:"row_limit"`
}

type ListActionRunsRow struct {
	ID           int64          `json:"id"`
	ActionID     string         `json:"action_id"`
	Key          string         `json:"key"`
	Status       string         `json:"status"`
	Attempts     int64          `json:"attempts"`
	DispatchLane string         `json:"dispatch_lane"`
	IsRerun      int64          `json:"is_rerun"`
	CreatedAt    int64          `json:"created_at"`
	ClaimedAt    int64          `json:"claimed_at"`
	FinishedAt   int64          `json:"finished_at"`
	LastError    sql.NullString `json:"last_error"`
	ProfileID    string         `json:"profile_id"`
	SourceKind   string         `json:"source_kind"`
	SourceScope  string         `json:"source_scope"`
	ExternalID   string         `json:"external_id"`
	Label        string         `json:"label"`
	ItemID       int64          `json:"item_id"`
	ItemTitle    string         `json:"item_title"`
}

// Only actions.yml actions: an authored id is a slug, and the synthetic ids of
// notify and launch nodes are the only ones that contain a colon.
func (q *Queries) ListActionRuns(ctx context.Context, arg ListActionRunsParams) ([]ListActionRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listActionRuns, arg.BeforeID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActionRunsRow{}
	for rows.Next() {
		var i ListActionRunsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActionID,
			&i.Key,
			&i.Status,
			&i.Attempts,
			&i.DispatchLane,
			&i.IsRerun,
			&i.CreatedAt,
			&i.ClaimedAt,
			&i.FinishedAt,
			&i.LastError,
			&i.ProfileID,
			&i.SourceKind,
			&i.SourceScope,
			&i.ExternalID,
			&i.Label,
			&i.ItemID,
			&i.ItemTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneActionRunLogs = `-- name: PruneActionRunLogs :exec
DELETE FROM action_run_log
WHERE command_id NOT IN (
    SELECT command_id FROM (
        SELECT DISTINCT l.command_id FROM action_run_log l
        ORDER BY l.command_id DESC
        LIMIT ?
    )
)
AND command_id NOT IN (SELECT id FROM output_command WHERE status IN ('pending', 'running'))
`

// Keeps the logs of the newest commands that have any, and of every command
// that can still run.
func (q *Queries) PruneActionRunLogs(ctx context.Context, limit int64) error {
	_, err := q.db.ExecContext(ctx, pruneActionRunLogs, limit)
	return err
}
