// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: item_chat.sql

package queries

import (
	"context"
)

const deleteItemChatsByProfile = `-- name: DeleteItemChatsByProfile :exec
DELETE FROM item_chat WHERE profile_id = ?
`

func (q *Queries) DeleteItemChatsByProfile(ctx context.Context, profileID string) error {
	_, err := q.db.ExecContext(ctx, deleteItemChatsByProfile, profileID)
	return err
}

const deleteUnscopedItemChats = `-- name: DeleteUnscopedItemChats :exec
DELETE FROM item_chat
WHERE profile_id = ?1
  AND source_kind = ?2
  AND source_scope = ''
  AND external_id = ?3
`

type DeleteUnscopedItemChatsParams struct {
	ProfileID  string `json:"profile_id"`
	SourceKind string `json:"source_kind"`
	ExternalID string `json:"external_id"`
}

func (q *Queries) DeleteUnscopedItemChats(ctx context.Context, arg DeleteUnscopedItemChatsParams) error {
	_, err := q.db.ExecContext(ctx, deleteUnscopedItemChats, arg.ProfileID, arg.SourceKind, arg.ExternalID)
	return err
}

const linkItemChat = `-- name: LinkItemChat :exec
INSERT INTO item_chat (chat_id, profile_id, source_kind, source_scope, external_id, created_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (chat_id, profile_id, source_kind, source_scope, external_id) DO NOTHING
`

type LinkItemChatParams struct {
	ChatID      int64  `json:"chat_id"`
	ProfileID   string `json:"profile_id"`
	SourceKind  string `json:"source_kind"`
	SourceScope string `json:"source_scope"`
	ExternalID  string `json:"external_id"`
	CreatedAt   int64  `json:"created_at"`
}

func (q *Queries) LinkItemChat(ctx context.Context, arg LinkItemChatParams) error {
	_, err := q.db.ExecContext(ctx, linkItemChat,
		arg.ChatID,
		arg.ProfileID,
		arg.SourceKind,
		arg.SourceScope,
		arg.ExternalID,
		arg.CreatedAt,
	)
	return err
}

const listItemChats = `-- name: ListItemChats :many
SELECT item_chat.chat_id, agent_workspace_session.workspace, agent_workspace_session.name, item_chat.created_at
FROM item_chat
JOIN agent_workspace_session ON agent_workspace_session.id = item_chat.chat_id
WHERE item_chat.profile_id = ? AND item_chat.source_kind = ? AND item_chat.source_scope = ? AND item_chat.external_id = ?
ORDER BY item_chat.created_at DESC, item_chat.chat_id DESC
`

type ListItemChatsParams struct {
	ProfileID   string `json:"profile_id"`
	SourceKind  string `json:"source_kind"`
	SourceScope string `json:"source_scope"`
	ExternalID  string `json:"external_id"`
}

type ListItemChatsRow struct {
	ChatID    int64  `json:"chat_id"`
	Workspace string `json:"workspace"`
	Name      string `json:"name"`
	CreatedAt int64  `json:"created_at"`
}

// Newest first, as ListItemSessions. The join reads the chat's current name,
// so a chat renamed after launch reports what it is now.
func (q *Queries) ListItemChats(ctx context.Context, arg ListItemChatsParams) ([]ListItemChatsRow, error) {
	rows, err := q.db.QueryContext(ctx, listItemChats,
		arg.ProfileID,
		arg.SourceKind,
		arg.SourceScope,
		arg.ExternalID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemChatsRow{}
	for rows.Next() {
		var i ListItemChatsRow
		if err := rows.Scan(
			&i.ChatID,
			&i.Workspace,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rescopeItemChats = `-- name: RescopeItemChats :exec
UPDATE OR IGNORE item_chat SET source_scope = ?1
WHERE profile_id = ?2
  AND source_kind = ?3
  AND source_scope = ''
  AND external_id = ?4
`

type RescopeItemChatsParams struct {
	SourceScope string `json:"source_scope"`
	ProfileID   string `json:"profile_id"`
	SourceKind  string `json:"source_kind"`
	ExternalID  string `json:"external_id"`
}

// The chat counterpart of RescopeItemSessions.
func (q *Queries) RescopeItemChats(ctx context.Context, arg RescopeItemChatsParams) error {
	_, err := q.db.ExecContext(ctx, rescopeItemChats,
		arg.SourceScope,
		arg.ProfileID,
		arg.SourceKind,
		arg.ExternalID,
	)
	return err
}
