// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orchestrator_token.sql

package queries

import (
	"context"
	"database/sql"
)

const createOrchestratorToken = `-- name: CreateOrchestratorToken :one
INSERT INTO orchestrator_token (name, token_hash, hint, created_at) VALUES (?, ?, ?, ?)
RETURNING id, name, token_hash, hint, created_at, last_used_at
`

type CreateOrchestratorTokenParams struct {
	Name      string `json:"name"`
	TokenHash string `json:"token_hash"`
	Hint      string `json:"hint"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) CreateOrchestratorToken(ctx context.Context, arg CreateOrchestratorTokenParams) (OrchestratorToken, error) {
	row := q.db.QueryRowContext(ctx, createOrchestratorToken,
		arg.Name,
		arg.TokenHash,
		arg.Hint,
		arg.CreatedAt,
	)
	var i OrchestratorToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.Hint,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const deleteOrchestratorToken = `-- name: DeleteOrchestratorToken :execrows
DELETE FROM orchestrator_token WHERE id = ?
`

func (q *Queries) DeleteOrchestratorToken(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteOrchestratorToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getOrchestratorTokenByHash = `-- name: GetOrchestratorTokenByHash :one
SELECT id, name, token_hash, hint, created_at, last_used_at FROM orchestrator_token WHERE token_hash = ?
`

func (q *Queries) GetOrchestratorTokenByHash(ctx context.Context, tokenHash string) (OrchestratorToken, error) {
	row := q.db.QueryRowContext(ctx, getOrchestratorTokenByHash, tokenHash)
	var i OrchestratorToken
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.Hint,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const listOrchestratorTokens = `-- name: ListOrchestratorTokens :many
SELECT id, name, token_hash, hint, created_at, last_used_at FROM orchestrator_token ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListOrchestratorTokens(ctx context.Context) ([]OrchestratorToken, error) {
	rows, err := q.db.QueryContext(ctx, listOrchestratorTokens)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrchestratorToken{}
	for rows.Next() {
		var i OrchestratorToken
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenHash,
			&i.Hint,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchOrchestratorToken = `-- name: TouchOrchestratorToken :exec
UPDATE orchestrator_token SET last_used_at = ? WHERE id = ?
`

type TouchOrchestratorTokenParams struct {
	LastUsedAt sql.NullInt64 `json:"last_used_at"`
	ID         int64         `json:"id"`
}

func (q *Queries) TouchOrchestratorToken(ctx context.Context, arg TouchOrchestratorTokenParams) error {
	_, err := q.db.ExecContext(ctx, touchOrchestratorToken, arg.LastUsedAt, arg.ID)
	return err
}
