// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: output_command.sql

package queries

import (
	"context"
	"database/sql"
)

const cancelClaimedOutputCommand = `-- name: CancelClaimedOutputCommand :execrows
UPDATE output_command
SET status = 'cancelled', claim_token = '', last_error = ?, stdout = ?, stderr = ?
WHERE id = ? AND status = 'running' AND claim_token = ?
`

type CancelClaimedOutputCommandParams struct {
	LastError  sql.NullString `json:"last_error"`
	Stdout     sql.NullString `json:"stdout"`
	Stderr     sql.NullString `json:"stderr"`
	ID         int64          `json:"id"`
	ClaimToken string         `json:"claim_token"`
}

func (q *Queries) CancelClaimedOutputCommand(ctx context.Context, arg CancelClaimedOutputCommandParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, cancelClaimedOutputCommand,
		arg.LastError,
		arg.Stdout,
		arg.Stderr,
		arg.ID,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const claimNextAutomaticOutputCommand = `-- name: ClaimNextAutomaticOutputCommand :one
UPDATE output_command
SET status = 'running', claim_token = ?1, claimed_at = ?2,
    attempts = attempts + 1
WHERE id = (
    SELECT oc.id FROM output_command oc
    WHERE oc.status = 'pending' AND oc.dispatch_lane = 'automatic'
      AND oc.id > ?3 AND oc.not_before <= ?2
    ORDER BY oc.id ASC
    LIMIT 1
)
AND status = 'pending'
RETURNING id, action_id, "key", payload, status, attempts, last_error, result_json, stdout, stderr, created_at, is_rerun, profile_id, source_kind, source_scope, external_id, dispatch_lane, claim_token, claimed_at, not_before
`

type ClaimNextAutomaticOutputCommandParams struct {
	ClaimToken string `json:"claim_token"`
	ClaimedAt  int64  `json:"claimed_at"`
	AfterID    int64  `json:"after_id"`
}

func (q *Queries) ClaimNextAutomaticOutputCommand(ctx context.Context, arg ClaimNextAutomaticOutputCommandParams) (OutputCommand, error) {
	row := q.db.QueryRowContext(ctx, claimNextAutomaticOutputCommand, arg.ClaimToken, arg.ClaimedAt, arg.AfterID)
	var i OutputCommand
	err := row.Scan(
		&i.ID,
		&i.ActionID,
		&i.Key,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.ResultJson,
		&i.Stdout,
		&i.Stderr,
		&i.CreatedAt,
		&i.IsRerun,
		&i.ProfileID,
		&i.SourceKind,
		&i.SourceScope,
		&i.ExternalID,
		&i.DispatchLane,
		&i.ClaimToken,
		&i.ClaimedAt,
		&i.NotBefore,
	)
	return i, err
}

const completeClaimedOutputCommand = `-- name: CompleteClaimedOutputCommand :execrows
UPDATE output_command
SET status = 'done', claim_token = '', last_error = NULL, result_json = ?, stdout = ?, stderr = ?
WHERE id = ? AND status = 'running' AND claim_token = ?
`

type CompleteClaimedOutputCommandParams struct {
	ResultJson sql.NullString `json:"result_json"`
	Stdout     sql.NullString `json:"stdout"`
	Stderr     sql.NullString `json:"stderr"`
	ID         int64          `json:"id"`
	ClaimToken string         `json:"claim_token"`
}

func (q *Queries) CompleteClaimedOutputCommand(ctx context.Context, arg CompleteClaimedOutputCommandParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeClaimedOutputCommand,
		arg.ResultJson,
		arg.Stdout,
		arg.Stderr,
		arg.ID,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const confirmOutputCommand = `-- name: ConfirmOutputCommand :one
INSERT INTO output_command (
    action_id, key, payload, status, attempts, created_at, dispatch_lane,
    claim_token, claimed_at, profile_id, source_kind, source_scope, external_id
)
VALUES (?, ?, ?, 'running', 1, ?, 'manual', ?, ?, ?, ?, ?, ?)
ON CONFLICT DO UPDATE SET
    status = 'running',
    attempts = output_command.attempts + 1,
    dispatch_lane = 'manual',
    claim_token = excluded.claim_token,
    claimed_at = excluded.claimed_at,
    profile_id = CASE WHEN output_command.profile_id <> '' AND output_command.external_id <> ''
                      THEN output_command.profile_id ELSE excluded.profile_id END,
    source_kind = CASE WHEN output_command.profile_id <> '' AND output_command.external_id <> ''
                       THEN output_command.source_kind ELSE excluded.source_kind END,
    source_scope = CASE WHEN output_command.profile_id <> '' AND output_command.external_id <> ''
                        THEN output_command.source_scope ELSE excluded.source_scope END,
    external_id = CASE WHEN output_command.profile_id <> '' AND output_command.external_id <> ''
                       THEN output_command.external_id ELSE excluded.external_id END
WHERE output_command.status = 'pending'
RETURNING id, action_id, "key", payload, status, attempts, last_error, result_json, stdout, stderr, created_at, is_rerun, profile_id, source_kind, source_scope, external_id, dispatch_lane, claim_token, claimed_at, not_before
`

type ConfirmOutputCommandParams struct {
	ActionID    string `json:"action_id"`
	Key         string `json:"key"`
	Payload     []byte `json:"payload"`
	CreatedAt   int64  `json:"created_at"`
	ClaimToken  string `json:"claim_token"`
	ClaimedAt   int64  `json:"claimed_at"`
	ProfileID   string `json:"profile_id"`
	SourceKind  string `json:"source_kind"`
	SourceScope string `json:"source_scope"`
	ExternalID  string `json:"external_id"`
}

func (q *Queries) ConfirmOutputCommand(ctx context.Context, arg ConfirmOutputCommandParams) (OutputCommand, error) {
	row := q.db.QueryRowContext(ctx, confirmOutputCommand,
		arg.ActionID,
		arg.Key,
		arg.Payload,
		arg.CreatedAt,
		arg.ClaimToken,
		arg.ClaimedAt,
		arg.ProfileID,
		arg.SourceKind,
		arg.SourceScope,
		arg.ExternalID,
	)
	var i OutputCommand
	err := row.Scan(
		&i.ID,
		&i.ActionID,
		&i.Key,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.ResultJson,
		&i.Stdout,
		&i.Stderr,
		&i.CreatedAt,
		&i.IsRerun,
		&i.ProfileID,
		&i.SourceKind,
		&i.SourceScope,
		&i.ExternalID,
		&i.DispatchLane,
		&i.ClaimToken,
		&i.ClaimedAt,
		&i.NotBefore,
	)
	return i, err
}

const countNonterminalCommandsForAction = `-- name: CountNonterminalCommandsForAction :one
SELECT COUNT(*) FROM output_command
WHERE action_id = ? AND status IN ('pending', 'running')
`

func (q *Queries) CountNonterminalCommandsForAction(ctx context.Context, actionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNonterminalCommandsForAction, actionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const enqueueOutputCommand = `-- name: EnqueueOutputCommand :exec
INSERT INTO output_command (action_id, key, payload, status, created_at, profile_id, source_kind, source_scope, external_id)
VALUES (?, ?, ?, 'pending', ?, ?, ?, ?, ?)
ON CONFLICT DO NOTHING
`

type EnqueueOutputCommandParams struct {
	ActionID    string `json:"action_id"`
	Key         string `json:"key"`
	Payload     []byte `json:"payload"`
	CreatedAt   int64  `json:"created_at"`
	ProfileID   string `json:"profile_id"`
	SourceKind  string `json:"source_kind"`
	SourceScope string `json:"source_scope"`
	ExternalID  string `json:"external_id"`
}

// Deduped on (action_id, key): a replayed commit batch enqueues the same
// action invocation at most once (see idx_output_command_action_key).
func (q *Queries) EnqueueOutputCommand(ctx context.Context, arg EnqueueOutputCommandParams) error {
	_, err := q.db.ExecContext(ctx, enqueueOutputCommand,
		arg.ActionID,
		arg.Key,
		arg.Payload,
		arg.CreatedAt,
		arg.ProfileID,
		arg.SourceKind,
		arg.SourceScope,
		arg.ExternalID,
	)
	return err
}

const failClaimedOutputCommand = `-- name: FailClaimedOutputCommand :execrows
UPDATE output_command
SET status = 'failed', claim_token = '', last_error = ?, stdout = ?, stderr = ?
WHERE id = ? AND status = 'running' AND claim_token = ?
`

type FailClaimedOutputCommandParams struct {
	LastError  sql.NullString `json:"last_error"`
	Stdout     sql.NullString `json:"stdout"`
	Stderr     sql.NullString `json:"stderr"`
	ID         int64          `json:"id"`
	ClaimToken string         `json:"claim_token"`
}

func (q *Queries) FailClaimedOutputCommand(ctx context.Context, arg FailClaimedOutputCommandParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, failClaimedOutputCommand,
		arg.LastError,
		arg.Stdout,
		arg.Stderr,
		arg.ID,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getLatestOutputCommandForAction = `-- name: GetLatestOutputCommandForAction :one
SELECT id, action_id, "key", payload, status, attempts, last_error, result_json, stdout, stderr, created_at, is_rerun, profile_id, source_kind, source_scope, external_id, dispatch_lane, claim_token, claimed_at, not_before FROM output_command
WHERE action_id = ? AND key = ?
ORDER BY id DESC
LIMIT 1
`

type GetLatestOutputCommandForActionParams struct {
	ActionID string `json:"action_id"`
	Key      string `json:"key"`
}

func (q *Queries) GetLatestOutputCommandForAction(ctx context.Context, arg GetLatestOutputCommandForActionParams) (OutputCommand, error) {
	row := q.db.QueryRowContext(ctx, getLatestOutputCommandForAction, arg.ActionID, arg.Key)
	var i OutputCommand
	err := row.Scan(
		&i.ID,
		&i.ActionID,
		&i.Key,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.ResultJson,
		&i.Stdout,
		&i.Stderr,
		&i.CreatedAt,
		&i.IsRerun,
		&i.ProfileID,
		&i.SourceKind,
		&i.SourceScope,
		&i.ExternalID,
		&i.DispatchLane,
		&i.ClaimToken,
		&i.ClaimedAt,
		&i.NotBefore,
	)
	return i, err
}

const getOutputCommand = `-- name: GetOutputCommand :one
SELECT id, action_id, "key", payload, status, attempts, last_error, result_json, stdout, stderr, created_at, is_rerun, profile_id, source_kind, source_scope, external_id, dispatch_lane, claim_token, claimed_at, not_before FROM output_command WHERE id = ?
`

func (q *Queries) GetOutputCommand(ctx context.Context, id int64) (OutputCommand, error) {
	row := q.db.QueryRowContext(ctx, getOutputCommand, id)
	var i OutputCommand
	err := row.Scan(
		&i.ID,
		&i.ActionID,
		&i.Key,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.ResultJson,
		&i.Stdout,
		&i.Stderr,
		&i.CreatedAt,
		&i.IsRerun,
		&i.ProfileID,
		&i.SourceKind,
		&i.SourceScope,
		&i.ExternalID,
		&i.DispatchLane,
		&i.ClaimToken,
		&i.ClaimedAt,
		&i.NotBefore,
	)
	return i, err
}

const listRunnableOutputCommandsAfter = `-- name: ListRunnableOutputCommandsAfter :many
SELECT id, action_id, "key", payload, status, attempts, last_error, result_json, stdout, stderr, created_at, is_rerun, profile_id, source_kind, source_scope, external_id, dispatch_lane, claim_token, claimed_at, not_before FROM output_command
WHERE status = 'pending' AND dispatch_lane = 'automatic' AND id > ?
ORDER BY id ASC
LIMIT ?
`

type ListRunnableOutputCommandsAfterParams struct {
	ID    int64 `json:"id"`
	Limit int64 `json:"limit"`
}

func (q *Queries) ListRunnableOutputCommandsAfter(ctx context.Context, arg ListRunnableOutputCommandsAfterParams) ([]OutputCommand, error) {
	rows, err := q.db.QueryContext(ctx, listRunnableOutputCommandsAfter, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutputCommand{}
	for rows.Next() {
		var i OutputCommand
		if err := rows.Scan(
			&i.ID,
			&i.ActionID,
			&i.Key,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.ResultJson,
			&i.Stdout,
			&i.Stderr,
			&i.CreatedAt,
			&i.IsRerun,
			&i.ProfileID,
			&i.SourceKind,
			&i.SourceScope,
			&i.ExternalID,
			&i.DispatchLane,
			&i.ClaimToken,
			&i.ClaimedAt,
			&i.NotBefore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneTerminalOutputCommands = `-- name: PruneTerminalOutputCommands :exec
DELETE FROM output_command
WHERE id IN (
    SELECT oc.id FROM output_command oc
    WHERE oc.status IN ('done', 'failed', 'cancelled')
      AND NOT (
          oc.action_id LIKE 'launch:%'
          AND EXISTS (
              SELECT 1 FROM inbox_item i
              WHERE i.profile_id = oc.profile_id
                AND i.source_kind = oc.source_kind
                AND i.external_id = oc.external_id
          )
      )
    ORDER BY oc.id DESC
    LIMIT -1 OFFSET ?
)
`

// Never remove active commands: only terminal history is bounded.
func (q *Queries) PruneTerminalOutputCommands(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, pruneTerminalOutputCommands, offset)
	return err
}

const requeueClaimedOutputCommand = `-- name: RequeueClaimedOutputCommand :execrows
UPDATE output_command
SET status = 'pending', claim_token = '', claimed_at = 0, not_before = ?,
    last_error = ?, stdout = ?, stderr = ?
WHERE id = ? AND status = 'running' AND claim_token = ?
`

type RequeueClaimedOutputCommandParams struct {
	NotBefore  int64          `json:"not_before"`
	LastError  sql.NullString `json:"last_error"`
	Stdout     sql.NullString `json:"stdout"`
	Stderr     sql.NullString `json:"stderr"`
	ID         int64          `json:"id"`
	ClaimToken string         `json:"claim_token"`
}

func (q *Queries) RequeueClaimedOutputCommand(ctx context.Context, arg RequeueClaimedOutputCommandParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, requeueClaimedOutputCommand,
		arg.NotBefore,
		arg.LastError,
		arg.Stdout,
		arg.Stderr,
		arg.ID,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const rerunOutputCommand = `-- name: RerunOutputCommand :one
INSERT INTO output_command (
    action_id, key, payload, status, attempts, created_at, is_rerun, dispatch_lane,
    claim_token, claimed_at, profile_id, source_kind, source_scope, external_id
)
SELECT ?1, ?2, ?3, 'running', 1, ?4, 1, 'manual',
       ?5, ?6, ?7, ?8,
       ?9, ?10
WHERE EXISTS (
    SELECT 1 FROM output_command
    WHERE action_id = ?1 AND key = ?2
      AND status IN ('done', 'failed', 'cancelled')
)
AND NOT EXISTS (
    SELECT 1 FROM output_command
    WHERE action_id = ?1 AND key = ?2
      AND status IN ('pending', 'running')
)
RETURNING id, action_id, "key", payload, status, attempts, last_error, result_json, stdout, stderr, created_at, is_rerun, profile_id, source_kind, source_scope, external_id, dispatch_lane, claim_token, claimed_at, not_before
`

type RerunOutputCommandParams struct {
	ActionID    string `json:"action_id"`
	Key         string `json:"key"`
	Payload     []byte `json:"payload"`
	CreatedAt   int64  `json:"created_at"`
	ClaimToken  string `json:"claim_token"`
	ClaimedAt   int64  `json:"claimed_at"`
	ProfileID   string `json:"profile_id"`
	SourceKind  string `json:"source_kind"`
	SourceScope string `json:"source_scope"`
	ExternalID  string `json:"external_id"`
}

func (q *Queries) RerunOutputCommand(ctx context.Context, arg RerunOutputCommandParams) (OutputCommand, error) {
	row := q.db.QueryRowContext(ctx, rerunOutputCommand,
		arg.ActionID,
		arg.Key,
		arg.Payload,
		arg.CreatedAt,
		arg.ClaimToken,
		arg.ClaimedAt,
		arg.ProfileID,
		arg.SourceKind,
		arg.SourceScope,
		arg.ExternalID,
	)
	var i OutputCommand
	err := row.Scan(
		&i.ID,
		&i.ActionID,
		&i.Key,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.ResultJson,
		&i.Stdout,
		&i.Stderr,
		&i.CreatedAt,
		&i.IsRerun,
		&i.ProfileID,
		&i.SourceKind,
		&i.SourceScope,
		&i.ExternalID,
		&i.DispatchLane,
		&i.ClaimToken,
		&i.ClaimedAt,
		&i.NotBefore,
	)
	return i, err
}
