package commands

// ConfigTemplateData is the data context for the annotated config template.
type ConfigTemplateData struct {
	Version      string
	Workspace    string
	AgentDefault string
	AgentFlags   []string
}

type resultStatus int //nolint:unused

const (
	statusDone    resultStatus = iota //nolint:unused
	statusSkipped                     //nolint:unused
	statusFailed                      //nolint:unused
)

type stepResult struct { //nolint:unused
	name    string
	status  resultStatus
	detail  string
	fixHint string
}

var knownAgents = []string{"claude", "opencode", "codex", "pi", "amp"} //nolint:unused

var agentFlagMap = map[string][]string{ //nolint:unused
	"claude":   {"--dangerously-skip-permissions"},
	"opencode": {"--agent", "free-permissions-runner"},
	"codex":    {"--full-auto"},
}

//nolint:unused
const configTemplate = `# hive configuration — generated by ` + "`hive init`" + `
# Full reference: https://hive.colonyops.io/configuration
version: {{ .Version }}

# Directories hive scans for git repositories (used in session picker).
workspaces:
  - {{ .Workspace }}  # add more paths here as needed

# Context directory settings
context:
  base_dir: "${XDG_DATA_HOME:-$HOME/.local/share}/hive/context"

# AI agent configuration
agents:
  default: {{ .AgentDefault }}
  {{ .AgentDefault }}:
    command: {{ .AgentDefault }}
    flags: {{ .AgentFlags | toStringSlice }}

# tmux integration — enables real-time status monitoring in the TUI
tmux:
  enabled: [tmux]
  poll_interval: 500ms
  # Pane content patterns that indicate an active AI agent window:
  preview_window_matcher: [claude, aider, codex, opencode, agent, pi, amp]

# Session lifecycle rules (last-match wins on remote URL pattern).
rules:
  - pattern: ""  # catch-all
    max_recycled: 3
    commands:
      - hive ctx init  # create .hive symlink in each new session
`
