package commands

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"

	"gopkg.in/yaml.v3"
)

// ConfigTemplateData is the data context for the annotated config template.
type ConfigTemplateData struct {
	Version      string
	Workspace    string
	AgentDefault string
	AgentFlags   []string
}

type resultStatus int //nolint:unused

const (
	statusDone    resultStatus = iota //nolint:unused
	statusSkipped                     //nolint:unused
	statusFailed                      //nolint:unused
)

type stepResult struct { //nolint:unused
	name    string
	status  resultStatus
	detail  string
	fixHint string
}

var knownAgents = []string{"claude", "opencode", "codex", "pi", "amp"} //nolint:unused

var agentFlagMap = map[string][]string{ //nolint:unused
	"claude":   {"--dangerously-skip-permissions"},
	"opencode": {"--agent", "free-permissions-runner"},
	"codex":    {"--full-auto"},
}

// detectInstalledAgents returns the subset of known agent names found on PATH,
// preserving input order. Uses exec.LookPath.
//
//nolint:unused
func detectInstalledAgents(known []string) []string {
	result := []string{}
	for _, name := range known {
		if _, err := exec.LookPath(name); err == nil {
			result = append(result, name)
		}
	}
	return result
}

// detectShell inspects $SHELL and returns a short name and the rc file path.
// Returns ("unknown", "") when $SHELL is unset, empty, or unrecognised.
// The bash case performs a file existence check on ~/.bash_profile.
//
//nolint:unused
func detectShell() (shellName, rcFile string) {
	shell := os.Getenv("SHELL")
	if shell == "" {
		return "unknown", ""
	}

	home, err := os.UserHomeDir()
	if err != nil {
		return "unknown", ""
	}

	switch {
	case strings.HasSuffix(shell, "zsh"):
		return "zsh", filepath.Join(home, ".zshrc")
	case strings.HasSuffix(shell, "bash"):
		bashProfile := filepath.Join(home, ".bash_profile")
		if _, err := os.Stat(bashProfile); err == nil {
			return "bash", bashProfile
		}
		return "bash", filepath.Join(home, ".bashrc")
	case strings.HasSuffix(shell, "fish"):
		return "fish", filepath.Join(home, ".config", "fish", "config.fish")
	default:
		return "unknown", ""
	}
}

// aliasAlreadyPresent reports whether rcFile contains "alias hv" on any line.
// Returns (false, nil) if the file does not exist.
//
//nolint:unused
func aliasAlreadyPresent(rcFile, aliasName string) (bool, error) {
	data, err := os.ReadFile(rcFile)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}

	lines := strings.Split(string(data), "\n")
	needle := "alias " + aliasName
	for _, line := range lines {
		if strings.Contains(line, needle) {
			return true, nil
		}
	}
	return false, nil
}

// appendAlias appends the hv alias line to rcFile.
// Fish uses `alias hv '...'`; all other shells use `alias hv='...'`.
//
//nolint:unused
func appendAlias(rcFile, shellName string) error {
	var line string
	if shellName == "fish" {
		line = "\nalias hv 'tmux new-session -As hive hive'\n"
	} else {
		line = "\nalias hv='tmux new-session -As hive hive'\n"
	}

	f, err := os.OpenFile(rcFile, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0o644)
	if err != nil {
		return err
	}

	_, err = f.WriteString(line)
	if closeErr := f.Close(); closeErr != nil && err == nil {
		err = closeErr
	}
	return err
}

// defaultConfigPath returns $XDG_CONFIG_HOME/hive/config.yaml.
// This is the write-side counterpart to DefaultConfigPath in flags.go which probes for existing files.
//
//nolint:unused
func defaultConfigPath() string {
	return filepath.Join(defaultConfigDir(), "config.yaml")
}

// toStringSlice serialises a []string as a YAML inline sequence using yaml.v3.
// Example: []string{"--foo"} → `["--foo"]`, nil/empty → `[]`.
//
//nolint:unused
func toStringSlice(ss []string) string {
	if len(ss) == 0 {
		return "[]"
	}
	node := &yaml.Node{
		Kind:  yaml.SequenceNode,
		Style: yaml.FlowStyle,
	}
	for _, s := range ss {
		node.Content = append(node.Content, &yaml.Node{
			Kind:  yaml.ScalarNode,
			Value: s,
		})
	}
	out, err := yaml.Marshal(node)
	if err != nil {
		return "[]"
	}
	return strings.TrimRight(string(out), "\n")
}

// renderConfigTemplate executes configTemplate with data and returns the rendered string.
// Registers toStringSlice as a template func internally.
//
//nolint:unused
func renderConfigTemplate(data ConfigTemplateData) (string, error) {
	funcMap := template.FuncMap{
		"toStringSlice": toStringSlice,
	}
	tmpl, err := template.New("config").Funcs(funcMap).Parse(configTemplate)
	if err != nil {
		return "", err
	}
	var sb strings.Builder
	if err := tmpl.Execute(&sb, data); err != nil {
		return "", err
	}
	return sb.String(), nil
}

//nolint:unused
const configTemplate = `# hive configuration — generated by ` + "`hive init`" + `
# Full reference: https://hive.colonyops.io/configuration
version: {{ .Version }}

# Directories hive scans for git repositories (used in session picker).
workspaces:
  - {{ .Workspace }}  # add more paths here as needed

# Context directory settings
context:
  base_dir: "${XDG_DATA_HOME:-$HOME/.local/share}/hive/context"

# AI agent configuration
agents:
  default: {{ .AgentDefault }}
  {{ .AgentDefault }}:
    command: {{ .AgentDefault }}
    flags: {{ .AgentFlags | toStringSlice }}

# tmux integration — enables real-time status monitoring in the TUI
tmux:
  enabled: [tmux]
  poll_interval: 500ms
  # Pane content patterns that indicate an active AI agent window:
  preview_window_matcher: [claude, aider, codex, opencode, agent, pi, amp]

# Session lifecycle rules (last-match wins on remote URL pattern).
rules:
  - pattern: ""  # catch-all
    max_recycled: 3
    commands:
      - hive ctx init  # create .hive symlink in each new session
`
