// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package hc

import (
	"fmt"
	"strings"
)

const (
	// ActivityTypeUpdate is a ActivityType of type update.
	ActivityTypeUpdate ActivityType = "update"
	// ActivityTypeComment is a ActivityType of type comment.
	ActivityTypeComment ActivityType = "comment"
	// ActivityTypeCheckpoint is a ActivityType of type checkpoint.
	ActivityTypeCheckpoint ActivityType = "checkpoint"
	// ActivityTypeStatusChange is a ActivityType of type status_change.
	ActivityTypeStatusChange ActivityType = "status_change"
)

var ErrInvalidActivityType = fmt.Errorf("not a valid ActivityType, try [%s]", strings.Join(_ActivityTypeNames, ", "))

var _ActivityTypeNames = []string{
	string(ActivityTypeUpdate),
	string(ActivityTypeComment),
	string(ActivityTypeCheckpoint),
	string(ActivityTypeStatusChange),
}

// ActivityTypeNames returns a list of possible string values of ActivityType.
func ActivityTypeNames() []string {
	tmp := make([]string, len(_ActivityTypeNames))
	copy(tmp, _ActivityTypeNames)
	return tmp
}

// String implements the Stringer interface.
func (x ActivityType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ActivityType) IsValid() bool {
	_, err := ParseActivityType(string(x))
	return err == nil
}

var _ActivityTypeValue = map[string]ActivityType{
	"update":        ActivityTypeUpdate,
	"comment":       ActivityTypeComment,
	"checkpoint":    ActivityTypeCheckpoint,
	"status_change": ActivityTypeStatusChange,
}

// ParseActivityType attempts to convert a string to a ActivityType.
func ParseActivityType(name string) (ActivityType, error) {
	if x, ok := _ActivityTypeValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _ActivityTypeValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return ActivityType(""), fmt.Errorf("%s is %w", name, ErrInvalidActivityType)
}

// MarshalText implements the text marshaller method.
func (x ActivityType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ActivityType) UnmarshalText(text []byte) error {
	tmp, err := ParseActivityType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *ActivityType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
