// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package hc

// CreateInput is one node of a bulk-create tree: the root epic or any item
// beneath it. The tree is walked breadth first and ids are generated on
// creation, so a node names nothing by id.
type CreateInput struct {
	// Local label other nodes name in blockers; not stored.
	Ref string `json:"ref,omitempty"`

	Title string `json:"title"`

	Desc string `json:"desc,omitempty"`

	Type ItemType `json:"type"`

	// Child items, created in the same call.
	Children []CreateInput `json:"children,omitempty"`

	// Refs of nodes in this tree that must complete before this one.
	Blockers []string `json:"blockers,omitempty"`
}
