// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Summary {
    "cliCommands": number;
    "hiveSessions": number;
    "terminalStarts": number;
}
