// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package tui

import (
	"fmt"
	"strings"
)

const (
	// UIStateNormal is a UIState of type normal.
	UIStateNormal UIState = "normal"
	// UIStateConfirming is a UIState of type confirming.
	UIStateConfirming UIState = "confirming"
	// UIStateLoading is a UIState of type loading.
	UIStateLoading UIState = "loading"
	// UIStateRunningRecycle is a UIState of type running_recycle.
	UIStateRunningRecycle UIState = "running_recycle"
	// UIStatePreviewingMessage is a UIState of type previewing_message.
	UIStatePreviewingMessage UIState = "previewing_message"
	// UIStateCreatingSession is a UIState of type creating_session.
	UIStateCreatingSession UIState = "creating_session"
	// UIStateCommandPalette is a UIState of type command_palette.
	UIStateCommandPalette UIState = "command_palette"
	// UIStateShowingHelp is a UIState of type showing_help.
	UIStateShowingHelp UIState = "showing_help"
	// UIStateShowingNotifications is a UIState of type showing_notifications.
	UIStateShowingNotifications UIState = "showing_notifications"
	// UIStateRenaming is a UIState of type renaming.
	UIStateRenaming UIState = "renaming"
	// UIStateFormInput is a UIState of type form_input.
	UIStateFormInput UIState = "form_input"
)

var ErrInvalidUIState = fmt.Errorf("not a valid UIState, try [%s]", strings.Join(_UIStateNames, ", "))

var _UIStateNames = []string{
	string(UIStateNormal),
	string(UIStateConfirming),
	string(UIStateLoading),
	string(UIStateRunningRecycle),
	string(UIStatePreviewingMessage),
	string(UIStateCreatingSession),
	string(UIStateCommandPalette),
	string(UIStateShowingHelp),
	string(UIStateShowingNotifications),
	string(UIStateRenaming),
	string(UIStateFormInput),
}

// UIStateNames returns a list of possible string values of UIState.
func UIStateNames() []string {
	tmp := make([]string, len(_UIStateNames))
	copy(tmp, _UIStateNames)
	return tmp
}

// String implements the Stringer interface.
func (x UIState) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x UIState) IsValid() bool {
	_, err := ParseUIState(string(x))
	return err == nil
}

var _UIStateValue = map[string]UIState{
	"normal":                UIStateNormal,
	"confirming":            UIStateConfirming,
	"loading":               UIStateLoading,
	"running_recycle":       UIStateRunningRecycle,
	"previewing_message":    UIStatePreviewingMessage,
	"creating_session":      UIStateCreatingSession,
	"command_palette":       UIStateCommandPalette,
	"showing_help":          UIStateShowingHelp,
	"showing_notifications": UIStateShowingNotifications,
	"renaming":              UIStateRenaming,
	"form_input":            UIStateFormInput,
}

// ParseUIState attempts to convert a string to a UIState.
func ParseUIState(name string) (UIState, error) {
	if x, ok := _UIStateValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _UIStateValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return UIState(""), fmt.Errorf("%s is %w", name, ErrInvalidUIState)
}

// MarshalText implements the text marshaller method.
func (x UIState) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *UIState) UnmarshalText(text []byte) error {
	tmp, err := ParseUIState(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *UIState) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
