// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package tui

import (
	"fmt"
	"strings"
)

const (
	// ViewTypeSessions is a ViewType of type sessions.
	ViewTypeSessions ViewType = "sessions"
	// ViewTypeMessages is a ViewType of type messages.
	ViewTypeMessages ViewType = "messages"
	// ViewTypeReview is a ViewType of type review.
	ViewTypeReview ViewType = "review"
)

var ErrInvalidViewType = fmt.Errorf("not a valid ViewType, try [%s]", strings.Join(_ViewTypeNames, ", "))

var _ViewTypeNames = []string{
	string(ViewTypeSessions),
	string(ViewTypeMessages),
	string(ViewTypeReview),
}

// ViewTypeNames returns a list of possible string values of ViewType.
func ViewTypeNames() []string {
	tmp := make([]string, len(_ViewTypeNames))
	copy(tmp, _ViewTypeNames)
	return tmp
}

// String implements the Stringer interface.
func (x ViewType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ViewType) IsValid() bool {
	_, err := ParseViewType(string(x))
	return err == nil
}

var _ViewTypeValue = map[string]ViewType{
	"sessions": ViewTypeSessions,
	"messages": ViewTypeMessages,
	"review":   ViewTypeReview,
}

// ParseViewType attempts to convert a string to a ViewType.
func ParseViewType(name string) (ViewType, error) {
	if x, ok := _ViewTypeValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _ViewTypeValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return ViewType(""), fmt.Errorf("%s is %w", name, ErrInvalidViewType)
}

// MarshalText implements the text marshaller method.
func (x ViewType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ViewType) UnmarshalText(text []byte) error {
	tmp, err := ParseViewType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *ViewType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
