// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pipelinedb$0 from "./pipelinedb/models.js";

/**
 * ActionInvocationInput contains only user-supplied action inputs. It never
 * carries executable configuration or message attribution.
 */
export interface ActionInvocationInput {
    "session"?: SessionInvocationInput | null;
}

export interface ActionRunView {
    "commandId": number;
    "status": string;
    "result"?: ExecutionOutcome | null;
    "error"?: string;
    "stdout"?: string;
    "stderr"?: string;
}

/**
 * Sink, Output, Discard, NodeRun, and CommitBatch are pipelinedb's commit
 * protocol structs, re-exported verbatim under package pipeline — the same
 * alias pattern as Msg above: pipelinedb owns the transactional
 * implementation (see pipelinedb/commit.go), while callers outside this
 * package (desktop/pipelineservice.go, the frontend graph runtime via Wails
 * bindings) speak in terms of this package's names.
 */
export type CommitBatch = pipelinedb$0.CommitBatch;

/**
 * ExecutionOutcome is a tagged-by-presence union. Exactly one branch is set
 * for successful side-effecting executors.
 */
export interface ExecutionOutcome {
    "session"?: SessionExecutionOutcome | null;
    "message"?: MessageExecutionOutcome | null;
}

/**
 * Sink, Output, Discard, NodeRun, and CommitBatch are pipelinedb's commit
 * protocol structs, re-exported verbatim under package pipeline — the same
 * alias pattern as Msg above: pipelinedb owns the transactional
 * implementation (see pipelinedb/commit.go), while callers outside this
 * package (desktop/pipelineservice.go, the frontend graph runtime via Wails
 * bindings) speak in terms of this package's names.
 *
 * FeedCount is a feed's total/unread item counts for the sidebar rail.
 */
export type FeedCount = pipelinedb$0.FeedCount;

/**
 * Sink, Output, Discard, NodeRun, and CommitBatch are pipelinedb's commit
 * protocol structs, re-exported verbatim under package pipeline — the same
 * alias pattern as Msg above: pipelinedb owns the transactional
 * implementation (see pipelinedb/commit.go), while callers outside this
 * package (desktop/pipelineservice.go, the frontend graph runtime via Wails
 * bindings) speak in terms of this package's names.
 *
 * FeedItem mirrors pipelinedb.FeedItemView, which is named "View" only
 * to avoid colliding with sqlc's generated raw feed_item row model
 * (also named FeedItem, in pipelinedb/models.go).
 */
export type FeedItem = pipelinedb$0.FeedItemView;

export interface MessageExecutionOutcome {
    "topic": string;
    "sender": string;
}

/**
 * Sink, Output, Discard, NodeRun, and CommitBatch are pipelinedb's commit
 * protocol structs, re-exported verbatim under package pipeline — the same
 * alias pattern as Msg above: pipelinedb owns the transactional
 * implementation (see pipelinedb/commit.go), while callers outside this
 * package (desktop/pipelineservice.go, the frontend graph runtime via Wails
 * bindings) speak in terms of this package's names.
 *
 * NodeRunRecord mirrors pipelinedb.NodeRunRecord, the read-side shape
 * returned by NodeRuns (see pipelinedb/node_run.go) — NodeRun's write
 * shape plus EndedAt.
 */
export type NodeRunRecord = pipelinedb$0.NodeRunRecord;

export interface SessionExecutionOutcome {
    "id": string;
    "name": string;
}

export interface SessionInvocationInput {
    "name": string;
    "repository": string;
    "agent"?: string;
}

/**
 * SessionLaunchOptions is the narrow DTO used by the session launch dialog.
 */
export interface SessionLaunchOptions {
    "repositories": SessionLaunchRepository[] | null;
    "defaultRepository": string;
    "agents": string[] | null;
    "defaultAgent": string;
}

/**
 * SessionLaunchRepository is the safe presentation of a repository available
 * to an interactive action. Local checkout paths stay backend-only.
 */
export interface SessionLaunchRepository {
    "name": string;
    "repository": string;
}
