// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pipelinedb$0 from "./pipelinedb/models.js";

/**
 * Sink, Output, Discard, NodeRun, and CommitBatch are pipelinedb's commit
 * protocol structs, re-exported verbatim under package pipeline — the same
 * alias pattern as Msg above: pipelinedb owns the transactional
 * implementation (see pipelinedb/commit.go), while callers outside this
 * package (desktop/pipelineservice.go, the frontend graph runtime via Wails
 * bindings) speak in terms of this package's names.
 */
export type CommitBatch = pipelinedb$0.CommitBatch;

/**
 * Sink, Output, Discard, NodeRun, and CommitBatch are pipelinedb's commit
 * protocol structs, re-exported verbatim under package pipeline — the same
 * alias pattern as Msg above: pipelinedb owns the transactional
 * implementation (see pipelinedb/commit.go), while callers outside this
 * package (desktop/pipelineservice.go, the frontend graph runtime via Wails
 * bindings) speak in terms of this package's names.
 *
 * FeedItem mirrors pipelinedb.FeedItemView, which is named "View" only
 * to avoid colliding with sqlc's generated raw feed_item row model
 * (also named FeedItem, in pipelinedb/models.go).
 */
export type FeedItem = pipelinedb$0.FeedItemView;

/**
 * Sink, Output, Discard, NodeRun, and CommitBatch are pipelinedb's commit
 * protocol structs, re-exported verbatim under package pipeline — the same
 * alias pattern as Msg above: pipelinedb owns the transactional
 * implementation (see pipelinedb/commit.go), while callers outside this
 * package (desktop/pipelineservice.go, the frontend graph runtime via Wails
 * bindings) speak in terms of this package's names.
 *
 * NodeRunRecord mirrors pipelinedb.NodeRunRecord, the read-side shape
 * returned by NodeRuns (see pipelinedb/node_run.go) — NodeRun's write
 * shape plus EndedAt.
 */
export type NodeRunRecord = pipelinedb$0.NodeRunRecord;
