// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package queries

type UsageEvent struct {
	EventID        string
	OccurredAtMs   int64
	RecordedAtMs   int64
	Name           string
	SchemaVersion  int64
	InstallationID string
	RunID          string
	Surface        string
	AppVersion     string
	ReleaseChannel string
	PropertiesJson string
}

type UsageMetadatum struct {
	ID             int64
	InstallationID string
	ClearCutoffNs  int64
}
