// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage.sql

package queries

import (
	"context"
)

const clearEvents = `-- name: ClearEvents :exec
DELETE FROM usage_event
`

func (q *Queries) ClearEvents(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearEvents)
	return err
}

const counts = `-- name: Counts :many
SELECT name, count(*) AS total FROM usage_event WHERE occurred_at_ms >= ? AND occurred_at_ms <= ? GROUP BY name
`

type CountsParams struct {
	OccurredAtMs   int64
	OccurredAtMs_2 int64
}

type CountsRow struct {
	Name  string
	Total int64
}

func (q *Queries) Counts(ctx context.Context, arg CountsParams) ([]CountsRow, error) {
	rows, err := q.db.QueryContext(ctx, counts, arg.OccurredAtMs, arg.OccurredAtMs_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountsRow{}
	for rows.Next() {
		var i CountsRow
		if err := rows.Scan(&i.Name, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const initializeMetadata = `-- name: InitializeMetadata :exec
INSERT INTO usage_metadata (id, installation_id) VALUES (1, ?) ON CONFLICT DO NOTHING
`

func (q *Queries) InitializeMetadata(ctx context.Context, installationID string) error {
	_, err := q.db.ExecContext(ctx, initializeMetadata, installationID)
	return err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO usage_event (event_id, occurred_at_ms, recorded_at_ms, name, schema_version, installation_id, run_id, surface, app_version, release_channel, properties_json)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT DO NOTHING
`

type InsertEventParams struct {
	EventID        string
	OccurredAtMs   int64
	RecordedAtMs   int64
	Name           string
	SchemaVersion  int64
	InstallationID string
	RunID          string
	Surface        string
	AppVersion     string
	ReleaseChannel string
	PropertiesJson string
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.EventID,
		arg.OccurredAtMs,
		arg.RecordedAtMs,
		arg.Name,
		arg.SchemaVersion,
		arg.InstallationID,
		arg.RunID,
		arg.Surface,
		arg.AppVersion,
		arg.ReleaseChannel,
		arg.PropertiesJson,
	)
	return err
}

const metadata = `-- name: Metadata :one
SELECT installation_id, clear_cutoff_ns FROM usage_metadata WHERE id = 1
`

type MetadataRow struct {
	InstallationID string
	ClearCutoffNs  int64
}

func (q *Queries) Metadata(ctx context.Context) (MetadataRow, error) {
	row := q.db.QueryRowContext(ctx, metadata)
	var i MetadataRow
	err := row.Scan(&i.InstallationID, &i.ClearCutoffNs)
	return i, err
}

const prune = `-- name: Prune :execrows
DELETE FROM usage_event WHERE event_id IN (SELECT old.event_id FROM usage_event AS old WHERE old.occurred_at_ms < ? LIMIT 500)
`

func (q *Queries) Prune(ctx context.Context, occurredAtMs int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, prune, occurredAtMs)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setClearCutoff = `-- name: SetClearCutoff :exec
UPDATE usage_metadata SET clear_cutoff_ns = max(clear_cutoff_ns, ?), installation_id = ? WHERE id = 1
`

type SetClearCutoffParams struct {
	MAX            interface{}
	InstallationID string
}

func (q *Queries) SetClearCutoff(ctx context.Context, arg SetClearCutoffParams) error {
	_, err := q.db.ExecContext(ctx, setClearCutoff, arg.MAX, arg.InstallationID)
	return err
}
