// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package command

import (
	"fmt"
	"strings"
)

const (
	// ActionTypeNone is a ActionType of type none.
	ActionTypeNone ActionType = "none"
	// ActionTypeRecycle is a ActionType of type recycle.
	ActionTypeRecycle ActionType = "recycle"
	// ActionTypeDelete is a ActionType of type delete.
	ActionTypeDelete ActionType = "delete"
	// ActionTypeShell is a ActionType of type shell.
	ActionTypeShell ActionType = "shell"
)

var ErrInvalidActionType = fmt.Errorf("not a valid ActionType, try [%s]", strings.Join(_ActionTypeNames, ", "))

var _ActionTypeNames = []string{
	string(ActionTypeNone),
	string(ActionTypeRecycle),
	string(ActionTypeDelete),
	string(ActionTypeShell),
}

// ActionTypeNames returns a list of possible string values of ActionType.
func ActionTypeNames() []string {
	tmp := make([]string, len(_ActionTypeNames))
	copy(tmp, _ActionTypeNames)
	return tmp
}

// String implements the Stringer interface.
func (x ActionType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x ActionType) IsValid() bool {
	_, err := ParseActionType(string(x))
	return err == nil
}

var _ActionTypeValue = map[string]ActionType{
	"none":    ActionTypeNone,
	"recycle": ActionTypeRecycle,
	"delete":  ActionTypeDelete,
	"shell":   ActionTypeShell,
}

// ParseActionType attempts to convert a string to a ActionType.
func ParseActionType(name string) (ActionType, error) {
	if x, ok := _ActionTypeValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _ActionTypeValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return ActionType(""), fmt.Errorf("%s is %w", name, ErrInvalidActionType)
}

// MarshalText implements the text marshaller method.
func (x ActionType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *ActionType) UnmarshalText(text []byte) error {
	tmp, err := ParseActionType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *ActionType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
