// Code generated by gobusgen; DO NOT EDIT.
package eventbus

import (
	"context"
	"sync"
)

// Event represents a typed event name.
type Event string

const (
	EventAgentStatusChanged Event = "agent.status-changed"
	EventConfigReloaded     Event = "config.reloaded"
	EventMessageReceived    Event = "message.received"
	EventSessionCorrupted   Event = "session.corrupted"
	EventSessionCreated     Event = "session.created"
	EventSessionDeleted     Event = "session.deleted"
	EventSessionRecycled    Event = "session.recycled"
	EventSessionRenamed     Event = "session.renamed"
	EventTuiStarted         Event = "tui.started"
	EventTuiStopped         Event = "tui.stopped"
)

// EventBus provides type-safe publish/subscribe for in-process events.
type EventBus struct {
	mu          sync.RWMutex
	subscribers map[Event][]any
	ch          chan envelope
}

type envelope struct {
	event   Event
	payload any
}

// New creates an EventBus with the given channel buffer size.
func New(size int) *EventBus {
	if size < 1 {
		size = 1
	}

	return &EventBus{
		subscribers: newSubscribersMap(),
		ch:          make(chan envelope, size),
	}
}

func newSubscribersMap() map[Event][]any {
	return map[Event][]any{
		EventAgentStatusChanged: {},
		EventConfigReloaded:     {},
		EventMessageReceived:    {},
		EventSessionCorrupted:   {},
		EventSessionCreated:     {},
		EventSessionDeleted:     {},
		EventSessionRecycled:    {},
		EventSessionRenamed:     {},
		EventTuiStarted:         {},
		EventTuiStopped:         {},
	}
}

// Start begins processing events. It blocks until ctx is cancelled.
func (bus *EventBus) Start(ctx context.Context) {
	for {
		select {
		case <-ctx.Done():
			return
		case env := <-bus.ch:
			bus.mu.RLock()
			subs := make([]any, len(bus.subscribers[env.event]))
			copy(subs, bus.subscribers[env.event])
			bus.mu.RUnlock()

			for _, sub := range subs {
				if fn, ok := sub.(func(any)); ok {
					fn(env.payload)
				}
			}
		}
	}
}

// PublishAgentStatusChanged publishes a agent.status-changed event.
func (bus *EventBus) PublishAgentStatusChanged(payload AgentStatusChangedPayload) {
	bus.ch <- envelope{event: EventAgentStatusChanged, payload: payload}
}

// SubscribeAgentStatusChanged registers a handler for agent.status-changed events.
func (bus *EventBus) SubscribeAgentStatusChanged(fn func(AgentStatusChangedPayload)) {
	bus.mu.Lock()
	defer bus.mu.Unlock()

	bus.subscribers[EventAgentStatusChanged] = append(bus.subscribers[EventAgentStatusChanged], func(v any) {
		payload, ok := v.(AgentStatusChangedPayload)
		if !ok {
			return
		}
		fn(payload)
	})
}

// PublishConfigReloaded publishes a config.reloaded event.
func (bus *EventBus) PublishConfigReloaded(payload ConfigReloadedPayload) {
	bus.ch <- envelope{event: EventConfigReloaded, payload: payload}
}

// SubscribeConfigReloaded registers a handler for config.reloaded events.
func (bus *EventBus) SubscribeConfigReloaded(fn func(ConfigReloadedPayload)) {
	bus.mu.Lock()
	defer bus.mu.Unlock()

	bus.subscribers[EventConfigReloaded] = append(bus.subscribers[EventConfigReloaded], func(v any) {
		payload, ok := v.(ConfigReloadedPayload)
		if !ok {
			return
		}
		fn(payload)
	})
}

// PublishMessageReceived publishes a message.received event.
func (bus *EventBus) PublishMessageReceived(payload MessageReceivedPayload) {
	bus.ch <- envelope{event: EventMessageReceived, payload: payload}
}

// SubscribeMessageReceived registers a handler for message.received events.
func (bus *EventBus) SubscribeMessageReceived(fn func(MessageReceivedPayload)) {
	bus.mu.Lock()
	defer bus.mu.Unlock()

	bus.subscribers[EventMessageReceived] = append(bus.subscribers[EventMessageReceived], func(v any) {
		payload, ok := v.(MessageReceivedPayload)
		if !ok {
			return
		}
		fn(payload)
	})
}

// PublishSessionCorrupted publishes a session.corrupted event.
func (bus *EventBus) PublishSessionCorrupted(payload SessionCorruptedPayload) {
	bus.ch <- envelope{event: EventSessionCorrupted, payload: payload}
}

// SubscribeSessionCorrupted registers a handler for session.corrupted events.
func (bus *EventBus) SubscribeSessionCorrupted(fn func(SessionCorruptedPayload)) {
	bus.mu.Lock()
	defer bus.mu.Unlock()

	bus.subscribers[EventSessionCorrupted] = append(bus.subscribers[EventSessionCorrupted], func(v any) {
		payload, ok := v.(SessionCorruptedPayload)
		if !ok {
			return
		}
		fn(payload)
	})
}

// PublishSessionCreated publishes a session.created event.
func (bus *EventBus) PublishSessionCreated(payload SessionCreatedPayload) {
	bus.ch <- envelope{event: EventSessionCreated, payload: payload}
}

// SubscribeSessionCreated registers a handler for session.created events.
func (bus *EventBus) SubscribeSessionCreated(fn func(SessionCreatedPayload)) {
	bus.mu.Lock()
	defer bus.mu.Unlock()

	bus.subscribers[EventSessionCreated] = append(bus.subscribers[EventSessionCreated], func(v any) {
		payload, ok := v.(SessionCreatedPayload)
		if !ok {
			return
		}
		fn(payload)
	})
}

// PublishSessionDeleted publishes a session.deleted event.
func (bus *EventBus) PublishSessionDeleted(payload SessionDeletedPayload) {
	bus.ch <- envelope{event: EventSessionDeleted, payload: payload}
}

// SubscribeSessionDeleted registers a handler for session.deleted events.
func (bus *EventBus) SubscribeSessionDeleted(fn func(SessionDeletedPayload)) {
	bus.mu.Lock()
	defer bus.mu.Unlock()

	bus.subscribers[EventSessionDeleted] = append(bus.subscribers[EventSessionDeleted], func(v any) {
		payload, ok := v.(SessionDeletedPayload)
		if !ok {
			return
		}
		fn(payload)
	})
}

// PublishSessionRecycled publishes a session.recycled event.
func (bus *EventBus) PublishSessionRecycled(payload SessionRecycledPayload) {
	bus.ch <- envelope{event: EventSessionRecycled, payload: payload}
}

// SubscribeSessionRecycled registers a handler for session.recycled events.
func (bus *EventBus) SubscribeSessionRecycled(fn func(SessionRecycledPayload)) {
	bus.mu.Lock()
	defer bus.mu.Unlock()

	bus.subscribers[EventSessionRecycled] = append(bus.subscribers[EventSessionRecycled], func(v any) {
		payload, ok := v.(SessionRecycledPayload)
		if !ok {
			return
		}
		fn(payload)
	})
}

// PublishSessionRenamed publishes a session.renamed event.
func (bus *EventBus) PublishSessionRenamed(payload SessionRenamedPayload) {
	bus.ch <- envelope{event: EventSessionRenamed, payload: payload}
}

// SubscribeSessionRenamed registers a handler for session.renamed events.
func (bus *EventBus) SubscribeSessionRenamed(fn func(SessionRenamedPayload)) {
	bus.mu.Lock()
	defer bus.mu.Unlock()

	bus.subscribers[EventSessionRenamed] = append(bus.subscribers[EventSessionRenamed], func(v any) {
		payload, ok := v.(SessionRenamedPayload)
		if !ok {
			return
		}
		fn(payload)
	})
}

// PublishTuiStarted publishes a tui.started event.
func (bus *EventBus) PublishTuiStarted(payload TUIStartedPayload) {
	bus.ch <- envelope{event: EventTuiStarted, payload: payload}
}

// SubscribeTuiStarted registers a handler for tui.started events.
func (bus *EventBus) SubscribeTuiStarted(fn func(TUIStartedPayload)) {
	bus.mu.Lock()
	defer bus.mu.Unlock()

	bus.subscribers[EventTuiStarted] = append(bus.subscribers[EventTuiStarted], func(v any) {
		payload, ok := v.(TUIStartedPayload)
		if !ok {
			return
		}
		fn(payload)
	})
}

// PublishTuiStopped publishes a tui.stopped event.
func (bus *EventBus) PublishTuiStopped(payload TUIStoppedPayload) {
	bus.ch <- envelope{event: EventTuiStopped, payload: payload}
}

// SubscribeTuiStopped registers a handler for tui.stopped events.
func (bus *EventBus) SubscribeTuiStopped(fn func(TUIStoppedPayload)) {
	bus.mu.Lock()
	defer bus.mu.Unlock()

	bus.subscribers[EventTuiStopped] = append(bus.subscribers[EventTuiStopped], func(v any) {
		payload, ok := v.(TUIStoppedPayload)
		if !ok {
			return
		}
		fn(payload)
	})
}

// Reference the source variable to suppress unused-variable lint.
var _ = Events
