// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Link is what is at the install path.
 */
export interface Link {
    "path": string;
    "exists": boolean;
    "appOwned": boolean;

    /**
     * Target is the symlink's destination, or "" for a regular file.
     */
    "target": string;
}
