// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ActionInvocationInput contains only user-supplied action inputs. It never
 * carries executable configuration or message attribution.
 */
export interface ActionInvocationInput {
    "session"?: SessionInvocationInput | null;

    /**
     * Inputs are the values collected for the action's declared inputs, keyed
     * by input name. They are validated against the catalog's declaration on
     * every invocation, so a name the action does not declare is refused.
     */
    "inputs"?: { [_ in string]?: string } | null;
    "rerun"?: boolean;
}

export interface ActionRunView {
    "commandId": number;
    "status": string;
    "result"?: ExecutionOutcome | null;
    "error"?: string;
    "stdout"?: string;
    "stderr"?: string;
    "confirmationRequired"?: boolean;
}

/**
 * ClipboardExecutionOutcome carries the text a clipboard action rendered. The
 * clipboard write itself is the desktop adapter's: the core produces the text
 * and the frontend copies it (see the detail-pane render path), so this is the
 * executor's whole result.
 */
export interface ClipboardExecutionOutcome {
    "text": string;
}

/**
 * CreateSessionRequest is a user-submitted New Session form. ItemIDs are the
 * inbox items the form was drafted from; the core resolves their identities
 * and never takes item refs from a client.
 */
export interface CreateSessionRequest {
    "repository"?: string;
    "workspace"?: string;
    "name": string;
    "prompt": string;
    "agent"?: string;
    "itemIds"?: number[] | null;
}

/**
 * ExecutionOutcome is a tagged-by-presence union. Exactly one branch is set
 * for successful side-effecting executors.
 */
export interface ExecutionOutcome {
    "session"?: SessionExecutionOutcome | null;
    "message"?: MessageExecutionOutcome | null;
    "clipboard"?: ClipboardExecutionOutcome | null;
}

export interface MessageExecutionOutcome {
    "topic": string;
    "sender": string;
}

/**
 * SessionCreateFailure is why one session creation attempt failed.
 */
export interface SessionCreateFailure {
    /**
     * Reason is the wrapped error, a chain like
     * "clone repository: git clone: exec git: exit status 1".
     */
    "reason": string;

    /**
     * Step is the last thing creation reported: "Cloning repository...",
     * "Executing rules...".
     */
    "step": string;

    /**
     * Output is the tail of the attempt's progress output, hook output included.
     */
    "output": string;

    /**
     * CloneStrategy is "full" or "worktree".
     */
    "cloneStrategy": string;

    /**
     * Destination is the checkout hive resolved for the attempt.
     */
    "destination": string;

    /**
     * LeftoverCheckout reports that Destination survived the failure, which is
     * what makes it a directory to go and delete. A refused clone names a
     * destination git already removed.
     */
    "leftoverCheckout": boolean;
    "at": string;
}

/**
 * SessionDraft is a New Session form the app prefills: from inbox items, or
 * from a creation attempt that failed and is being handed back. Agent and
 * ItemIDs are only meaningful for the second, which has to restore both
 * because the form they came from is gone.
 */
export interface SessionDraft {
    "repository"?: string;
    "workspace"?: string;
    "name": string;
    "prompt": string;
    "agent"?: string;
    "itemIds"?: number[] | null;

    /**
     * nil on a draft that is not a retry, which is also what "no attempt is
     * waiting" looks like to a caller.
     */
    "failure"?: SessionCreateFailure | null;
}

export interface SessionExecutionOutcome {
    "id": string;
    "name": string;

    /**
     * Slug names the tmux session; Path is the checkout a post hook runs in.
     */
    "slug"?: string;
    "path"?: string;
}

export interface SessionInvocationInput {
    "name": string;
    "repository"?: string;
    "workspace"?: string;
    "agent"?: string;
}

/**
 * SessionLaunchOptions is the narrow DTO used by the session launch dialog.
 */
export interface SessionLaunchOptions {
    "repositories": SessionLaunchRepository[] | null;
    "defaultRepository": string;
    "workspaces": SessionLaunchWorkspace[] | null;
    "agents": string[] | null;
    "defaultAgent": string;
}

/**
 * SessionLaunchRepository is the safe presentation of a repository available
 * to an interactive action. Local checkout paths stay backend-only.
 */
export interface SessionLaunchRepository {
    "name": string;
    "repository": string;
}

/**
 * SessionLaunchWorkspace identifies a configured workspace by its stable
 * directory name.
 */
export interface SessionLaunchWorkspace {
    "dir": string;
    "name": string;
    "supportsPrompt": boolean;
}

/**
 * TerminalTarget identifies the terminal session — and optionally the window
 * inside it — an action was invoked from. It carries identity only: every
 * value a template can read is resolved from the session record at invocation
 * time, so a client cannot hand an executor a checkout path of its choosing.
 */
export interface TerminalTarget {
    "slug": string;

    /**
     * WindowID is set when the invocation came from a window row. It is what
     * separates a window invocation from a session one, and it is the tmux
     * window id, so it addresses the window across renames.
     */
    "windowId"?: string;
}
