// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Action is an action offered for a feed item's kind, for the detail-pane
 * picker.
 */
export interface Action {
    "id": string;
    "icon": string;
    "color": string;
    "title": string;
    "sub": string;
    "primary": boolean;
}
