// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Item is a normalized GitHub item (PR or issue) produced by a source fetch.
 * It is JSON-encoded as a source node's event_log payload and re-surfaced as
 * a durable inbox row, so the frontend and the persisted feed both read this shape.
 */
export interface Item {
    "id": string;

    /**
     * "PR" | "Issue"
     */
    "kind": string;
    "repo": string;
    "num": number;
    "title": string;
    "author": string;
    "age": string;

    /**
     * GitHub's last-updated time, unix milliseconds
     */
    "updatedAt": number;
    "unread": boolean;

    /**
     * Reason is the GitHub notification reason (e.g. "review_requested"),
     * empty for items known only from search.
     */
    "reason"?: string;
    "labels": string[] | null;
    "branch": string;
    "body": string;
    "prompt": string;
    "url": string;
}
