// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package pipelinedb

import (
	"database/sql"
)

type ConsumerOffset struct {
	Consumer string `json:"consumer"`
	Offset   int64  `json:"offset"`
}

type EventLog struct {
	Offset    int64  `json:"offset"`
	Topic     string `json:"topic"`
	Key       string `json:"key"`
	Payload   []byte `json:"payload"`
	CreatedAt int64  `json:"created_at"`
	Snapshot  int64  `json:"snapshot"`
}

type FeedItem struct {
	FeedID      string `json:"feed_id"`
	ItemID      string `json:"item_id"`
	Payload     []byte `json:"payload"`
	UpdatedAt   int64  `json:"updated_at"`
	Unread      int64  `json:"unread"`
	SourceTopic string `json:"source_topic"`
	SnapshotID  string `json:"snapshot_id"`
}

type NodeRun struct {
	FlowID    string         `json:"flow_id"`
	NodeID    string         `json:"node_id"`
	Ok        int64          `json:"ok"`
	InCount   int64          `json:"in_count"`
	OutCount  int64          `json:"out_count"`
	DropCount int64          `json:"drop_count"`
	Err       sql.NullString `json:"err"`
	EndedAt   int64          `json:"ended_at"`
	DurMs     int64          `json:"dur_ms"`
}

type OutputCommand struct {
	ID         int64          `json:"id"`
	ActionID   string         `json:"action_id"`
	Payload    []byte         `json:"payload"`
	Status     string         `json:"status"`
	CreatedAt  int64          `json:"created_at"`
	Key        string         `json:"key"`
	Attempts   int64          `json:"attempts"`
	LastError  sql.NullString `json:"last_error"`
	ResultJson sql.NullString `json:"result_json"`
	Stdout     sql.NullString `json:"stdout"`
	Stderr     sql.NullString `json:"stderr"`
}

type SourceHead struct {
	Topic   string `json:"topic"`
	Key     string `json:"key"`
	Payload []byte `json:"payload"`
}
