// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package pipelinedb

import (
	"context"
	"database/sql"
)

const appendActivityEvent = `-- name: AppendActivityEvent :one
INSERT INTO activity_event (created_at, category, severity, title, body, source, metadata)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, created_at, category, severity, title, body, source, metadata
`

type AppendActivityEventParams struct {
	CreatedAt int64  `json:"created_at"`
	Category  string `json:"category"`
	Severity  string `json:"severity"`
	Title     string `json:"title"`
	Body      string `json:"body"`
	Source    string `json:"source"`
	Metadata  []byte `json:"metadata"`
}

// Append one audit-log row and return it (with its assigned id) so the caller
// can echo the stored event straight back to subscribers.
func (q *Queries) AppendActivityEvent(ctx context.Context, arg AppendActivityEventParams) (ActivityEvent, error) {
	row := q.db.QueryRowContext(ctx, appendActivityEvent,
		arg.CreatedAt,
		arg.Category,
		arg.Severity,
		arg.Title,
		arg.Body,
		arg.Source,
		arg.Metadata,
	)
	var i ActivityEvent
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.Category,
		&i.Severity,
		&i.Title,
		&i.Body,
		&i.Source,
		&i.Metadata,
	)
	return i, err
}

const appendEvent = `-- name: AppendEvent :one
INSERT INTO event_log (topic, key, payload, created_at, snapshot, source_kind, source_scope, occurrence_key)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING "offset"
`

type AppendEventParams struct {
	Topic         string         `json:"topic"`
	Key           string         `json:"key"`
	Payload       []byte         `json:"payload"`
	CreatedAt     int64          `json:"created_at"`
	Snapshot      int64          `json:"snapshot"`
	SourceKind    string         `json:"source_kind"`
	SourceScope   string         `json:"source_scope"`
	OccurrenceKey sql.NullString `json:"occurrence_key"`
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, appendEvent,
		arg.Topic,
		arg.Key,
		arg.Payload,
		arg.CreatedAt,
		arg.Snapshot,
		arg.SourceKind,
		arg.SourceScope,
		arg.OccurrenceKey,
	)
	var offset int64
	err := row.Scan(&offset)
	return offset, err
}

const commitConsumerOffset = `-- name: CommitConsumerOffset :exec
INSERT INTO consumer_offset (consumer, "offset")
VALUES (?, ?)
ON CONFLICT(consumer) DO UPDATE SET "offset" = excluded."offset"
WHERE excluded."offset" > consumer_offset."offset"
`

type CommitConsumerOffsetParams struct {
	Consumer string `json:"consumer"`
	Offset   int64  `json:"offset"`
}

// Monotonic upsert: on conflict, only advance the stored offset when the
// incoming one is greater. If it isn't, the WHERE clause makes the DO UPDATE
// a no-op (SQLite upsert semantics), so a stale/out-of-order commit never
// regresses a consumer's checkpoint.
func (q *Queries) CommitConsumerOffset(ctx context.Context, arg CommitConsumerOffsetParams) error {
	_, err := q.db.ExecContext(ctx, commitConsumerOffset, arg.Consumer, arg.Offset)
	return err
}

const confirmOutputCommand = `-- name: ConfirmOutputCommand :one
INSERT INTO output_command (action_id, key, payload, status, created_at)
VALUES (?, ?, ?, 'running', ?)
ON CONFLICT(action_id, key) DO UPDATE SET status = 'running'
WHERE output_command.status = 'pending'
RETURNING id, action_id, "key", payload, status, attempts, last_error, result_json, stdout, stderr, created_at
`

type ConfirmOutputCommandParams struct {
	ActionID  string `json:"action_id"`
	Key       string `json:"key"`
	Payload   []byte `json:"payload"`
	CreatedAt int64  `json:"created_at"`
}

// Explicit detail invocation creates work or claims a queued flow command.
// Terminal/running commands remain deduplicated.
func (q *Queries) ConfirmOutputCommand(ctx context.Context, arg ConfirmOutputCommandParams) (OutputCommand, error) {
	row := q.db.QueryRowContext(ctx, confirmOutputCommand,
		arg.ActionID,
		arg.Key,
		arg.Payload,
		arg.CreatedAt,
	)
	var i OutputCommand
	err := row.Scan(
		&i.ID,
		&i.ActionID,
		&i.Key,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.ResultJson,
		&i.Stdout,
		&i.Stderr,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEventsThrough = `-- name: DeleteEventsThrough :exec
DELETE FROM event_log
WHERE "offset" <= ?
`

func (q *Queries) DeleteEventsThrough(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, deleteEventsThrough, offset)
	return err
}

const enqueueOutputCommand = `-- name: EnqueueOutputCommand :exec
INSERT INTO output_command (action_id, key, payload, status, created_at)
VALUES (?, ?, ?, 'pending', ?)
ON CONFLICT(action_id, key) DO NOTHING
`

type EnqueueOutputCommandParams struct {
	ActionID  string `json:"action_id"`
	Key       string `json:"key"`
	Payload   []byte `json:"payload"`
	CreatedAt int64  `json:"created_at"`
}

// Deduped on (action_id, key): a replayed commit batch enqueues the same
// action invocation at most once (see idx_output_command_action_key).
func (q *Queries) EnqueueOutputCommand(ctx context.Context, arg EnqueueOutputCommandParams) error {
	_, err := q.db.ExecContext(ctx, enqueueOutputCommand,
		arg.ActionID,
		arg.Key,
		arg.Payload,
		arg.CreatedAt,
	)
	return err
}

const findRunningJobByCommandID = `-- name: FindRunningJobByCommandID :one
SELECT id, created_at, updated_at, status, label, step, action_id, target, error, command_id FROM job
WHERE command_id = ? AND status = 'running'
ORDER BY id DESC
LIMIT 1
`

// Restore a running job's identity after a worker or app restart so retries do
// not create duplicate jobs and strand the original lifecycle as active.
func (q *Queries) FindRunningJobByCommandID(ctx context.Context, commandID sql.NullInt64) (Job, error) {
	row := q.db.QueryRowContext(ctx, findRunningJobByCommandID, commandID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.Label,
		&i.Step,
		&i.ActionID,
		&i.Target,
		&i.Error,
		&i.CommandID,
	)
	return i, err
}

const getConsumerOffset = `-- name: GetConsumerOffset :one
SELECT consumer, "offset" FROM consumer_offset
WHERE consumer = ?
`

func (q *Queries) GetConsumerOffset(ctx context.Context, consumer string) (ConsumerOffset, error) {
	row := q.db.QueryRowContext(ctx, getConsumerOffset, consumer)
	var i ConsumerOffset
	err := row.Scan(&i.Consumer, &i.Offset)
	return i, err
}

const getInboxItemByExternalID = `-- name: GetInboxItemByExternalID :one
SELECT id, profile_id, source_kind, source_scope, external_id, title, url, payload, revision, unread, archived_at, archived_actor, archived_reason, lifecycle, source_state, first_seen_at, last_event_at FROM inbox_item
WHERE profile_id = ? AND source_kind = ? AND source_scope = ? AND external_id = ?
`

type GetInboxItemByExternalIDParams struct {
	ProfileID   string `json:"profile_id"`
	SourceKind  string `json:"source_kind"`
	SourceScope string `json:"source_scope"`
	ExternalID  string `json:"external_id"`
}

func (q *Queries) GetInboxItemByExternalID(ctx context.Context, arg GetInboxItemByExternalIDParams) (InboxItem, error) {
	row := q.db.QueryRowContext(ctx, getInboxItemByExternalID,
		arg.ProfileID,
		arg.SourceKind,
		arg.SourceScope,
		arg.ExternalID,
	)
	var i InboxItem
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.SourceKind,
		&i.SourceScope,
		&i.ExternalID,
		&i.Title,
		&i.Url,
		&i.Payload,
		&i.Revision,
		&i.Unread,
		&i.ArchivedAt,
		&i.ArchivedActor,
		&i.ArchivedReason,
		&i.Lifecycle,
		&i.SourceState,
		&i.FirstSeenAt,
		&i.LastEventAt,
	)
	return i, err
}

const getOutputCommand = `-- name: GetOutputCommand :one
SELECT id, action_id, "key", payload, status, attempts, last_error, result_json, stdout, stderr, created_at FROM output_command WHERE id = ?
`

func (q *Queries) GetOutputCommand(ctx context.Context, id int64) (OutputCommand, error) {
	row := q.db.QueryRowContext(ctx, getOutputCommand, id)
	var i OutputCommand
	err := row.Scan(
		&i.ID,
		&i.ActionID,
		&i.Key,
		&i.Payload,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.ResultJson,
		&i.Stdout,
		&i.Stderr,
		&i.CreatedAt,
	)
	return i, err
}

const getSourceHeadPayload = `-- name: GetSourceHeadPayload :one
SELECT payload FROM source_head
WHERE topic = ? AND key = ?
`

type GetSourceHeadPayloadParams struct {
	Topic string `json:"topic"`
	Key   string `json:"key"`
}

func (q *Queries) GetSourceHeadPayload(ctx context.Context, arg GetSourceHeadPayloadParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getSourceHeadPayload, arg.Topic, arg.Key)
	var payload []byte
	err := row.Scan(&payload)
	return payload, err
}

const insertInboxEvent = `-- name: InsertInboxEvent :one
INSERT INTO inbox_event (item_id, kind, transition, attention, occurrence_key, summary, detail, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (item_id, occurrence_key) WHERE occurrence_key IS NOT NULL DO NOTHING
RETURNING id, item_id, kind, transition, attention, occurrence_key, summary, detail, created_at
`

type InsertInboxEventParams struct {
	ItemID        int64          `json:"item_id"`
	Kind          string         `json:"kind"`
	Transition    string         `json:"transition"`
	Attention     string         `json:"attention"`
	OccurrenceKey sql.NullString `json:"occurrence_key"`
	Summary       sql.NullString `json:"summary"`
	Detail        []byte         `json:"detail"`
	CreatedAt     int64          `json:"created_at"`
}

func (q *Queries) InsertInboxEvent(ctx context.Context, arg InsertInboxEventParams) (InboxEvent, error) {
	row := q.db.QueryRowContext(ctx, insertInboxEvent,
		arg.ItemID,
		arg.Kind,
		arg.Transition,
		arg.Attention,
		arg.OccurrenceKey,
		arg.Summary,
		arg.Detail,
		arg.CreatedAt,
	)
	var i InboxEvent
	err := row.Scan(
		&i.ID,
		&i.ItemID,
		&i.Kind,
		&i.Transition,
		&i.Attention,
		&i.OccurrenceKey,
		&i.Summary,
		&i.Detail,
		&i.CreatedAt,
	)
	return i, err
}

const insertInboxItem = `-- name: InsertInboxItem :one
INSERT INTO inbox_item (
    profile_id, source_kind, source_scope, external_id,
    title, url, payload, revision, unread,
    lifecycle, first_seen_at, last_event_at
) VALUES (
    ?, ?, ?, ?,
    ?, ?, ?, 1, ?,
    ?, ?, ?
)
RETURNING id, profile_id, source_kind, source_scope, external_id, title, url, payload, revision, unread, archived_at, archived_actor, archived_reason, lifecycle, source_state, first_seen_at, last_event_at
`

type InsertInboxItemParams struct {
	ProfileID   string `json:"profile_id"`
	SourceKind  string `json:"source_kind"`
	SourceScope string `json:"source_scope"`
	ExternalID  string `json:"external_id"`
	Title       string `json:"title"`
	Url         string `json:"url"`
	Payload     []byte `json:"payload"`
	Unread      int64  `json:"unread"`
	Lifecycle   string `json:"lifecycle"`
	FirstSeenAt int64  `json:"first_seen_at"`
	LastEventAt int64  `json:"last_event_at"`
}

// Seed-only plain insert for deterministic desktop fixtures. The ingestion
// path receives its classify-and-upsert contract in a later phase.
func (q *Queries) InsertInboxItem(ctx context.Context, arg InsertInboxItemParams) (InboxItem, error) {
	row := q.db.QueryRowContext(ctx, insertInboxItem,
		arg.ProfileID,
		arg.SourceKind,
		arg.SourceScope,
		arg.ExternalID,
		arg.Title,
		arg.Url,
		arg.Payload,
		arg.Unread,
		arg.Lifecycle,
		arg.FirstSeenAt,
		arg.LastEventAt,
	)
	var i InboxItem
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.SourceKind,
		&i.SourceScope,
		&i.ExternalID,
		&i.Title,
		&i.Url,
		&i.Payload,
		&i.Revision,
		&i.Unread,
		&i.ArchivedAt,
		&i.ArchivedActor,
		&i.ArchivedReason,
		&i.Lifecycle,
		&i.SourceState,
		&i.FirstSeenAt,
		&i.LastEventAt,
	)
	return i, err
}

const insertJob = `-- name: InsertJob :one
INSERT INTO job (created_at, updated_at, status, label, step, action_id, target, error, command_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, created_at, updated_at, status, label, step, action_id, target, error, command_id
`

type InsertJobParams struct {
	CreatedAt int64         `json:"created_at"`
	UpdatedAt int64         `json:"updated_at"`
	Status    string        `json:"status"`
	Label     string        `json:"label"`
	Step      string        `json:"step"`
	ActionID  string        `json:"action_id"`
	Target    string        `json:"target"`
	Error     string        `json:"error"`
	CommandID sql.NullInt64 `json:"command_id"`
}

func (q *Queries) InsertJob(ctx context.Context, arg InsertJobParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, insertJob,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Status,
		arg.Label,
		arg.Step,
		arg.ActionID,
		arg.Target,
		arg.Error,
		arg.CommandID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.Label,
		&i.Step,
		&i.ActionID,
		&i.Target,
		&i.Error,
		&i.CommandID,
	)
	return i, err
}

const insertNodeRun = `-- name: InsertNodeRun :exec
INSERT INTO node_run (flow_id, node_id, ok, in_count, out_count, drop_count, err, ended_at, dur_ms)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertNodeRunParams struct {
	FlowID    string         `json:"flow_id"`
	NodeID    string         `json:"node_id"`
	Ok        int64          `json:"ok"`
	InCount   int64          `json:"in_count"`
	OutCount  int64          `json:"out_count"`
	DropCount int64          `json:"drop_count"`
	Err       sql.NullString `json:"err"`
	EndedAt   int64          `json:"ended_at"`
	DurMs     int64          `json:"dur_ms"`
}

func (q *Queries) InsertNodeRun(ctx context.Context, arg InsertNodeRunParams) error {
	_, err := q.db.ExecContext(ctx, insertNodeRun,
		arg.FlowID,
		arg.NodeID,
		arg.Ok,
		arg.InCount,
		arg.OutCount,
		arg.DropCount,
		arg.Err,
		arg.EndedAt,
		arg.DurMs,
	)
	return err
}

const listActiveJobs = `-- name: ListActiveJobs :many
SELECT id, created_at, updated_at, status, label, step, action_id, target, error, command_id FROM job
WHERE status IN ('queued', 'running') OR (status IN ('done', 'failed') AND updated_at >= ?)
ORDER BY id DESC
`

// Non-terminal jobs plus terminal jobs updated within a recency window, newest
// first. Drives the auto-hiding titlebar chip.
func (q *Queries) ListActiveJobs(ctx context.Context, updatedAt int64) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listActiveJobs, updatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.Label,
			&i.Step,
			&i.ActionID,
			&i.Target,
			&i.Error,
			&i.CommandID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityEvents = `-- name: ListActivityEvents :many
SELECT id, created_at, category, severity, title, body, source, metadata FROM activity_event
WHERE id < ?
ORDER BY id DESC
LIMIT ?
`

type ListActivityEventsParams struct {
	ID    int64 `json:"id"`
	Limit int64 `json:"limit"`
}

// Newest first, paged by a descending id cursor: pass a sentinel above the
// largest id for the first page, then the smallest id returned to continue.
func (q *Queries) ListActivityEvents(ctx context.Context, arg ListActivityEventsParams) ([]ActivityEvent, error) {
	rows, err := q.db.QueryContext(ctx, listActivityEvents, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActivityEvent{}
	for rows.Next() {
		var i ActivityEvent
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Category,
			&i.Severity,
			&i.Title,
			&i.Body,
			&i.Source,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConsumerOffsets = `-- name: ListConsumerOffsets :many
SELECT consumer, "offset" FROM consumer_offset
`

func (q *Queries) ListConsumerOffsets(ctx context.Context) ([]ConsumerOffset, error) {
	rows, err := q.db.QueryContext(ctx, listConsumerOffsets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ConsumerOffset{}
	for rows.Next() {
		var i ConsumerOffset
		if err := rows.Scan(&i.Consumer, &i.Offset); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT id, created_at, updated_at, status, label, step, action_id, target, error, command_id FROM job WHERE id < ? ORDER BY id DESC LIMIT ?
`

type ListJobsParams struct {
	ID    int64 `json:"id"`
	Limit int64 `json:"limit"`
}

// Newest first, paged by a descending id cursor (same shape as ListActivityEvents).
func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.QueryContext(ctx, listJobs, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Job{}
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Status,
			&i.Label,
			&i.Step,
			&i.ActionID,
			&i.Target,
			&i.Error,
			&i.CommandID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeRunsByFlow = `-- name: ListNodeRunsByFlow :many
SELECT flow_id, node_id, ok, in_count, out_count, drop_count, err, ended_at, dur_ms FROM node_run
WHERE flow_id = ?
ORDER BY ended_at DESC
LIMIT ?
`

type ListNodeRunsByFlowParams struct {
	FlowID string `json:"flow_id"`
	Limit  int64  `json:"limit"`
}

// Recent runs, newest first: the canvas derives latest-per-node status and a
// RECENT list from this page rather than querying per-node.
func (q *Queries) ListNodeRunsByFlow(ctx context.Context, arg ListNodeRunsByFlowParams) ([]NodeRun, error) {
	rows, err := q.db.QueryContext(ctx, listNodeRunsByFlow, arg.FlowID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeRun{}
	for rows.Next() {
		var i NodeRun
		if err := rows.Scan(
			&i.FlowID,
			&i.NodeID,
			&i.Ok,
			&i.InCount,
			&i.OutCount,
			&i.DropCount,
			&i.Err,
			&i.EndedAt,
			&i.DurMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunnableOutputCommands = `-- name: ListRunnableOutputCommands :many
SELECT id, action_id, "key", payload, status, attempts, last_error, result_json, stdout, stderr, created_at FROM output_command
WHERE status = 'pending'
ORDER BY id ASC
LIMIT ?
`

// Every enqueued flow action is runnable immediately; running is reserved for
// an explicit detail invocation.
func (q *Queries) ListRunnableOutputCommands(ctx context.Context, limit int64) ([]OutputCommand, error) {
	rows, err := q.db.QueryContext(ctx, listRunnableOutputCommands, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutputCommand{}
	for rows.Next() {
		var i OutputCommand
		if err := rows.Scan(
			&i.ID,
			&i.ActionID,
			&i.Key,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.ResultJson,
			&i.Stdout,
			&i.Stderr,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunnableOutputCommandsAfter = `-- name: ListRunnableOutputCommandsAfter :many
SELECT id, action_id, "key", payload, status, attempts, last_error, result_json, stdout, stderr, created_at FROM output_command
WHERE status = 'pending' AND id > ?
ORDER BY id ASC
LIMIT ?
`

type ListRunnableOutputCommandsAfterParams struct {
	ID    int64 `json:"id"`
	Limit int64 `json:"limit"`
}

// Continue a bounded worker scan after the previous row. The status/id
// predicate is covered by idx_output_command_status_id.
func (q *Queries) ListRunnableOutputCommandsAfter(ctx context.Context, arg ListRunnableOutputCommandsAfterParams) ([]OutputCommand, error) {
	rows, err := q.db.QueryContext(ctx, listRunnableOutputCommandsAfter, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutputCommand{}
	for rows.Next() {
		var i OutputCommand
		if err := rows.Scan(
			&i.ID,
			&i.ActionID,
			&i.Key,
			&i.Payload,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.ResultJson,
			&i.Stdout,
			&i.Stderr,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSourceHeadKeys = `-- name: ListSourceHeadKeys :many
SELECT key FROM source_head WHERE topic = ?
`

func (q *Queries) ListSourceHeadKeys(ctx context.Context, topic string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSourceHeadKeys, topic)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutputCommandDone = `-- name: MarkOutputCommandDone :exec
UPDATE output_command
SET status = 'done', last_error = NULL, result_json = ?, stdout = ?, stderr = ?
WHERE id = ?
`

type MarkOutputCommandDoneParams struct {
	ResultJson sql.NullString `json:"result_json"`
	Stdout     sql.NullString `json:"stdout"`
	Stderr     sql.NullString `json:"stderr"`
	ID         int64          `json:"id"`
}

func (q *Queries) MarkOutputCommandDone(ctx context.Context, arg MarkOutputCommandDoneParams) error {
	_, err := q.db.ExecContext(ctx, markOutputCommandDone,
		arg.ResultJson,
		arg.Stdout,
		arg.Stderr,
		arg.ID,
	)
	return err
}

const markOutputCommandFailed = `-- name: MarkOutputCommandFailed :exec
UPDATE output_command SET status = 'failed', attempts = attempts + 1, last_error = ?, stdout = ?, stderr = ?
WHERE id = ?
`

type MarkOutputCommandFailedParams struct {
	LastError sql.NullString `json:"last_error"`
	Stdout    sql.NullString `json:"stdout"`
	Stderr    sql.NullString `json:"stderr"`
	ID        int64          `json:"id"`
}

func (q *Queries) MarkOutputCommandFailed(ctx context.Context, arg MarkOutputCommandFailedParams) error {
	_, err := q.db.ExecContext(ctx, markOutputCommandFailed,
		arg.LastError,
		arg.Stdout,
		arg.Stderr,
		arg.ID,
	)
	return err
}

const pruneActivityEvents = `-- name: PruneActivityEvents :exec
DELETE FROM activity_event
WHERE id IN (
    SELECT id FROM activity_event
    ORDER BY id DESC
    LIMIT -1 OFFSET ?
)
`

// Retain only the newest rows globally; bounded diagnostic history like
// node_run. The id primary key both orders and breaks ties exactly.
func (q *Queries) PruneActivityEvents(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, pruneActivityEvents, offset)
	return err
}

const pruneNodeRuns = `-- name: PruneNodeRuns :exec
DELETE FROM node_run
WHERE rowid IN (
    SELECT rowid FROM node_run
    ORDER BY ended_at DESC, rowid DESC
    LIMIT -1 OFFSET ?
)
`

// Retain the newest rows globally. rowid breaks same-nanosecond ties, so the
// limit is exact even when a fast batch stamps equal ended_at values.
func (q *Queries) PruneNodeRuns(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, pruneNodeRuns, offset)
	return err
}

const pruneTerminalJobs = `-- name: PruneTerminalJobs :exec
DELETE FROM job
WHERE id IN (
    SELECT id FROM job
    WHERE status IN ('done', 'failed')
    ORDER BY id DESC
    LIMIT -1 OFFSET ?
)
`

// Never remove active jobs: only terminal done/failed history is bounded
// (mirrors PruneTerminalOutputCommands).
func (q *Queries) PruneTerminalJobs(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, pruneTerminalJobs, offset)
	return err
}

const pruneTerminalOutputCommands = `-- name: PruneTerminalOutputCommands :exec
DELETE FROM output_command
WHERE id IN (
    SELECT id FROM output_command
    WHERE status IN ('done', 'failed')
    ORDER BY id DESC
    LIMIT -1 OFFSET ?
)
`

// Never remove active commands: only terminal done/failed history is bounded.
func (q *Queries) PruneTerminalOutputCommands(ctx context.Context, offset int64) error {
	_, err := q.db.ExecContext(ctx, pruneTerminalOutputCommands, offset)
	return err
}

const readEventsFrom = `-- name: ReadEventsFrom :many
SELECT "offset", topic, "key", payload, snapshot, source_kind, source_scope, occurrence_key, created_at FROM event_log
WHERE "offset" > ?
ORDER BY "offset" ASC
LIMIT ?
`

type ReadEventsFromParams struct {
	Offset int64 `json:"offset"`
	Limit  int64 `json:"limit"`
}

func (q *Queries) ReadEventsFrom(ctx context.Context, arg ReadEventsFromParams) ([]EventLog, error) {
	rows, err := q.db.QueryContext(ctx, readEventsFrom, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventLog{}
	for rows.Next() {
		var i EventLog
		if err := rows.Scan(
			&i.Offset,
			&i.Topic,
			&i.Key,
			&i.Payload,
			&i.Snapshot,
			&i.SourceKind,
			&i.SourceScope,
			&i.OccurrenceKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retryOutputCommand = `-- name: RetryOutputCommand :exec
UPDATE output_command SET attempts = attempts + 1, last_error = ?, stdout = ?, stderr = ?
WHERE id = ?
`

type RetryOutputCommandParams struct {
	LastError sql.NullString `json:"last_error"`
	Stdout    sql.NullString `json:"stdout"`
	Stderr    sql.NullString `json:"stderr"`
	ID        int64          `json:"id"`
}

func (q *Queries) RetryOutputCommand(ctx context.Context, arg RetryOutputCommandParams) error {
	_, err := q.db.ExecContext(ctx, retryOutputCommand,
		arg.LastError,
		arg.Stdout,
		arg.Stderr,
		arg.ID,
	)
	return err
}

const setJobRunning = `-- name: SetJobRunning :one
UPDATE job SET updated_at = ?, status = ?, step = ?, command_id = ?
WHERE id = ?
RETURNING id, created_at, updated_at, status, label, step, action_id, target, error, command_id
`

type SetJobRunningParams struct {
	UpdatedAt int64         `json:"updated_at"`
	Status    string        `json:"status"`
	Step      string        `json:"step"`
	CommandID sql.NullInt64 `json:"command_id"`
	ID        int64         `json:"id"`
}

// Advance a job to running and link its output_command. This is the ONLY write
// that sets command_id, so terminal transitions can never null it out.
func (q *Queries) SetJobRunning(ctx context.Context, arg SetJobRunningParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, setJobRunning,
		arg.UpdatedAt,
		arg.Status,
		arg.Step,
		arg.CommandID,
		arg.ID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.Label,
		&i.Step,
		&i.ActionID,
		&i.Target,
		&i.Error,
		&i.CommandID,
	)
	return i, err
}

const setJobStatus = `-- name: SetJobStatus :one
UPDATE job SET updated_at = ?, status = ?, step = ?, error = ?
WHERE id = ?
RETURNING id, created_at, updated_at, status, label, step, action_id, target, error, command_id
`

type SetJobStatusParams struct {
	UpdatedAt int64  `json:"updated_at"`
	Status    string `json:"status"`
	Step      string `json:"step"`
	Error     string `json:"error"`
	ID        int64  `json:"id"`
}

// Advance a job's status/step/error WITHOUT touching command_id (used by the
// done/failed terminal transitions). Splitting this from SetJobRunning avoids a
// read-modify-write and prevents clobbering the command link.
func (q *Queries) SetJobStatus(ctx context.Context, arg SetJobStatusParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, setJobStatus,
		arg.UpdatedAt,
		arg.Status,
		arg.Step,
		arg.Error,
		arg.ID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Status,
		&i.Label,
		&i.Step,
		&i.ActionID,
		&i.Target,
		&i.Error,
		&i.CommandID,
	)
	return i, err
}

const updateEventOccurrenceKey = `-- name: UpdateEventOccurrenceKey :exec
UPDATE event_log SET occurrence_key = ? WHERE "offset" = ?
`

type UpdateEventOccurrenceKeyParams struct {
	OccurrenceKey sql.NullString `json:"occurrence_key"`
	Offset        int64          `json:"offset"`
}

func (q *Queries) UpdateEventOccurrenceKey(ctx context.Context, arg UpdateEventOccurrenceKeyParams) error {
	_, err := q.db.ExecContext(ctx, updateEventOccurrenceKey, arg.OccurrenceKey, arg.Offset)
	return err
}

const upsertInboxItem = `-- name: UpsertInboxItem :one
INSERT INTO inbox_item (
    profile_id, source_kind, source_scope, external_id,
    title, url, payload, revision, unread,
    archived_at, archived_actor, archived_reason,
    lifecycle, source_state, first_seen_at, last_event_at
) VALUES (?, ?, ?, ?, ?, ?, ?, 1, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT (profile_id, source_kind, source_scope, external_id) DO UPDATE SET
    title = excluded.title, url = excluded.url, payload = excluded.payload,
    revision = inbox_item.revision + 1, unread = excluded.unread,
    archived_at = excluded.archived_at, archived_actor = excluded.archived_actor,
    archived_reason = excluded.archived_reason, lifecycle = excluded.lifecycle,
    source_state = excluded.source_state, last_event_at = excluded.last_event_at
RETURNING id, profile_id, source_kind, source_scope, external_id, title, url, payload, revision, unread, archived_at, archived_actor, archived_reason, lifecycle, source_state, first_seen_at, last_event_at
`

type UpsertInboxItemParams struct {
	ProfileID      string         `json:"profile_id"`
	SourceKind     string         `json:"source_kind"`
	SourceScope    string         `json:"source_scope"`
	ExternalID     string         `json:"external_id"`
	Title          string         `json:"title"`
	Url            string         `json:"url"`
	Payload        []byte         `json:"payload"`
	Unread         int64          `json:"unread"`
	ArchivedAt     sql.NullInt64  `json:"archived_at"`
	ArchivedActor  sql.NullString `json:"archived_actor"`
	ArchivedReason sql.NullString `json:"archived_reason"`
	Lifecycle      string         `json:"lifecycle"`
	SourceState    sql.NullString `json:"source_state"`
	FirstSeenAt    int64          `json:"first_seen_at"`
	LastEventAt    int64          `json:"last_event_at"`
}

func (q *Queries) UpsertInboxItem(ctx context.Context, arg UpsertInboxItemParams) (InboxItem, error) {
	row := q.db.QueryRowContext(ctx, upsertInboxItem,
		arg.ProfileID,
		arg.SourceKind,
		arg.SourceScope,
		arg.ExternalID,
		arg.Title,
		arg.Url,
		arg.Payload,
		arg.Unread,
		arg.ArchivedAt,
		arg.ArchivedActor,
		arg.ArchivedReason,
		arg.Lifecycle,
		arg.SourceState,
		arg.FirstSeenAt,
		arg.LastEventAt,
	)
	var i InboxItem
	err := row.Scan(
		&i.ID,
		&i.ProfileID,
		&i.SourceKind,
		&i.SourceScope,
		&i.ExternalID,
		&i.Title,
		&i.Url,
		&i.Payload,
		&i.Revision,
		&i.Unread,
		&i.ArchivedAt,
		&i.ArchivedActor,
		&i.ArchivedReason,
		&i.Lifecycle,
		&i.SourceState,
		&i.FirstSeenAt,
		&i.LastEventAt,
	)
	return i, err
}

const upsertSourceHead = `-- name: UpsertSourceHead :exec
INSERT INTO source_head (topic, key, payload)
VALUES (?, ?, ?)
ON CONFLICT(topic, key) DO UPDATE SET payload = excluded.payload
`

type UpsertSourceHeadParams struct {
	Topic   string `json:"topic"`
	Key     string `json:"key"`
	Payload []byte `json:"payload"`
}

func (q *Queries) UpsertSourceHead(ctx context.Context, arg UpsertSourceHeadParams) error {
	_, err := q.db.ExecContext(ctx, upsertSourceHead, arg.Topic, arg.Key, arg.Payload)
	return err
}
