// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package pipelinedb

import (
	"context"
	"database/sql"
)

const appendEvent = `-- name: AppendEvent :one
INSERT INTO event_log (topic, key, payload, created_at, snapshot)
VALUES (?, ?, ?, ?, ?)
RETURNING "offset"
`

type AppendEventParams struct {
	Topic     string `json:"topic"`
	Key       string `json:"key"`
	Payload   []byte `json:"payload"`
	CreatedAt int64  `json:"created_at"`
	Snapshot  int64  `json:"snapshot"`
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, appendEvent,
		arg.Topic,
		arg.Key,
		arg.Payload,
		arg.CreatedAt,
		arg.Snapshot,
	)
	var offset int64
	err := row.Scan(&offset)
	return offset, err
}

const commitConsumerOffset = `-- name: CommitConsumerOffset :exec
INSERT INTO consumer_offset (consumer, "offset")
VALUES (?, ?)
ON CONFLICT(consumer) DO UPDATE SET "offset" = excluded."offset"
WHERE excluded."offset" > consumer_offset."offset"
`

type CommitConsumerOffsetParams struct {
	Consumer string `json:"consumer"`
	Offset   int64  `json:"offset"`
}

// Monotonic upsert: on conflict, only advance the stored offset when the
// incoming one is greater. If it isn't, the WHERE clause makes the DO UPDATE
// a no-op (SQLite upsert semantics), so a stale/out-of-order commit never
// regresses a consumer's checkpoint.
func (q *Queries) CommitConsumerOffset(ctx context.Context, arg CommitConsumerOffsetParams) error {
	_, err := q.db.ExecContext(ctx, commitConsumerOffset, arg.Consumer, arg.Offset)
	return err
}

const compactEventLogByKey = `-- name: CompactEventLogByKey :exec
DELETE FROM event_log
WHERE key != ''
  AND "offset" NOT IN (
    SELECT MAX("offset") FROM event_log WHERE key != '' GROUP BY topic, key
  )
`

// Log-compaction pass: for every non-empty (topic, key), keep only the row
// at its highest offset (the current value). Rows with an empty key (system
// events with no stable identity) are exempt from key-compaction.
func (q *Queries) CompactEventLogByKey(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, compactEventLogByKey)
	return err
}

const confirmOutputCommand = `-- name: ConfirmOutputCommand :one
INSERT INTO output_command (action_id, key, payload, status, created_at)
VALUES (?, ?, ?, 'running', ?)
ON CONFLICT(action_id, key) DO UPDATE SET status = 'running'
WHERE output_command.status IN ('pending', 'awaiting_confirmation')
RETURNING id, action_id, payload, status, created_at, "key", attempts, last_error
`

type ConfirmOutputCommandParams struct {
	ActionID  string `json:"action_id"`
	Key       string `json:"key"`
	Payload   []byte `json:"payload"`
	CreatedAt int64  `json:"created_at"`
}

// An explicit detail-pane action invocation creates a command when no flow
// action node did, or promotes that node's awaiting command to running.
// Completed/failed/running commands are deliberately not re-run: output
// actions remain deduped on (action_id, key).
func (q *Queries) ConfirmOutputCommand(ctx context.Context, arg ConfirmOutputCommandParams) (OutputCommand, error) {
	row := q.db.QueryRowContext(ctx, confirmOutputCommand,
		arg.ActionID,
		arg.Key,
		arg.Payload,
		arg.CreatedAt,
	)
	var i OutputCommand
	err := row.Scan(
		&i.ID,
		&i.ActionID,
		&i.Payload,
		&i.Status,
		&i.CreatedAt,
		&i.Key,
		&i.Attempts,
		&i.LastError,
	)
	return i, err
}

const countEventLog = `-- name: CountEventLog :one
SELECT COUNT(*) FROM event_log
`

func (q *Queries) CountEventLog(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEventLog)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFeedItemsByFlow = `-- name: CountFeedItemsByFlow :many
SELECT
    feed_id,
    CAST(COUNT(*) AS INTEGER) AS total,
    CAST(SUM(unread) AS INTEGER) AS unread
FROM feed_item
WHERE feed_id LIKE ?1
GROUP BY feed_id
`

type CountFeedItemsByFlowRow struct {
	FeedID string `json:"feed_id"`
	Total  int64  `json:"total"`
	Unread int64  `json:"unread"`
}

// Per-feed total and unread counts for every feed belonging to a flow, for
// the sidebar rail badges: one query instead of an N-feed fan-out of
// ListFeedItemsByFeed. The caller passes a LIKE prefix like "myflow/%".
func (q *Queries) CountFeedItemsByFlow(ctx context.Context, flowPrefix string) ([]CountFeedItemsByFlowRow, error) {
	rows, err := q.db.QueryContext(ctx, countFeedItemsByFlow, flowPrefix)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountFeedItemsByFlowRow{}
	for rows.Next() {
		var i CountFeedItemsByFlowRow
		if err := rows.Scan(&i.FeedID, &i.Total, &i.Unread); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteEventLogOlderThan = `-- name: DeleteEventLogOlderThan :exec
DELETE FROM event_log WHERE created_at < ?
`

func (q *Queries) DeleteEventLogOlderThan(ctx context.Context, createdAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteEventLogOlderThan, createdAt)
	return err
}

const deleteFeedItemsNotInSnapshot = `-- name: DeleteFeedItemsNotInSnapshot :exec
DELETE FROM feed_item
WHERE feed_id = ?
  AND source_topic = ?
  AND snapshot_id != ?
`

type DeleteFeedItemsNotInSnapshotParams struct {
	FeedID      string `json:"feed_id"`
	SourceTopic string `json:"source_topic"`
	SnapshotID  string `json:"snapshot_id"`
}

func (q *Queries) DeleteFeedItemsNotInSnapshot(ctx context.Context, arg DeleteFeedItemsNotInSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, deleteFeedItemsNotInSnapshot, arg.FeedID, arg.SourceTopic, arg.SnapshotID)
	return err
}

const deleteOldestEventLog = `-- name: DeleteOldestEventLog :exec
DELETE FROM event_log
WHERE "offset" IN (
    SELECT "offset" FROM event_log ORDER BY "offset" ASC LIMIT ?
)
`

// Deletes the oldest ? rows by offset. Used for count-based retention once
// age-based retention still leaves the table over its row cap.
func (q *Queries) DeleteOldestEventLog(ctx context.Context, limit int64) error {
	_, err := q.db.ExecContext(ctx, deleteOldestEventLog, limit)
	return err
}

const enqueueOutputCommand = `-- name: EnqueueOutputCommand :exec
INSERT INTO output_command (action_id, key, payload, status, created_at)
VALUES (?, ?, ?, 'pending', ?)
ON CONFLICT(action_id, key) DO NOTHING
`

type EnqueueOutputCommandParams struct {
	ActionID  string `json:"action_id"`
	Key       string `json:"key"`
	Payload   []byte `json:"payload"`
	CreatedAt int64  `json:"created_at"`
}

// Deduped on (action_id, key): a replayed commit batch enqueues the same
// action invocation at most once (see idx_output_command_action_key).
func (q *Queries) EnqueueOutputCommand(ctx context.Context, arg EnqueueOutputCommandParams) error {
	_, err := q.db.ExecContext(ctx, enqueueOutputCommand,
		arg.ActionID,
		arg.Key,
		arg.Payload,
		arg.CreatedAt,
	)
	return err
}

const getConsumerOffset = `-- name: GetConsumerOffset :one
SELECT consumer, "offset" FROM consumer_offset
WHERE consumer = ?
`

func (q *Queries) GetConsumerOffset(ctx context.Context, consumer string) (ConsumerOffset, error) {
	row := q.db.QueryRowContext(ctx, getConsumerOffset, consumer)
	var i ConsumerOffset
	err := row.Scan(&i.Consumer, &i.Offset)
	return i, err
}

const getSourceHeadPayload = `-- name: GetSourceHeadPayload :one
SELECT payload FROM source_head
WHERE topic = ? AND key = ?
`

type GetSourceHeadPayloadParams struct {
	Topic string `json:"topic"`
	Key   string `json:"key"`
}

func (q *Queries) GetSourceHeadPayload(ctx context.Context, arg GetSourceHeadPayloadParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getSourceHeadPayload, arg.Topic, arg.Key)
	var payload []byte
	err := row.Scan(&payload)
	return payload, err
}

const insertNodeRun = `-- name: InsertNodeRun :exec
INSERT INTO node_run (flow_id, node_id, ok, in_count, out_count, drop_count, err, ended_at, dur_ms)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertNodeRunParams struct {
	FlowID    string         `json:"flow_id"`
	NodeID    string         `json:"node_id"`
	Ok        int64          `json:"ok"`
	InCount   int64          `json:"in_count"`
	OutCount  int64          `json:"out_count"`
	DropCount int64          `json:"drop_count"`
	Err       sql.NullString `json:"err"`
	EndedAt   int64          `json:"ended_at"`
	DurMs     int64          `json:"dur_ms"`
}

func (q *Queries) InsertNodeRun(ctx context.Context, arg InsertNodeRunParams) error {
	_, err := q.db.ExecContext(ctx, insertNodeRun,
		arg.FlowID,
		arg.NodeID,
		arg.Ok,
		arg.InCount,
		arg.OutCount,
		arg.DropCount,
		arg.Err,
		arg.EndedAt,
		arg.DurMs,
	)
	return err
}

const listFeedItemsByFeed = `-- name: ListFeedItemsByFeed :many
SELECT feed_id, item_id, payload, updated_at, unread FROM feed_item
WHERE feed_id = ?
ORDER BY updated_at DESC
`

type ListFeedItemsByFeedRow struct {
	FeedID    string `json:"feed_id"`
	ItemID    string `json:"item_id"`
	Payload   []byte `json:"payload"`
	UpdatedAt int64  `json:"updated_at"`
	Unread    int64  `json:"unread"`
}

func (q *Queries) ListFeedItemsByFeed(ctx context.Context, feedID string) ([]ListFeedItemsByFeedRow, error) {
	rows, err := q.db.QueryContext(ctx, listFeedItemsByFeed, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFeedItemsByFeedRow{}
	for rows.Next() {
		var i ListFeedItemsByFeedRow
		if err := rows.Scan(
			&i.FeedID,
			&i.ItemID,
			&i.Payload,
			&i.UpdatedAt,
			&i.Unread,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeRunsByFlow = `-- name: ListNodeRunsByFlow :many
SELECT flow_id, node_id, ok, in_count, out_count, drop_count, err, ended_at, dur_ms FROM node_run
WHERE flow_id = ?
ORDER BY ended_at DESC
LIMIT ?
`

type ListNodeRunsByFlowParams struct {
	FlowID string `json:"flow_id"`
	Limit  int64  `json:"limit"`
}

// Recent runs, newest first: the canvas derives latest-per-node status and a
// RECENT list from this page rather than querying per-node.
func (q *Queries) ListNodeRunsByFlow(ctx context.Context, arg ListNodeRunsByFlowParams) ([]NodeRun, error) {
	rows, err := q.db.QueryContext(ctx, listNodeRunsByFlow, arg.FlowID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NodeRun{}
	for rows.Next() {
		var i NodeRun
		if err := rows.Scan(
			&i.FlowID,
			&i.NodeID,
			&i.Ok,
			&i.InCount,
			&i.OutCount,
			&i.DropCount,
			&i.Err,
			&i.EndedAt,
			&i.DurMs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunnableOutputCommands = `-- name: ListRunnableOutputCommands :many
SELECT id, action_id, payload, status, created_at, "key", attempts, last_error FROM output_command
WHERE status IN ('pending', 'running')
ORDER BY id ASC
LIMIT ?
`

// Pending commands await automatic classification/execution; running ones
// were explicitly confirmed by the detail pane. ID order matches
// idx_output_command_status_id, avoiding a sort as the queue grows.
func (q *Queries) ListRunnableOutputCommands(ctx context.Context, limit int64) ([]OutputCommand, error) {
	rows, err := q.db.QueryContext(ctx, listRunnableOutputCommands, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutputCommand{}
	for rows.Next() {
		var i OutputCommand
		if err := rows.Scan(
			&i.ID,
			&i.ActionID,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
			&i.Key,
			&i.Attempts,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunnableOutputCommandsAfter = `-- name: ListRunnableOutputCommandsAfter :many
SELECT id, action_id, payload, status, created_at, "key", attempts, last_error FROM output_command
WHERE status IN ('pending', 'running') AND id > ?
ORDER BY id ASC
LIMIT ?
`

type ListRunnableOutputCommandsAfterParams struct {
	ID    int64 `json:"id"`
	Limit int64 `json:"limit"`
}

// Continue a bounded worker scan after the previous row. The status/id
// predicate is covered by idx_output_command_status_id.
func (q *Queries) ListRunnableOutputCommandsAfter(ctx context.Context, arg ListRunnableOutputCommandsAfterParams) ([]OutputCommand, error) {
	rows, err := q.db.QueryContext(ctx, listRunnableOutputCommandsAfter, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutputCommand{}
	for rows.Next() {
		var i OutputCommand
		if err := rows.Scan(
			&i.ID,
			&i.ActionID,
			&i.Payload,
			&i.Status,
			&i.CreatedAt,
			&i.Key,
			&i.Attempts,
			&i.LastError,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFeedItemRead = `-- name: MarkFeedItemRead :exec
UPDATE feed_item SET unread = 0
WHERE feed_id = ? AND item_id = ?
`

type MarkFeedItemReadParams struct {
	FeedID string `json:"feed_id"`
	ItemID string `json:"item_id"`
}

func (q *Queries) MarkFeedItemRead(ctx context.Context, arg MarkFeedItemReadParams) error {
	_, err := q.db.ExecContext(ctx, markFeedItemRead, arg.FeedID, arg.ItemID)
	return err
}

const markOutputCommandAwaitingConfirmation = `-- name: MarkOutputCommandAwaitingConfirmation :exec
UPDATE output_command SET status = 'awaiting_confirmation'
WHERE id = ? AND status = 'pending'
`

func (q *Queries) MarkOutputCommandAwaitingConfirmation(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markOutputCommandAwaitingConfirmation, id)
	return err
}

const markOutputCommandDone = `-- name: MarkOutputCommandDone :exec
UPDATE output_command SET status = 'done'
WHERE id = ?
`

func (q *Queries) MarkOutputCommandDone(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, markOutputCommandDone, id)
	return err
}

const markOutputCommandFailed = `-- name: MarkOutputCommandFailed :exec
UPDATE output_command SET status = 'failed', attempts = attempts + 1, last_error = ?
WHERE id = ?
`

type MarkOutputCommandFailedParams struct {
	LastError sql.NullString `json:"last_error"`
	ID        int64          `json:"id"`
}

func (q *Queries) MarkOutputCommandFailed(ctx context.Context, arg MarkOutputCommandFailedParams) error {
	_, err := q.db.ExecContext(ctx, markOutputCommandFailed, arg.LastError, arg.ID)
	return err
}

const promoteOutputCommandsAwaitingConfirmation = `-- name: PromoteOutputCommandsAwaitingConfirmation :exec
UPDATE output_command SET status = 'pending'
WHERE action_id = ? AND status = 'awaiting_confirmation'
`

// An action changed from manual to auto-apply, so make its previously
// confirmation-gated commands runnable again.
func (q *Queries) PromoteOutputCommandsAwaitingConfirmation(ctx context.Context, actionID string) error {
	_, err := q.db.ExecContext(ctx, promoteOutputCommandsAwaitingConfirmation, actionID)
	return err
}

const readEventsFrom = `-- name: ReadEventsFrom :many
SELECT "offset", topic, "key", payload, created_at, snapshot FROM event_log
WHERE "offset" > ?
ORDER BY "offset" ASC
LIMIT ?
`

type ReadEventsFromParams struct {
	Offset int64 `json:"offset"`
	Limit  int64 `json:"limit"`
}

func (q *Queries) ReadEventsFrom(ctx context.Context, arg ReadEventsFromParams) ([]EventLog, error) {
	rows, err := q.db.QueryContext(ctx, readEventsFrom, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventLog{}
	for rows.Next() {
		var i EventLog
		if err := rows.Scan(
			&i.Offset,
			&i.Topic,
			&i.Key,
			&i.Payload,
			&i.CreatedAt,
			&i.Snapshot,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retryOutputCommand = `-- name: RetryOutputCommand :exec
UPDATE output_command SET attempts = attempts + 1, last_error = ?
WHERE id = ?
`

type RetryOutputCommandParams struct {
	LastError sql.NullString `json:"last_error"`
	ID        int64          `json:"id"`
}

func (q *Queries) RetryOutputCommand(ctx context.Context, arg RetryOutputCommandParams) error {
	_, err := q.db.ExecContext(ctx, retryOutputCommand, arg.LastError, arg.ID)
	return err
}

const upsertFeedItem = `-- name: UpsertFeedItem :exec
INSERT INTO feed_item (feed_id, item_id, payload, updated_at, unread, source_topic, snapshot_id)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(feed_id, item_id) DO UPDATE SET
    payload      = excluded.payload,
    updated_at   = excluded.updated_at,
    unread       = excluded.unread,
    source_topic = excluded.source_topic,
    snapshot_id  = excluded.snapshot_id
`

type UpsertFeedItemParams struct {
	FeedID      string `json:"feed_id"`
	ItemID      string `json:"item_id"`
	Payload     []byte `json:"payload"`
	UpdatedAt   int64  `json:"updated_at"`
	Unread      int64  `json:"unread"`
	SourceTopic string `json:"source_topic"`
	SnapshotID  string `json:"snapshot_id"`
}

// Idempotent by (feed_id, item_id): committing the same key twice updates
// the row in place rather than duplicating it.
func (q *Queries) UpsertFeedItem(ctx context.Context, arg UpsertFeedItemParams) error {
	_, err := q.db.ExecContext(ctx, upsertFeedItem,
		arg.FeedID,
		arg.ItemID,
		arg.Payload,
		arg.UpdatedAt,
		arg.Unread,
		arg.SourceTopic,
		arg.SnapshotID,
	)
	return err
}

const upsertFeedItemSnapshot = `-- name: UpsertFeedItemSnapshot :exec
INSERT INTO feed_item (feed_id, item_id, payload, updated_at, unread, source_topic, snapshot_id)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(feed_id, item_id) DO UPDATE SET
    payload      = excluded.payload,
    updated_at   = excluded.updated_at,
    unread       = feed_item.unread,
    source_topic = excluded.source_topic,
    snapshot_id  = excluded.snapshot_id
`

type UpsertFeedItemSnapshotParams struct {
	FeedID      string `json:"feed_id"`
	ItemID      string `json:"item_id"`
	Payload     []byte `json:"payload"`
	UpdatedAt   int64  `json:"updated_at"`
	Unread      int64  `json:"unread"`
	SourceTopic string `json:"source_topic"`
	SnapshotID  string `json:"snapshot_id"`
}

// Snapshot outputs preserve a previously-read row's unread state while still
// updating its payload and reconciliation marker.
func (q *Queries) UpsertFeedItemSnapshot(ctx context.Context, arg UpsertFeedItemSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, upsertFeedItemSnapshot,
		arg.FeedID,
		arg.ItemID,
		arg.Payload,
		arg.UpdatedAt,
		arg.Unread,
		arg.SourceTopic,
		arg.SnapshotID,
	)
	return err
}

const upsertSourceHead = `-- name: UpsertSourceHead :exec
INSERT INTO source_head (topic, key, payload)
VALUES (?, ?, ?)
ON CONFLICT(topic, key) DO UPDATE SET payload = excluded.payload
`

type UpsertSourceHeadParams struct {
	Topic   string `json:"topic"`
	Key     string `json:"key"`
	Payload []byte `json:"payload"`
}

func (q *Queries) UpsertSourceHead(ctx context.Context, arg UpsertSourceHeadParams) error {
	_, err := q.db.ExecContext(ctx, upsertSourceHead, arg.Topic, arg.Key, arg.Payload)
	return err
}
