// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package pipelinedb

import (
	"context"
)

const appendEvent = `-- name: AppendEvent :one
INSERT INTO event_log (topic, key, payload, created_at)
VALUES (?, ?, ?, ?)
RETURNING "offset"
`

type AppendEventParams struct {
	Topic     string `json:"topic"`
	Key       string `json:"key"`
	Payload   []byte `json:"payload"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) AppendEvent(ctx context.Context, arg AppendEventParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, appendEvent,
		arg.Topic,
		arg.Key,
		arg.Payload,
		arg.CreatedAt,
	)
	var offset int64
	err := row.Scan(&offset)
	return offset, err
}

const commitConsumerOffset = `-- name: CommitConsumerOffset :exec
INSERT INTO consumer_offset (consumer, "offset")
VALUES (?, ?)
ON CONFLICT(consumer) DO UPDATE SET "offset" = excluded."offset"
WHERE excluded."offset" > consumer_offset."offset"
`

type CommitConsumerOffsetParams struct {
	Consumer string `json:"consumer"`
	Offset   int64  `json:"offset"`
}

// Monotonic upsert: on conflict, only advance the stored offset when the
// incoming one is greater. If it isn't, the WHERE clause makes the DO UPDATE
// a no-op (SQLite upsert semantics), so a stale/out-of-order commit never
// regresses a consumer's checkpoint.
func (q *Queries) CommitConsumerOffset(ctx context.Context, arg CommitConsumerOffsetParams) error {
	_, err := q.db.ExecContext(ctx, commitConsumerOffset, arg.Consumer, arg.Offset)
	return err
}

const compactEventLogByKey = `-- name: CompactEventLogByKey :exec
DELETE FROM event_log
WHERE key != ''
  AND "offset" NOT IN (
    SELECT MAX("offset") FROM event_log WHERE key != '' GROUP BY key
  )
`

// Log-compaction pass: for every non-empty key, keep only the row at its
// highest offset (the current value). Rows with an empty key (system events
// with no stable identity) are exempt from key-compaction.
func (q *Queries) CompactEventLogByKey(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, compactEventLogByKey)
	return err
}

const countEventLog = `-- name: CountEventLog :one
SELECT COUNT(*) FROM event_log
`

func (q *Queries) CountEventLog(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEventLog)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteEventLogOlderThan = `-- name: DeleteEventLogOlderThan :exec
DELETE FROM event_log WHERE created_at < ?
`

func (q *Queries) DeleteEventLogOlderThan(ctx context.Context, createdAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteEventLogOlderThan, createdAt)
	return err
}

const deleteOldestEventLog = `-- name: DeleteOldestEventLog :exec
DELETE FROM event_log
WHERE "offset" IN (
    SELECT "offset" FROM event_log ORDER BY "offset" ASC LIMIT ?
)
`

// Deletes the oldest ? rows by offset. Used for count-based retention once
// age-based retention still leaves the table over its row cap.
func (q *Queries) DeleteOldestEventLog(ctx context.Context, limit int64) error {
	_, err := q.db.ExecContext(ctx, deleteOldestEventLog, limit)
	return err
}

const getConsumerOffset = `-- name: GetConsumerOffset :one
SELECT consumer, "offset" FROM consumer_offset
WHERE consumer = ?
`

func (q *Queries) GetConsumerOffset(ctx context.Context, consumer string) (ConsumerOffset, error) {
	row := q.db.QueryRowContext(ctx, getConsumerOffset, consumer)
	var i ConsumerOffset
	err := row.Scan(&i.Consumer, &i.Offset)
	return i, err
}

const readEventsFrom = `-- name: ReadEventsFrom :many
SELECT "offset", topic, "key", payload, created_at FROM event_log
WHERE "offset" > ?
ORDER BY "offset" ASC
LIMIT ?
`

type ReadEventsFromParams struct {
	Offset int64 `json:"offset"`
	Limit  int64 `json:"limit"`
}

func (q *Queries) ReadEventsFrom(ctx context.Context, arg ReadEventsFromParams) ([]EventLog, error) {
	rows, err := q.db.QueryContext(ctx, readEventsFrom, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventLog{}
	for rows.Next() {
		var i EventLog
		if err := rows.Scan(
			&i.Offset,
			&i.Topic,
			&i.Key,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
