// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ActionsService is the explicit editor API for the global actions catalog.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as actions$0 from "../../app/actions/models.js";

export function CreateAction(a: actions$0.EditableAction): $CancellablePromise<actions$0.EditableAction> {
    return $Call.ByID(3533353826, a);
}

export function CreateLauncher(l: actions$0.Launcher): $CancellablePromise<actions$0.Launcher> {
    return $Call.ByID(2007776408, l);
}

export function DeleteAction(id: string): $CancellablePromise<void> {
    return $Call.ByID(1948429757, id);
}

export function DeleteLauncher(id: string): $CancellablePromise<void> {
    return $Call.ByID(3616476335, id);
}

export function ListActions(): $CancellablePromise<actions$0.EditableCatalog> {
    return $Call.ByID(3468623999);
}

/**
 * ReorderActions persists the catalog order the settings list was dragged
 * into. ids must be the full catalog.
 */
export function ReorderActions(ids: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(1157248834, ids);
}

export function UpdateAction(id: string, a: actions$0.EditableAction): $CancellablePromise<actions$0.EditableAction> {
    return $Call.ByID(1116370519, id, a);
}

export function UpdateLauncher(id: string, l: actions$0.Launcher): $CancellablePromise<actions$0.Launcher> {
    return $Call.ByID(1827295305, id, l);
}
