// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ActionRunService exposes the action run history and each run's log to the
 * run viewer.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../../app/models.js";

export function Get(commandID: number): $CancellablePromise<app$0.ActionRunSummary> {
    return $Call.ByID(1242245656, commandID);
}

/**
 * List returns up to limit runs with id < before, newest first. Zero before
 * starts at the newest.
 */
export function List(before: number, limit: number): $CancellablePromise<app$0.ActionRunSummary[] | null> {
    return $Call.ByID(4240448500, before, limit);
}

/**
 * Log returns up to limit lines after afterID, oldest first.
 */
export function Log(commandID: number, afterID: number, limit: number): $CancellablePromise<app$0.ActionRunLogPage> {
    return $Call.ByID(2960975566, commandID, afterID, limit);
}
