// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../../app/models.js";

export function Clear(): $CancellablePromise<void> {
    return $Call.ByID(760072548);
}

export function SetEnabled(enabled: boolean): $CancellablePromise<void> {
    return $Call.ByID(3958575490, enabled);
}

export function Summary(): $CancellablePromise<app$0.AnalyticsSummary> {
    return $Call.ByID(1317510581);
}
