// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../../app/models.js";

export function Agents(): $CancellablePromise<app$0.DiagnosticsAgents> {
    return $Call.ByID(2264254461);
}

export function Context(req: app$0.DiagnosticsIncident): $CancellablePromise<app$0.DiagnosticsContext> {
    return $Call.ByID(3553274398, req);
}

export function Open(): $CancellablePromise<void> {
    return $Call.ByID(3040026171);
}

/**
 * Prepare saves evidence and renders a command; only the authenticated PTY
 * transport may execute it.
 */
export function Prepare(req: app$0.DiagnosticsIncident): $CancellablePromise<app$0.DiagnosticsContext> {
    return $Call.ByID(3299530178, req);
}

export function Read(q: app$0.DiagnosticsQuery): $CancellablePromise<app$0.DiagnosticsSnapshot> {
    return $Call.ByID(4199937787, q);
}

export function Reveal(source: string): $CancellablePromise<void> {
    return $Call.ByID(4008422698, source);
}

export function Save(req: app$0.DiagnosticsIncident): $CancellablePromise<app$0.DiagnosticsContext> {
    return $Call.ByID(3227055938, req);
}
