// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * FlowsService exposes the flow definitions to the frontend graph editor.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as flow$0 from "../../app/flow/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ClearProfileImage removes a profile's avatar, returning the summary with no
 * image so the rail reverts to the letter chip.
 */
export function ClearProfileImage(id: string): $CancellablePromise<$models.FlowSummary> {
    return $Call.ByID(2421057533, id);
}

export function CreateFlow(name: string): $CancellablePromise<$models.FlowSummary> {
    return $Call.ByID(2154351254, name);
}

export function DeleteFlow(id: string): $CancellablePromise<void> {
    return $Call.ByID(307226601, id);
}

export function GetFlow(id: string): $CancellablePromise<flow$0.Flow> {
    return $Call.ByID(3051733894, id);
}

export function GetLayout(id: string): $CancellablePromise<flow$0.Layout> {
    return $Call.ByID(3540608916, id);
}

export function GetSidebar(id: string): $CancellablePromise<flow$0.SidebarLayout> {
    return $Call.ByID(1482500198, id);
}

/**
 * ListFlows returns one summary per flow file, valid and invalid alike.
 */
export function ListFlows(): $CancellablePromise<$models.FlowSummary[] | null> {
    return $Call.ByID(4227987535);
}

/**
 * MarkImages resolves feed-mark hashes to PNG data URLs. A hash with no stored
 * file is omitted, so the feed falls back to the glyph.
 */
export function MarkImages(hashes: string[] | null): $CancellablePromise<{ [_ in string]?: string } | null> {
    return $Call.ByID(1473392645, hashes);
}

export function RenameFlow(id: string, name: string): $CancellablePromise<$models.FlowSummary> {
    return $Call.ByID(609746912, id, name);
}

export function SaveFlow(f: flow$0.Flow): $CancellablePromise<void> {
    return $Call.ByID(4084221047, f);
}

export function SaveLayout(id: string, layout: flow$0.Layout): $CancellablePromise<void> {
    return $Call.ByID(3465327793, id, layout);
}

export function SaveSidebar(id: string, layout: flow$0.SidebarLayout): $CancellablePromise<void> {
    return $Call.ByID(416453493, id, layout);
}

/**
 * SeedStarterFlow fills an empty profile with the starter graph, fetching as
 * the one connected GitHub account.
 */
export function SeedStarterFlow(id: string): $CancellablePromise<$models.FlowSummary> {
    return $Call.ByID(3561021050, id);
}

export function SetFlowEnabled(id: string, enabled: boolean): $CancellablePromise<$models.FlowSummary> {
    return $Call.ByID(1976616511, id, enabled);
}

/**
 * SetFlowOrder persists the rail order — ids top first, the whole rail in one
 * write.
 */
export function SetFlowOrder(ids: string[] | null): $CancellablePromise<void> {
    return $Call.ByID(2278477322, ids);
}

/**
 * SetMarkImage stores an uploaded feed-mark image (base64, bare or a data: URL)
 * and returns its hash and stored PNG for preview. The hash reaches the flow
 * through the node editor's ordinary graph save.
 */
export function SetMarkImage(data: string): $CancellablePromise<$models.MarkImageView> {
    return $Call.ByID(1556865868, data);
}

/**
 * SetProfileImage sets a profile's sidebar-rail avatar. The frontend sends the
 * picked file as base64 (a bare payload or a data: URL); the core normalizes,
 * stores, and references it. The returned summary carries the stored image so
 * the settings view and rail can preview it without a re-fetch.
 */
export function SetProfileImage(id: string, data: string): $CancellablePromise<$models.FlowSummary> {
    return $Call.ByID(3772373328, id, data);
}
