// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HiveCLIService exposes the `hive` command the app installs to first run and
 * Settings ▸ Hive CLI.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../../app/models.js";

/**
 * SetInstall records whether the app installs the command and applies it.
 */
export function SetInstall(install: boolean): $CancellablePromise<app$0.HiveCLIStatus> {
    return $Call.ByID(2173706364, install);
}

/**
 * Status reports the command, what is at its install path, and what the
 * login shell runs as `hive`.
 */
export function Status(): $CancellablePromise<app$0.HiveCLIStatus> {
    return $Call.ByID(1016022365);
}
