// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../../app/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function FeedChoices(): $CancellablePromise<app$0.MenuBarFeedChoice[] | null> {
    return $Call.ByID(1884332205);
}

export function Limits(): $CancellablePromise<$models.MenuBarLimits> {
    return $Call.ByID(1647189543);
}

export function Pins(): $CancellablePromise<app$0.MenuBarPin[] | null> {
    return $Call.ByID(24259595);
}

export function SetPins(pins: app$0.MenuBarPin[] | null): $CancellablePromise<void> {
    return $Call.ByID(3933907721, pins);
}
