// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../../app/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as stores$0 from "../../app/data/stores/models.js";

export function CreateToken(name: string): $CancellablePromise<app$0.CreatedOrchestratorToken> {
    return $Call.ByID(1626091919, name);
}

export function ListTokens(): $CancellablePromise<stores$0.OrchestratorToken[] | null> {
    return $Call.ByID(4073668580);
}

export function RevokeToken(id: number): $CancellablePromise<void> {
    return $Call.ByID(4174880809, id);
}

export function ServerURL(): $CancellablePromise<string> {
    return $Call.ByID(3289757866);
}
