// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * PipelineService exposes the inbox to the frontend. Every method is a
 * request build plus one call into the core.
 * 
 * The event log is not on this surface. Reading it, committing runs against
 * it, and the replay protocol used to be RPCs because the graph ran in the
 * browser; with the engine in Go they are internal calls, and the
 * decimal-string offset encoding they needed to survive the JavaScript number
 * boundary went with them.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../../app/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as actions$0 from "../../app/actions/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as stores$0 from "../../app/data/stores/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dispatch$0 from "../../app/dispatch/models.js";

export function ActionRun(commandID: number): $CancellablePromise<dispatch$0.ActionRunView> {
    return $Call.ByID(4254816512, commandID);
}

export function ActionRunLocation(commandID: number): $CancellablePromise<app$0.ActionRunLocation> {
    return $Call.ByID(3213990823, commandID);
}

export function ActionViews(itemID: number): $CancellablePromise<actions$0.View[] | null> {
    return $Call.ByID(2080274851, itemID);
}

export function Events(itemID: number, limit: number): $CancellablePromise<stores$0.InboxEvent[] | null> {
    return $Call.ByID(1030841516, itemID, limit);
}

export function Feed(profileID: string, itemID: number): $CancellablePromise<string> {
    return $Call.ByID(477021309, profileID, itemID);
}

export function FeedCounts(profileID: string): $CancellablePromise<stores$0.FeedCount[] | null> {
    return $Call.ByID(3282723837, profileID);
}

export function FindItems(profileID: string, externalID: string): $CancellablePromise<stores$0.InboxItem[] | null> {
    return $Call.ByID(1214368686, profileID, externalID);
}

export function InvokeAction(actionID: string, itemID: number, input: dispatch$0.ActionInvocationInput): $CancellablePromise<dispatch$0.ActionRunView> {
    return $Call.ByID(2590183007, actionID, itemID, input);
}

export function ListArchivedByFeed(profileID: string, feedID: string, limit: number): $CancellablePromise<stores$0.InboxItem[] | null> {
    return $Call.ByID(1861373746, profileID, feedID, limit);
}

export function ListByFeed(profileID: string, feedID: string, limit: number): $CancellablePromise<stores$0.InboxItem[] | null> {
    return $Call.ByID(3232747780, profileID, feedID, limit);
}

export function ListTrash(profileID: string, limit: number): $CancellablePromise<stores$0.InboxItem[] | null> {
    return $Call.ByID(4234041209, profileID, limit);
}

export function MarkRead(profileID: string, feedID: string): $CancellablePromise<number> {
    return $Call.ByID(3433917548, profileID, feedID);
}

export function NewSessionDraft(itemIDs: number[] | null): $CancellablePromise<dispatch$0.SessionDraft> {
    return $Call.ByID(3725626310, itemIDs);
}

export function NodeRuns(flowID: string, limit: number): $CancellablePromise<stores$0.NodeRunRecord[] | null> {
    return $Call.ByID(3784576187, flowID, limit);
}

/**
 * RenderClipboardAction returns one text block rendered across ordered items.
 * The frontend writes it through the native Wails clipboard.
 */
export function RenderClipboardAction(actionID: string, itemIDs: number[] | null, inputs: { [_ in string]?: string } | null): $CancellablePromise<string> {
    return $Call.ByID(1398181267, actionID, itemIDs, inputs);
}

export function SetUnread(itemID: number, revision: number, unread: boolean): $CancellablePromise<stores$0.InboxItem> {
    return $Call.ByID(957270160, itemID, revision, unread);
}

export function ToggleArchived(itemID: number, revision: number): $CancellablePromise<stores$0.InboxItem> {
    return $Call.ByID(650888907, itemID, revision);
}

export function ToggleIgnored(itemID: number, revision: number): $CancellablePromise<stores$0.InboxItem> {
    return $Call.ByID(1486242205, itemID, revision);
}
