// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService exposes user-tunable settings to the frontend. The JSON
 * shapes below are the wire contract; the core deals in Durations and plain
 * maps.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AppearanceSettings(): $CancellablePromise<$models.AppearanceSettings> {
    return $Call.ByID(1460512141);
}

export function EditorSettings(): $CancellablePromise<$models.EditorSettings> {
    return $Call.ByID(3922245462);
}

/**
 * Fonts lists the families installed on this machine, for the app and terminal
 * font pickers. The webview cannot enumerate them itself — queryLocalFonts is
 * Chromium-only and macOS runs on WKWebView.
 * 
 * The scan is cached for the process, so a font installed while the app runs
 * appears on the next launch.
 */
export function Fonts(): $CancellablePromise<$models.InstalledFonts> {
    return $Call.ByID(2605967336);
}

export function GithubSettings(): $CancellablePromise<$models.GithubSettings> {
    return $Call.ByID(2083049132);
}

export function KeybindingSettings(): $CancellablePromise<$models.KeybindingSettings> {
    return $Call.ByID(3907833795);
}

export function NotificationSettings(): $CancellablePromise<$models.NotificationSettings> {
    return $Call.ByID(2074036148);
}

export function OnboardingSettings(): $CancellablePromise<$models.OnboardingSettings> {
    return $Call.ByID(3457698538);
}

export function SetCanvasFontSize(size: string): $CancellablePromise<void> {
    return $Call.ByID(1474669462, size);
}

export function SetCanvasLineSpacing(spacing: string): $CancellablePromise<void> {
    return $Call.ByID(3911754413, spacing);
}

/**
 * SetEditor persists the editor command; empty clears it.
 */
export function SetEditor(command: string): $CancellablePromise<void> {
    return $Call.ByID(1975978635, command);
}

export function SetFontFamily(family: string): $CancellablePromise<void> {
    return $Call.ByID(3115539787, family);
}

/**
 * SetGithubSettings converts the wire's seconds to a duration and hands it to
 * the core, which owns the floor and the live apply. A negative or absurd
 * value is caught here because it cannot be represented as a duration at all.
 */
export function SetGithubSettings($in: $models.GithubSettings): $CancellablePromise<void> {
    return $Call.ByID(2566575980, $in);
}

export function SetKeybindingSettings($in: $models.KeybindingSettings): $CancellablePromise<void> {
    return $Call.ByID(1115516291, $in);
}

export function SetMonoFontFamily(family: string): $CancellablePromise<void> {
    return $Call.ByID(3715226776, family);
}

export function SetNotificationSettings($in: $models.NotificationSettings): $CancellablePromise<void> {
    return $Call.ByID(1777849716, $in);
}

export function SetOnboardingCompleted(): $CancellablePromise<void> {
    return $Call.ByID(1041406544);
}

export function SetTerminalFontFamily(family: string): $CancellablePromise<void> {
    return $Call.ByID(2172269859, family);
}

export function SetTerminalFontSize(px: number): $CancellablePromise<void> {
    return $Call.ByID(4272872546, px);
}

export function SetTerminalFontWeights(weight: number, weightBold: number): $CancellablePromise<void> {
    return $Call.ByID(2641607236, weight, weightBold);
}

export function SetTerminalLetterSpacing(spacing: number): $CancellablePromise<void> {
    return $Call.ByID(653676947, spacing);
}

export function SetTerminalLineHeight(lineHeight: number): $CancellablePromise<void> {
    return $Call.ByID(375201723, lineHeight);
}

export function SetTerminalPoolSize(size: number): $CancellablePromise<void> {
    return $Call.ByID(3334784753, size);
}

export function SetTerminalShowStatusBar(show: boolean): $CancellablePromise<void> {
    return $Call.ByID(1260520894, show);
}

export function SetTerminalShowWindows(show: boolean): $CancellablePromise<void> {
    return $Call.ByID(860849420, show);
}

/**
 * The appearance setters are per-field so the theme picker and the font pickers
 * cannot clobber each other's persisted value.
 */
export function SetTheme(theme: string): $CancellablePromise<void> {
    return $Call.ByID(4185056443, theme);
}
