// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TasksService exposes the desktop's tasks view over Hive's hc issue tracker.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as dispatch$0 from "../../app/dispatch/models.js";

export function DeleteTask(id: string): $CancellablePromise<void> {
    return $Call.ByID(498612603, id);
}

export function ListTasks(repoKey: string): $CancellablePromise<dispatch$0.TaskItem[] | null> {
    return $Call.ByID(480176773, repoKey);
}

export function PruneTasks(olderThanDays: number, repoKey: string, dryRun: boolean): $CancellablePromise<number> {
    return $Call.ByID(2693247331, olderThanDays, repoKey, dryRun);
}

export function SetTaskStatus(id: string, status: string): $CancellablePromise<void> {
    return $Call.ByID(2116066304, id, status);
}

export function TaskDetail(id: string): $CancellablePromise<dispatch$0.TaskDetail> {
    return $Call.ByID(2471965633, id);
}

export function TaskRepoKeys(): $CancellablePromise<string[] | null> {
    return $Call.ByID(394618344);
}
