// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WebhookService exposes the local webhook listener's endpoint info, its
 * user-tunable settings, and each sources.webhook node's last captured
 * delivery to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Capture returns the last request body POSTed to a sources.webhook node, with
 * the non-blocking feed-shape verdict the editor surfaces.
 */
export function Capture(flowID: string, nodeID: string): $CancellablePromise<$models.WebhookCaptureView> {
    return $Call.ByID(3638162508, flowID, nodeID);
}

/**
 * GeneratePort returns a fresh random port without persisting it: the
 * settings pane offers it as a candidate, and saving is what commits it.
 */
export function GeneratePort(): $CancellablePromise<number> {
    return $Call.ByID(445936466);
}

/**
 * Info returns the listener's state and the base URL sources.webhook paths are
 * served under (endpoint URL = BaseURL + node path).
 */
export function Info(): $CancellablePromise<$models.WebhookInfo> {
    return $Call.ByID(1555782830);
}

/**
 * SetSettings persists the enable toggle and port.
 */
export function SetSettings(next: $models.WebhookSettings): $CancellablePromise<void> {
    return $Call.ByID(1271970915, next);
}

export function Settings(): $CancellablePromise<$models.WebhookSettings> {
    return $Call.ByID(1421124283);
}
