package initcmd

import (
	"bytes"
	"os"
	"path/filepath"
	"text/template"
)

// ConfigOptions controls what gets generated.
type ConfigOptions struct {
	RepoDirs   []string
	Tmux       bool
	ScriptPath string // path to hive.sh, empty if not installed
}

// DefaultRepoDirs returns the default repository directories.
func DefaultRepoDirs() []string {
	home, _ := os.UserHomeDir()
	return []string{filepath.Join(home, "code")}
}

// configTemplate defines the generated config structure.
// Using a template gives us precise control over YAML formatting
// and avoids duplicating the config struct definitions.
var configTemplate = template.Must(template.New("config").Parse(`# Hive configuration - generated by 'hive init'
version: "0.2.3"

repo_dirs:
{{- range .RepoDirs }}
  - {{ . }}
{{- end }}

integrations:
  terminal:
    enabled: [{{ if .Tmux }}tmux{{ end }}]
{{- if .Tmux }}
    poll_interval: 500ms
{{- end }}

commands:
{{- if .ScriptPath }}
  spawn:
    - {{ .ScriptPath }} "{{ "{{" }} .Name {{ "}}" }}" "{{ "{{" }} .Path {{ "}}" }}"
  batch_spawn:
    - {{ .ScriptPath }} -b "{{ "{{" }} .Name {{ "}}" }}" "{{ "{{" }} .Path {{ "}}" }}" "{{ "{{" }} .Prompt {{ "}}" }}"
{{- else }}
  spawn: []
  batch_spawn: []
{{- end }}
  recycle:
    - git fetch origin
    - git checkout {{ "{{" }} .DefaultBranch {{ "}}" }}
    - git reset --hard origin/{{ "{{" }} .DefaultBranch {{ "}}" }}
    - git clean -fd

rules:
  - pattern: ""
    max_recycled: 3
    commands:
      - hive ctx init
{{- if .ScriptPath }}

keybindings:
  enter:
    help: open/create tmux
    sh: {{ .ScriptPath }} "{{ "{{" }} .Name {{ "}}" }}" "{{ "{{" }} .Path {{ "}}" }}"
    exit: $HIVE_POPUP
    silent: true
  ctrl+d:
    help: kill session
    sh: tmux kill-session -t "{{ "{{" }} .Name {{ "}}" }}" 2>/dev/null || true
{{- end }}
`))

// GenerateConfig creates config content based on the provided options.
func GenerateConfig(opts ConfigOptions) ([]byte, error) {
	var buf bytes.Buffer
	if err := configTemplate.Execute(&buf, opts); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// WriteConfig writes the generated config to the specified path.
func WriteConfig(opts ConfigOptions, path string) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}

	content, err := GenerateConfig(opts)
	if err != nil {
		return err
	}

	return os.WriteFile(path, content, 0o644)
}
