package initcmd

import (
	"os"
	"path/filepath"
	"time"

	"gopkg.in/yaml.v3"
)

// GeneratedConfig represents the YAML config structure for generation.
// Uses separate structs to control YAML output formatting.
type GeneratedConfig struct {
	Version      string                   `yaml:"version"`
	RepoDirs     []string                 `yaml:"repo_dirs"`
	Integrations GeneratedIntegrations    `yaml:"integrations"`
	Commands     GeneratedCommands        `yaml:"commands"`
	Rules        []GeneratedRule          `yaml:"rules"`
	Keybindings  map[string]GeneratedKeyb `yaml:"keybindings,omitempty"`
}

// GeneratedIntegrations holds terminal integration config.
type GeneratedIntegrations struct {
	Terminal GeneratedTerminal `yaml:"terminal"`
}

// GeneratedTerminal holds terminal multiplexer config.
type GeneratedTerminal struct {
	Enabled      []string `yaml:"enabled"`
	PollInterval string   `yaml:"poll_interval,omitempty"`
}

// GeneratedCommands holds spawn and recycle commands.
type GeneratedCommands struct {
	Spawn      []string `yaml:"spawn"`
	BatchSpawn []string `yaml:"batch_spawn"`
	Recycle    []string `yaml:"recycle"`
}

// GeneratedRule defines a session rule.
type GeneratedRule struct {
	Pattern     string   `yaml:"pattern"`
	MaxRecycled int      `yaml:"max_recycled"`
	Commands    []string `yaml:"commands"`
}

// GeneratedKeyb defines a keybinding.
type GeneratedKeyb struct {
	Help   string `yaml:"help"`
	Sh     string `yaml:"sh"`
	Exit   string `yaml:"exit,omitempty"`
	Silent bool   `yaml:"silent,omitempty"`
}

// ConfigOptions controls what gets generated.
type ConfigOptions struct {
	RepoDirs    []string
	InstallTmux bool
	ScriptPath  string // path to hive.sh, empty if not installed
}

// DefaultRepoDirs returns the default repository directories.
func DefaultRepoDirs() []string {
	home, _ := os.UserHomeDir()
	return []string{filepath.Join(home, "code")}
}

// GenerateConfig creates a config based on the provided options.
func GenerateConfig(opts ConfigOptions) GeneratedConfig {
	cfg := GeneratedConfig{
		Version:  "0.2.3",
		RepoDirs: opts.RepoDirs,
		Commands: GeneratedCommands{
			Spawn:      []string{},
			BatchSpawn: []string{},
			Recycle: []string{
				"git fetch origin",
				"git checkout {{ .DefaultBranch }}",
				"git reset --hard origin/{{ .DefaultBranch }}",
				"git clean -fd",
			},
		},
		Rules: []GeneratedRule{
			{
				Pattern:     "",
				MaxRecycled: 3,
				Commands:    []string{"hive ctx init"},
			},
		},
	}

	if opts.InstallTmux && opts.ScriptPath != "" {
		cfg.Integrations = GeneratedIntegrations{
			Terminal: GeneratedTerminal{
				Enabled:      []string{"tmux"},
				PollInterval: (500 * time.Millisecond).String(),
			},
		}
		cfg.Commands.Spawn = []string{
			opts.ScriptPath + ` "{{ .Name }}" "{{ .Path }}"`,
		}
		cfg.Commands.BatchSpawn = []string{
			opts.ScriptPath + ` -b "{{ .Name }}" "{{ .Path }}" "{{ .Prompt }}"`,
		}
		cfg.Keybindings = map[string]GeneratedKeyb{
			"enter": {
				Help:   "open/create tmux",
				Sh:     opts.ScriptPath + ` "{{ .Name }}" "{{ .Path }}"`,
				Exit:   "$HIVE_POPUP",
				Silent: true,
			},
			"ctrl+d": {
				Help: "kill session",
				Sh:   `tmux kill-session -t "{{ .Name }}" 2>/dev/null || true`,
			},
		}
	} else {
		cfg.Integrations = GeneratedIntegrations{
			Terminal: GeneratedTerminal{
				Enabled: []string{},
			},
		}
	}

	return cfg
}

// WriteConfig writes the generated config to the specified path.
func WriteConfig(cfg GeneratedConfig, path string) error {
	// Ensure parent directory exists
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}

	data, err := yaml.Marshal(cfg)
	if err != nil {
		return err
	}

	header := "# Hive configuration - generated by 'hive init'\n"
	return os.WriteFile(path, append([]byte(header), data...), 0o644)
}
