// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package todo

import (
	"errors"
	"fmt"
)

const (
	// CategoryReview is a Category of type review.
	CategoryReview Category = "review"
	// CategoryCodeReview is a Category of type code-review.
	CategoryCodeReview Category = "code-review"
	// CategoryDone is a Category of type done.
	CategoryDone Category = "done"
)

var ErrInvalidCategory = errors.New("not a valid Category")

// String implements the Stringer interface.
func (x Category) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Category) IsValid() bool {
	_, err := ParseCategory(string(x))
	return err == nil
}

var _CategoryValue = map[string]Category{
	"review":      CategoryReview,
	"code-review": CategoryCodeReview,
	"done":        CategoryDone,
}

// ParseCategory attempts to convert a string to a Category.
func ParseCategory(name string) (Category, error) {
	if x, ok := _CategoryValue[name]; ok {
		return x, nil
	}
	return Category(""), fmt.Errorf("%s is %w", name, ErrInvalidCategory)
}

const (
	// SourceAgent is a Source of type agent.
	SourceAgent Source = "agent"
	// SourceHuman is a Source of type human.
	SourceHuman Source = "human"
	// SourceSystem is a Source of type system.
	SourceSystem Source = "system"
)

var ErrInvalidSource = errors.New("not a valid Source")

// String implements the Stringer interface.
func (x Source) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Source) IsValid() bool {
	_, err := ParseSource(string(x))
	return err == nil
}

var _SourceValue = map[string]Source{
	"agent":  SourceAgent,
	"human":  SourceHuman,
	"system": SourceSystem,
}

// ParseSource attempts to convert a string to a Source.
func ParseSource(name string) (Source, error) {
	if x, ok := _SourceValue[name]; ok {
		return x, nil
	}
	return Source(""), fmt.Errorf("%s is %w", name, ErrInvalidSource)
}

const (
	// StatusPending is a Status of type pending.
	StatusPending Status = "pending"
	// StatusAcknowledged is a Status of type acknowledged.
	StatusAcknowledged Status = "acknowledged"
	// StatusCompleted is a Status of type completed.
	StatusCompleted Status = "completed"
	// StatusDismissed is a Status of type dismissed.
	StatusDismissed Status = "dismissed"
)

var ErrInvalidStatus = errors.New("not a valid Status")

// String implements the Stringer interface.
func (x Status) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Status) IsValid() bool {
	_, err := ParseStatus(string(x))
	return err == nil
}

var _StatusValue = map[string]Status{
	"pending":      StatusPending,
	"acknowledged": StatusAcknowledged,
	"completed":    StatusCompleted,
	"dismissed":    StatusDismissed,
}

// ParseStatus attempts to convert a string to a Status.
func ParseStatus(name string) (Status, error) {
	if x, ok := _StatusValue[name]; ok {
		return x, nil
	}
	return Status(""), fmt.Errorf("%s is %w", name, ErrInvalidStatus)
}
