// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package review

import (
	"fmt"
	"strings"
)

const (
	// FinalizationActionNone is a FinalizationAction of type none.
	FinalizationActionNone FinalizationAction = "none"
	// FinalizationActionClipboard is a FinalizationAction of type clipboard.
	FinalizationActionClipboard FinalizationAction = "clipboard"
	// FinalizationActionSendToAgent is a FinalizationAction of type send_to_agent.
	FinalizationActionSendToAgent FinalizationAction = "send_to_agent"
)

var ErrInvalidFinalizationAction = fmt.Errorf("not a valid FinalizationAction, try [%s]", strings.Join(_FinalizationActionNames, ", "))

var _FinalizationActionNames = []string{
	string(FinalizationActionNone),
	string(FinalizationActionClipboard),
	string(FinalizationActionSendToAgent),
}

// FinalizationActionNames returns a list of possible string values of FinalizationAction.
func FinalizationActionNames() []string {
	tmp := make([]string, len(_FinalizationActionNames))
	copy(tmp, _FinalizationActionNames)
	return tmp
}

// String implements the Stringer interface.
func (x FinalizationAction) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x FinalizationAction) IsValid() bool {
	_, err := ParseFinalizationAction(string(x))
	return err == nil
}

var _FinalizationActionValue = map[string]FinalizationAction{
	"none":          FinalizationActionNone,
	"clipboard":     FinalizationActionClipboard,
	"send_to_agent": FinalizationActionSendToAgent,
}

// ParseFinalizationAction attempts to convert a string to a FinalizationAction.
func ParseFinalizationAction(name string) (FinalizationAction, error) {
	if x, ok := _FinalizationActionValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _FinalizationActionValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return FinalizationAction(""), fmt.Errorf("%s is %w", name, ErrInvalidFinalizationAction)
}

// MarshalText implements the text marshaller method.
func (x FinalizationAction) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *FinalizationAction) UnmarshalText(text []byte) error {
	tmp, err := ParseFinalizationAction(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *FinalizationAction) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
