// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package review

import (
	"fmt"
	"strings"
)

const (
	// DocumentTypePlan is a DocumentType of type plan.
	DocumentTypePlan DocumentType = "plan"
	// DocumentTypeResearch is a DocumentType of type research.
	DocumentTypeResearch DocumentType = "research"
	// DocumentTypeContext is a DocumentType of type context.
	DocumentTypeContext DocumentType = "context"
	// DocumentTypeOther is a DocumentType of type other.
	DocumentTypeOther DocumentType = "other"
)

var ErrInvalidDocumentType = fmt.Errorf("not a valid DocumentType, try [%s]", strings.Join(_DocumentTypeNames, ", "))

var _DocumentTypeNames = []string{
	string(DocumentTypePlan),
	string(DocumentTypeResearch),
	string(DocumentTypeContext),
	string(DocumentTypeOther),
}

// DocumentTypeNames returns a list of possible string values of DocumentType.
func DocumentTypeNames() []string {
	tmp := make([]string, len(_DocumentTypeNames))
	copy(tmp, _DocumentTypeNames)
	return tmp
}

// String implements the Stringer interface.
func (x DocumentType) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x DocumentType) IsValid() bool {
	_, err := ParseDocumentType(string(x))
	return err == nil
}

var _DocumentTypeValue = map[string]DocumentType{
	"plan":     DocumentTypePlan,
	"research": DocumentTypeResearch,
	"context":  DocumentTypeContext,
	"other":    DocumentTypeOther,
}

// ParseDocumentType attempts to convert a string to a DocumentType.
func ParseDocumentType(name string) (DocumentType, error) {
	if x, ok := _DocumentTypeValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _DocumentTypeValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return DocumentType(""), fmt.Errorf("%s is %w", name, ErrInvalidDocumentType)
}

// MarshalText implements the text marshaller method.
func (x DocumentType) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *DocumentType) UnmarshalText(text []byte) error {
	tmp, err := ParseDocumentType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *DocumentType) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
