// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Entry {
    "id": string;
    "time": string;
    "source": string;
    "level": string;
    "message": string;
    "fields": { [_ in string]?: string } | null;
    "raw": string;
    "truncated": boolean;
}

export interface Source {
    "id": string;
    "path": string;
    "updatedAt": string;
    "error": string;
    "truncated": boolean;
}
