// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Message struct {
	ID        string         `json:"id"`
	Topic     string         `json:"topic"`
	Payload   string         `json:"payload"`
	Sender    sql.NullString `json:"sender"`
	SessionID sql.NullString `json:"session_id"`
	CreatedAt int64          `json:"created_at"`
}

type SchemaVersion struct {
	Version int64 `json:"version"`
}

type Session struct {
	ID            string         `json:"id"`
	Name          string         `json:"name"`
	Slug          string         `json:"slug"`
	Path          string         `json:"path"`
	Remote        string         `json:"remote"`
	State         string         `json:"state"`
	Metadata      sql.NullString `json:"metadata"`
	CreatedAt     int64          `json:"created_at"`
	UpdatedAt     int64          `json:"updated_at"`
	LastInboxRead sql.NullInt64  `json:"last_inbox_read"`
}

type Topic struct {
	Name      string      `json:"name"`
	UpdatedAt interface{} `json:"updated_at"`
}
