// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: timers.sql

package db

import (
	"context"
	"database/sql"
	"strings"

	"github.com/colonyops/hive/internal/core/timer"
)

const activeTimersAll = `-- name: ActiveTimersAll :many
SELECT id, session_id, tmux_target, prompt, duration_ns, fires_at, pid, status, created_at, fired_at FROM timers WHERE status = 'active'
ORDER BY fires_at ASC
`

func (q *Queries) ActiveTimersAll(ctx context.Context) ([]Timer, error) {
	rows, err := q.db.QueryContext(ctx, activeTimersAll)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Timer{}
	for rows.Next() {
		var i Timer
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TmuxTarget,
			&i.Prompt,
			&i.DurationNs,
			&i.FiresAt,
			&i.Pid,
			&i.Status,
			&i.CreatedAt,
			&i.FiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const activeTimersForSession = `-- name: ActiveTimersForSession :many
SELECT id, session_id, tmux_target, prompt, duration_ns, fires_at, pid, status, created_at, fired_at FROM timers WHERE session_id = ? AND status = 'active'
ORDER BY fires_at ASC
`

func (q *Queries) ActiveTimersForSession(ctx context.Context, sessionID string) ([]Timer, error) {
	rows, err := q.db.QueryContext(ctx, activeTimersForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Timer{}
	for rows.Next() {
		var i Timer
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.TmuxTarget,
			&i.Prompt,
			&i.DurationNs,
			&i.FiresAt,
			&i.Pid,
			&i.Status,
			&i.CreatedAt,
			&i.FiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteTimer = `-- name: DeleteTimer :exec
DELETE FROM timers WHERE id = ?
`

func (q *Queries) DeleteTimer(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTimer, id)
	return err
}

const getTimer = `-- name: GetTimer :one
SELECT id, session_id, tmux_target, prompt, duration_ns, fires_at, pid, status, created_at, fired_at FROM timers WHERE id = ?
`

func (q *Queries) GetTimer(ctx context.Context, id string) (Timer, error) {
	row := q.db.QueryRowContext(ctx, getTimer, id)
	var i Timer
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TmuxTarget,
		&i.Prompt,
		&i.DurationNs,
		&i.FiresAt,
		&i.Pid,
		&i.Status,
		&i.CreatedAt,
		&i.FiredAt,
	)
	return i, err
}

const insertTimer = `-- name: InsertTimer :exec
INSERT INTO timers (
    id, session_id, tmux_target, prompt, duration_ns,
    fires_at, pid, status, created_at, fired_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertTimerParams struct {
	ID         string        `json:"id"`
	SessionID  string        `json:"session_id"`
	TmuxTarget string        `json:"tmux_target"`
	Prompt     string        `json:"prompt"`
	DurationNs int64         `json:"duration_ns"`
	FiresAt    int64         `json:"fires_at"`
	Pid        sql.NullInt64 `json:"pid"`
	Status     timer.Status  `json:"status"`
	CreatedAt  int64         `json:"created_at"`
	FiredAt    sql.NullInt64 `json:"fired_at"`
}

func (q *Queries) InsertTimer(ctx context.Context, arg InsertTimerParams) error {
	_, err := q.db.ExecContext(ctx, insertTimer,
		arg.ID,
		arg.SessionID,
		arg.TmuxTarget,
		arg.Prompt,
		arg.DurationNs,
		arg.FiresAt,
		arg.Pid,
		arg.Status,
		arg.CreatedAt,
		arg.FiredAt,
	)
	return err
}

const markInactiveTimersAll = `-- name: MarkInactiveTimersAll :exec
UPDATE timers SET status = 'orphaned'
WHERE status = 'active'
  AND pid IS NOT NULL
  AND id IN (/*SLICE:ids*/?)
`

func (q *Queries) MarkInactiveTimersAll(ctx context.Context, ids []string) error {
	query := markInactiveTimersAll
	var queryParams []interface{}
	if len(ids) > 0 {
		for _, v := range ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const markInactiveTimersForSession = `-- name: MarkInactiveTimersForSession :exec
UPDATE timers SET status = 'orphaned'
WHERE session_id = ?
  AND status = 'active'
  AND pid IS NOT NULL
  AND id IN (/*SLICE:ids*/?)
`

type MarkInactiveTimersForSessionParams struct {
	SessionID string   `json:"session_id"`
	Ids       []string `json:"ids"`
}

func (q *Queries) MarkInactiveTimersForSession(ctx context.Context, arg MarkInactiveTimersForSessionParams) error {
	query := markInactiveTimersForSession
	var queryParams []interface{}
	queryParams = append(queryParams, arg.SessionID)
	if len(arg.Ids) > 0 {
		for _, v := range arg.Ids {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:ids*/?", strings.Repeat(",?", len(arg.Ids))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:ids*/?", "NULL", 1)
	}
	_, err := q.db.ExecContext(ctx, query, queryParams...)
	return err
}

const markTimerFailed = `-- name: MarkTimerFailed :exec
UPDATE timers SET status = 'failed', fired_at = ? WHERE id = ?
`

type MarkTimerFailedParams struct {
	FiredAt sql.NullInt64 `json:"fired_at"`
	ID      string        `json:"id"`
}

func (q *Queries) MarkTimerFailed(ctx context.Context, arg MarkTimerFailedParams) error {
	_, err := q.db.ExecContext(ctx, markTimerFailed, arg.FiredAt, arg.ID)
	return err
}

const markTimerFired = `-- name: MarkTimerFired :exec
UPDATE timers SET status = 'fired', fired_at = ? WHERE id = ?
`

type MarkTimerFiredParams struct {
	FiredAt sql.NullInt64 `json:"fired_at"`
	ID      string        `json:"id"`
}

func (q *Queries) MarkTimerFired(ctx context.Context, arg MarkTimerFiredParams) error {
	_, err := q.db.ExecContext(ctx, markTimerFired, arg.FiredAt, arg.ID)
	return err
}

const updateTimerPID = `-- name: UpdateTimerPID :exec
UPDATE timers SET pid = ? WHERE id = ?
`

type UpdateTimerPIDParams struct {
	Pid sql.NullInt64 `json:"pid"`
	ID  string        `json:"id"`
}

func (q *Queries) UpdateTimerPID(ctx context.Context, arg UpdateTimerPIDParams) error {
	_, err := q.db.ExecContext(ctx, updateTimerPID, arg.Pid, arg.ID)
	return err
}
