// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package action

import (
	"fmt"
	"strings"
)

const (
	// TypeNone is a Type of type None.
	TypeNone Type = "None"
	// TypeRecycle is a Type of type Recycle.
	TypeRecycle Type = "Recycle"
	// TypeDelete is a Type of type Delete.
	TypeDelete Type = "Delete"
	// TypeShell is a Type of type Shell.
	TypeShell Type = "Shell"
	// TypeTmuxOpen is a Type of type TmuxOpen.
	TypeTmuxOpen Type = "TmuxOpen"
	// TypeTmuxStart is a Type of type TmuxStart.
	TypeTmuxStart Type = "TmuxStart"
	// TypeFilterAll is a Type of type FilterAll.
	TypeFilterAll Type = "FilterAll"
	// TypeFilterActive is a Type of type FilterActive.
	TypeFilterActive Type = "FilterActive"
	// TypeFilterApproval is a Type of type FilterApproval.
	TypeFilterApproval Type = "FilterApproval"
	// TypeFilterReady is a Type of type FilterReady.
	TypeFilterReady Type = "FilterReady"
	// TypeDocReview is a Type of type DocReview.
	TypeDocReview Type = "DocReview"
	// TypeNewSession is a Type of type NewSession.
	TypeNewSession Type = "NewSession"
	// TypeSetTheme is a Type of type SetTheme.
	TypeSetTheme Type = "SetTheme"
	// TypeMessages is a Type of type Messages.
	TypeMessages Type = "Messages"
	// TypeRenameSession is a Type of type RenameSession.
	TypeRenameSession Type = "RenameSession"
	// TypeNextActive is a Type of type NextActive.
	TypeNextActive Type = "NextActive"
	// TypePrevActive is a Type of type PrevActive.
	TypePrevActive Type = "PrevActive"
	// TypeDeleteRecycledBatch is a Type of type DeleteRecycledBatch.
	TypeDeleteRecycledBatch Type = "DeleteRecycledBatch"
	// TypeSpawnWindows is a Type of type SpawnWindows.
	TypeSpawnWindows Type = "SpawnWindows"
	// TypeHiveInfo is a Type of type HiveInfo.
	TypeHiveInfo Type = "HiveInfo"
	// TypeHiveDoctor is a Type of type HiveDoctor.
	TypeHiveDoctor Type = "HiveDoctor"
)

var ErrInvalidType = fmt.Errorf("not a valid Type, try [%s]", strings.Join(_TypeNames, ", "))

var _TypeNames = []string{
	string(TypeNone),
	string(TypeRecycle),
	string(TypeDelete),
	string(TypeShell),
	string(TypeTmuxOpen),
	string(TypeTmuxStart),
	string(TypeFilterAll),
	string(TypeFilterActive),
	string(TypeFilterApproval),
	string(TypeFilterReady),
	string(TypeDocReview),
	string(TypeNewSession),
	string(TypeSetTheme),
	string(TypeMessages),
	string(TypeRenameSession),
	string(TypeNextActive),
	string(TypePrevActive),
	string(TypeDeleteRecycledBatch),
	string(TypeSpawnWindows),
	string(TypeHiveInfo),
	string(TypeHiveDoctor),
}

// TypeNames returns a list of possible string values of Type.
func TypeNames() []string {
	tmp := make([]string, len(_TypeNames))
	copy(tmp, _TypeNames)
	return tmp
}

// String implements the Stringer interface.
func (x Type) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Type) IsValid() bool {
	_, err := ParseType(string(x))
	return err == nil
}

var _TypeValue = map[string]Type{
	"None":                TypeNone,
	"none":                TypeNone,
	"Recycle":             TypeRecycle,
	"recycle":             TypeRecycle,
	"Delete":              TypeDelete,
	"delete":              TypeDelete,
	"Shell":               TypeShell,
	"shell":               TypeShell,
	"TmuxOpen":            TypeTmuxOpen,
	"tmuxopen":            TypeTmuxOpen,
	"TmuxStart":           TypeTmuxStart,
	"tmuxstart":           TypeTmuxStart,
	"FilterAll":           TypeFilterAll,
	"filterall":           TypeFilterAll,
	"FilterActive":        TypeFilterActive,
	"filteractive":        TypeFilterActive,
	"FilterApproval":      TypeFilterApproval,
	"filterapproval":      TypeFilterApproval,
	"FilterReady":         TypeFilterReady,
	"filterready":         TypeFilterReady,
	"DocReview":           TypeDocReview,
	"docreview":           TypeDocReview,
	"NewSession":          TypeNewSession,
	"newsession":          TypeNewSession,
	"SetTheme":            TypeSetTheme,
	"settheme":            TypeSetTheme,
	"Messages":            TypeMessages,
	"messages":            TypeMessages,
	"RenameSession":       TypeRenameSession,
	"renamesession":       TypeRenameSession,
	"NextActive":          TypeNextActive,
	"nextactive":          TypeNextActive,
	"PrevActive":          TypePrevActive,
	"prevactive":          TypePrevActive,
	"DeleteRecycledBatch": TypeDeleteRecycledBatch,
	"deleterecycledbatch": TypeDeleteRecycledBatch,
	"SpawnWindows":        TypeSpawnWindows,
	"spawnwindows":        TypeSpawnWindows,
	"HiveInfo":            TypeHiveInfo,
	"hiveinfo":            TypeHiveInfo,
	"HiveDoctor":          TypeHiveDoctor,
	"hivedoctor":          TypeHiveDoctor,
}

// ParseType attempts to convert a string to a Type.
func ParseType(name string) (Type, error) {
	if x, ok := _TypeValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _TypeValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return Type(""), fmt.Errorf("%s is %w", name, ErrInvalidType)
}

// MarshalText implements the text marshaller method.
func (x Type) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Type) UnmarshalText(text []byte) error {
	tmp, err := ParseType(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *Type) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
