// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package action

import (
	"errors"
	"fmt"
)

const (
	// TypeNone is a Type of type None.
	TypeNone Type = "None"
	// TypeRecycle is a Type of type Recycle.
	TypeRecycle Type = "Recycle"
	// TypeDelete is a Type of type Delete.
	TypeDelete Type = "Delete"
	// TypeShell is a Type of type Shell.
	TypeShell Type = "Shell"
	// TypeTmuxOpen is a Type of type TmuxOpen.
	TypeTmuxOpen Type = "TmuxOpen"
	// TypeTmuxStart is a Type of type TmuxStart.
	TypeTmuxStart Type = "TmuxStart"
	// TypeFilterAll is a Type of type FilterAll.
	TypeFilterAll Type = "FilterAll"
	// TypeFilterActive is a Type of type FilterActive.
	TypeFilterActive Type = "FilterActive"
	// TypeFilterApproval is a Type of type FilterApproval.
	TypeFilterApproval Type = "FilterApproval"
	// TypeFilterReady is a Type of type FilterReady.
	TypeFilterReady Type = "FilterReady"
	// TypeDocReview is a Type of type DocReview.
	TypeDocReview Type = "DocReview"
	// TypeNewSession is a Type of type NewSession.
	TypeNewSession Type = "NewSession"
	// TypeSetTheme is a Type of type SetTheme.
	TypeSetTheme Type = "SetTheme"
	// TypeNotifications is a Type of type Notifications.
	TypeNotifications Type = "Notifications"
	// TypeRenameSession is a Type of type RenameSession.
	TypeRenameSession Type = "RenameSession"
	// TypeNextActive is a Type of type NextActive.
	TypeNextActive Type = "NextActive"
	// TypePrevActive is a Type of type PrevActive.
	TypePrevActive Type = "PrevActive"
	// TypeDeleteRecycledBatch is a Type of type DeleteRecycledBatch.
	TypeDeleteRecycledBatch Type = "DeleteRecycledBatch"
	// TypeSpawnWindows is a Type of type SpawnWindows.
	TypeSpawnWindows Type = "SpawnWindows"
	// TypeHiveInfo is a Type of type HiveInfo.
	TypeHiveInfo Type = "HiveInfo"
	// TypeHiveDoctor is a Type of type HiveDoctor.
	TypeHiveDoctor Type = "HiveDoctor"
	// TypeGroupSet is a Type of type GroupSet.
	TypeGroupSet Type = "GroupSet"
	// TypeGroupToggle is a Type of type GroupToggle.
	TypeGroupToggle Type = "GroupToggle"
	// TypeTodos is a Type of type Todos.
	TypeTodos Type = "Todos"
)

var ErrInvalidType = errors.New("not a valid Type")

// String implements the Stringer interface.
func (x Type) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Type) IsValid() bool {
	_, err := ParseType(string(x))
	return err == nil
}

var _TypeValue = map[string]Type{
	"None":                TypeNone,
	"Recycle":             TypeRecycle,
	"Delete":              TypeDelete,
	"Shell":               TypeShell,
	"TmuxOpen":            TypeTmuxOpen,
	"TmuxStart":           TypeTmuxStart,
	"FilterAll":           TypeFilterAll,
	"FilterActive":        TypeFilterActive,
	"FilterApproval":      TypeFilterApproval,
	"FilterReady":         TypeFilterReady,
	"DocReview":           TypeDocReview,
	"NewSession":          TypeNewSession,
	"SetTheme":            TypeSetTheme,
	"Notifications":       TypeNotifications,
	"RenameSession":       TypeRenameSession,
	"NextActive":          TypeNextActive,
	"PrevActive":          TypePrevActive,
	"DeleteRecycledBatch": TypeDeleteRecycledBatch,
	"SpawnWindows":        TypeSpawnWindows,
	"HiveInfo":            TypeHiveInfo,
	"HiveDoctor":          TypeHiveDoctor,
	"GroupSet":            TypeGroupSet,
	"GroupToggle":         TypeGroupToggle,
	"Todos":               TypeTodos,
}

// ParseType attempts to convert a string to a Type.
func ParseType(name string) (Type, error) {
	if x, ok := _TypeValue[name]; ok {
		return x, nil
	}
	return Type(""), fmt.Errorf("%s is %w", name, ErrInvalidType)
}
