// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * View is the complete action contract exposed to the desktop frontend. It
 * deliberately excludes executable configuration: the frontend can present
 * and identify an action, but execution always resolves its current
 * definition from ActionStore.
 */
export interface View {
    "id": string;
    "label": string;
    "type": string;
    "autoApply": boolean;
}
