name: pr

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-tests:
    name: "Go Build/Test"
    uses: ./.github/workflows/partial-tests.yml

  integration-tests:
    name: "Integration Tests"
    uses: ./.github/workflows/partial-integration-tests.yml
