// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.4

// Built By: go install

package prompt

import (
	"fmt"
	"strings"
)

const (
	// AgentStateActive is a AgentState of type active.
	AgentStateActive AgentState = "active"
	// AgentStateApproval is a AgentState of type approval.
	AgentStateApproval AgentState = "approval"
	// AgentStateQuestion is a AgentState of type question.
	AgentStateQuestion AgentState = "question"
	// AgentStateReady is a AgentState of type ready.
	AgentStateReady AgentState = "ready"
	// AgentStateUnknown is a AgentState of type unknown.
	AgentStateUnknown AgentState = "unknown"
	// AgentStateMissing is a AgentState of type missing.
	AgentStateMissing AgentState = "missing"
)

var ErrInvalidAgentState = fmt.Errorf("not a valid AgentState, try [%s]", strings.Join(_AgentStateNames, ", "))

var _AgentStateNames = []string{
	string(AgentStateActive),
	string(AgentStateApproval),
	string(AgentStateQuestion),
	string(AgentStateReady),
	string(AgentStateUnknown),
	string(AgentStateMissing),
}

// AgentStateNames returns a list of possible string values of AgentState.
func AgentStateNames() []string {
	tmp := make([]string, len(_AgentStateNames))
	copy(tmp, _AgentStateNames)
	return tmp
}

// String implements the Stringer interface.
func (x AgentState) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x AgentState) IsValid() bool {
	_, err := ParseAgentState(string(x))
	return err == nil
}

var _AgentStateValue = map[string]AgentState{
	"active":   AgentStateActive,
	"approval": AgentStateApproval,
	"question": AgentStateQuestion,
	"ready":    AgentStateReady,
	"unknown":  AgentStateUnknown,
	"missing":  AgentStateMissing,
}

// ParseAgentState attempts to convert a string to a AgentState.
func ParseAgentState(name string) (AgentState, error) {
	if x, ok := _AgentStateValue[name]; ok {
		return x, nil
	}
	// Case insensitive parse, do a separate lookup to prevent unnecessary cost of lowercasing a string if we don't need to.
	if x, ok := _AgentStateValue[strings.ToLower(name)]; ok {
		return x, nil
	}
	return AgentState(""), fmt.Errorf("%s is %w", name, ErrInvalidAgentState)
}

// MarshalText implements the text marshaller method.
func (x AgentState) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *AgentState) UnmarshalText(text []byte) error {
	tmp, err := ParseAgentState(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *AgentState) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
